#!/bin/bash
export LANG=zh_CN.gbk
export LANGUAGE=zh_CN.GBK
alias cdi="cd $HOME/bank/src/include"
alias cdp="cd $HOME/bank/src/public"
alias cds="cd $HOME/bank/src"
alias cdf="cd $HOME/bank/src/func"
alias bank="cd $HOME/bank/src/bank"
alias cdg="cd $HOME/bank/log"
alias cdb="cd $HOME/bank/bin"
alias cdsb="cd $HOME/bank/sbin"
export PATH=$PATH:$HOME/bank/sbin:$HOME/bank/bin:$HOME/bank/src/bank:$HOME/bank/src/public
export BIN_PATH=$HOME/bank/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/bank/lib