//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by cpucard.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_BARDEMTYPE                  129
#define IDD_DIALOGBAR                   130
#define IDB_BUTBMP                      131
#define IDI_ICON3                       133
#define IDI_ICON2                       134
#define IDD_DIALOGBAR2                  135
#define IDI_ICON1                       136
#define IDD_DIALOGBAR3                  136
#define IDD_INPUTPWD                    137
#define IDD_DIALOGBAR4                  138
#define IDD_DIALOGBAR5                  139
#define IDD_DLG_CONNECT                 140
#define IDC_COMBO1                      1002
#define IDC_CMB_SAM                     1002
#define IDC_CMB_FIELD                   1002
#define IDC_COMBO_PORT                  1002
#define IDC_water_type                  1002
#define IDC_CHECK1                      1003
#define IDC_CMB_PORT                    1003
#define IDC_COMBO2                      1003
#define IDC_COMBO_BAUD                  1003
#define IDC_CHECK2                      1004
#define IDC_EDIT1                       1005
#define IDC_EDIT_TERMID                 1005
#define IDC_EDIT_PIN                    1005
#define IDC_EDIT_FIELDVAL               1005
#define ID_EDT_INFO                     1005
#define IDC_TREE1                       1006
#define IDC_EDIT_KEY1                   1007
#define IDC_EDIT_KEY2                   1008
#define IDC_EDIT_KEY3                   1009
#define IDC_EDIT_PWD                    1010
#define IDC_EDIT_PRIMAYKEY              1011
#define IDC_BTN_GENPRIMAYKEY            1012
#define IDC_PUBLISHKEYCARD              1013
#define IDC_RECYCLECARD                 1014
#define IDC_RADIO1                      1015
#define IDC_RADIO2                      1016
#define IDC_BTN_READKEYCARD             1020
#define IDC_PUBLISHPSAMCARD             1021
#define IDC_BTN_RECYCLEPSAMCARD         1022
#define IDC_SPIN1                       1023
#define IDC_PUBLISHCARD                 1025
#define IDC_EDIT2                       1026
#define IDC_BTN_RECYCLECARD             1027
#define IDC_BTN_RECYCLECARD2            1028
#define IDC_BTN_REFINECARD              1028
#define IDC_BTN_SZROAD                  1029
#define IDC_STATIC_INFO                 1030
#define IDC_BTN_SZROADADD               1030
#define IDC_READBASEINFO                1031
#define IDC_BTN_XT                      1031
#define IDC_BTN_READPERSONINFO          1032
#define IDC_BTN_XTADD                   1032
#define IDC_BTN_READPARA                1033
#define IDC_BTN_HD                      1033
#define IDC_BTN_READPARA2               1034
#define IDC_BTN_HDADD                   1034
#define IDC_BTN_READBALANCE             1035
#define IDC_BTN_HDADD2                  1035
#define IDC_BTN_FORMATMF                1035
#define IDC_READPUBLICINFO2             1036
#define IDC_BTN_PSAMRESET               1036
#define IDC_BTN_HDPARAM                 1036
#define IDC_BTN_READPERSONINFO2         1037
#define IDC_BTN_RUNAPDU                 1037
#define IDC_BTN_READBALANCE2            1038
#define IDC_EDIT_CMDSTR                 1038
#define IDC_BTN_PAYMENT                 1038
#define IDC_BTN_READBALANCE3            1039
#define IDC_PUBLISHSUPERCARD            1039
#define IDC_BTN_ADDMONEY                1039
#define IDC_BTN_RECYCLESUPERCARD        1040
#define IDC_BTN_PAYMENT2                1040
#define IDC_BTN_REVERSE                 1040
#define IDC_LIST_CMD                    1048
#define IDC_BTN_SETREAD                 1050
#define IDC_BTN_SETWRITE                1051
#define IDC_BTN_READ                    1052
#define IDC_BTN_WRITE                   1053
#define IDC_BTN_CLEARALL                1055
#define IDC_BTN_REQUESTCARD             1056
#define IDC_BTN_GETKEY                  1057
#define IDC_BTN_SETBALANCE              1058
#define IDC_BTN_READPSAMCARD            1059
#define IDC_BTN_VERIFYPWD               1060
#define IDC_BTN_RESETPWD                1061
#define IDC_BTN_CLONECARD               1062
#define IDC_BTN_RESETPWD2               1062
#define IDC_BTN_CARDDTL                 1062
#define IDC_BTN_SAVEKEYS                1063
#define IDC_BUTTON1                     1064
#define ID_BTN_INITPARAM                1066
#define ID_BTN_INITCARD                 1067
#define IDC_EDT_WATERSECT               1068
#define ID_BTN_INITPARAM2               1069
#define IDC_BTN_OPENPORT                1069
#define ID_EDT_UNIT                     1070
#define ID_EDT_TRANS                    1071
#define IDC_MONTHCALENDAR1              1072
#define IDC_BUTTON2                     1073
#define IDC_BTN_TEST                    1074
#define IDC_BUTTON3                     1075
#define ID_BTN_POSPAID                  1075
#define IDC_WrOldWater                  1075
#define IDC_SLIDER2                     1076
#define ID_BTN_INITPOSTPAID             1077
#define IDC_RdOldWater                  1078
#define ID_BTN_GETPROVE4PAY2            1079
#define IDC_POLDWater                   1079
#define IDC_ROldWater                   1080
#define IDC_BUTTON8                     1084
#define IDC_BUTTON9                     1085
#define IDC_waterdumpdata               1086
#define IDC_setmfkey                    1087
#define IDC_BTN_HALT                    1088
#define IDC_BTN_SETM1KEY                1089
#define ID_EDT_M1KEY                    1090
#define ID_BTN_CHECKWRITECARD           1092
#define ID_PAYMONEY                     1093
#define ID_SHOWLEFTBAR                  32771
#define ID_SHOWBOTTOMBAR                32772
#define IDM_OPENPORT                    32773
#define IDM_CLOSEPORT                   32774
#define IDC_MYTREECTRL                  61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
