/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Oct 27 15:41:04 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.kingstargroup.form;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the MAP_CAUNBALANCE_TABLE
 * table.  This object should only be instantiated for use with instances 
 * of the MapCaunbalanceTable class.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized 
 * by MyEclipse Hibernate tool integration.
 */
public class MapCaunbalanceTableKey
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private volatile int hashValue = 0;

    /** The value of the ACCOUNT_ID component of this composite id. */
    private java.lang.String accountId;

    /** The value of the ANALYSIS_TIME component of this composite id. */
    private java.lang.String analysisTime;

    /**
     * Simple constructor of MapCaunbalanceTableKey instances.
     */
    public MapCaunbalanceTableKey()
    {
    }

    /**
     * Returns the value of the accountId property.
     * @return java.lang.String
     */
    public java.lang.String getAccountId()
    {
        return accountId;
    }

    /**
     * Sets the value of the accountId property.
     * @param accountId
     */
    public void setAccountId(java.lang.String accountId)
    {
        hashValue = 0;
        this.accountId = accountId;
    }

    /**
     * Returns the value of the analysisTime property.
     * @return java.lang.String
     */
    public java.lang.String getAnalysisTime()
    {
        return analysisTime;
    }

    /**
     * Sets the value of the analysisTime property.
     * @param analysisTime
     */
    public void setAnalysisTime(java.lang.String analysisTime)
    {
        hashValue = 0;
        this.analysisTime = analysisTime;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the id components.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof MapCaunbalanceTableKey))
            return false;
        MapCaunbalanceTableKey that = (MapCaunbalanceTableKey) rhs;
        if (this.getAccountId() == null || that.getAccountId() == null)
        {
            return false;
        }
        if (! this.getAccountId().equals(that.getAccountId()))
        {
            return false;
        }
        if (this.getAnalysisTime() == null || that.getAnalysisTime() == null)
        {
            return false;
        }
        if (! this.getAnalysisTime().equals(that.getAnalysisTime()))
        {
            return false;
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int accountIdValue = this.getAccountId() == null ? 0 : this.getAccountId().hashCode();
            result = result * 37 + accountIdValue;
            int analysisTimeValue = this.getAnalysisTime() == null ? 0 : this.getAnalysisTime().hashCode();
            result = result * 37 + analysisTimeValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
