#!/usr/bin/sh
BCCPROC="bcc"
for i in $BCCPROC
do
    ps -u $LOGNAME -f |grep "$i"|grep -v "grep"|awk '{print "echo  "$0";"$NF " stop"}'|sh
done

BUPROC="bcc bu"
for i in $BUPROC
do
    ps -u $LOGNAME -f |grep "$i"|grep -v "grep"|awk '{print "echo ",$0,";","kill -9 ",$2}'|sh
done
