package com.sungard.smartcard.bccsvr.modules.user.domain;

import com.sungard.smartcard.annotation.TransfersElement;
import com.sungard.smartcard.annotation.TransfersNodeIn;
import com.sungard.smartcard.annotation.TransfersNodeOut;
import com.sungard.smartcard.annotation.TransfersNodeType;

@TransfersElement
public class Authority {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column ACCT_AUTHORITY.ID
     * 
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    @TransfersNodeIn(value = TransfersNodeType.sphone, desc = "测试")
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column ACCT_AUTHORITY.NAME
     * 
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    @TransfersNodeOut(value = TransfersNodeType.sname, desc = "out测试")
    private String name;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column ACCT_AUTHORITY.ID
     * 
     * @return the value of ACCT_AUTHORITY.ID
     * 
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column ACCT_AUTHORITY.ID
     * 
     * @param id
     *            the value for ACCT_AUTHORITY.ID
     * 
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column ACCT_AUTHORITY.NAME
     * 
     * @return the value of ACCT_AUTHORITY.NAME
     * 
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column ACCT_AUTHORITY.NAME
     * 
     * @param name
     *            the value for ACCT_AUTHORITY.NAME
     * 
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}