package org.king.check.domain;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractWorkinfodetail generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractWorkinfodetail extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String detailid;
     private String checkdate;
     private String dutycheckdate;
     private String infotype;
     private Integer exceptionmins;


    // Constructors

    /** default constructor */
    public AbstractWorkinfodetail() {
    }

    
    /** full constructor */
    public AbstractWorkinfodetail(String checkdate, String dutycheckdate, String infotype,Integer exceptionmins) {
        this.checkdate = checkdate;
        this.dutycheckdate = dutycheckdate;
        this.infotype = infotype;
        this.exceptionmins = exceptionmins;
    }

   
    // Property accessors

    public String getDetailid() {
        return this.detailid;
    }
    
    public void setDetailid(String detailid) {
        this.detailid = detailid;
    }

    public String getCheckdate() {
        return this.checkdate;
    }
    
    public void setCheckdate(String checkdate) {
        this.checkdate = checkdate;
    }

    public String getDutycheckdate() {
        return this.dutycheckdate;
    }
    
    public void setDutycheckdate(String dutycheckdate) {
        this.dutycheckdate = dutycheckdate;
    }

    public String getInfotype() {
        return this.infotype;
    }
    
    public void setInfotype(String infotype) {
        this.infotype = infotype;
    }



	public boolean equals(Object arg0) {
		// TODO Auto-generated method stub
		return false;
	}


	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}


	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}


	public Integer getExceptionmins() {
		return exceptionmins;
	}


	public void setExceptionmins(Integer exceptionmins) {
		this.exceptionmins = exceptionmins;
	}
   








}