package org.king.check.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * Irregularrestmap generated by MyEclipse - Hibernate Tools
 */
public class Irregularrestmap extends AbstractIrregularrestmap implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 6959319181902443998L;


	/** default constructor */
    public Irregularrestmap() {
    }

    
    /** full constructor */
    public Irregularrestmap(String irregularrestid, Integer clerkid) {
        super(irregularrestid, clerkid);        
    }


	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}


	public boolean equals(Object arg0) {
		// TODO Auto-generated method stub
		return false;
	}


	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}
   
}
