package org.king.check.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * Manager generated by MyEclipse - Hibernate Tools
 */
public class Manager extends AbstractManager implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Manager() {
    }

    
    /** full constructor */
    public Manager(String username, String truename, String password, String departmentid, Integer role) {
        super(username, truename, password, departmentid, role);        
    }


	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}


	public boolean equals(Object arg0) {
		// TODO Auto-generated method stub
		return false;
	}


	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}
   
}
