package org.king.check.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * Worktimepara generated by MyEclipse - Hibernate Tools
 */
public class Worktimepara extends AbstractWorktimepara implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Worktimepara() {
    }

    
    /** full constructor */
    public Worktimepara(String ondutytime, String offdutytime) {
        super(ondutytime, offdutytime);        
    }


	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}


	public boolean equals(Object arg0) {
		// TODO Auto-generated method stub
		return false;
	}


	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}
   
}
