CREATE TABLE YKT_CUR.T_RPTTERMLEDGER  (
   ACCDATE              VARCHAR(8)                      NOT NULL,
   TERMID               INTEGER                         NOT NULL,
   SUBJNO               VARCHAR(6)                      NOT NULL,
   ACCNO                VARCHAR(10)                     NOT NULL,
   TRANSTYPE            INTEGER,
   SUMMARY              VARCHAR(60)                     NOT NULL,
   TRANSCNT             INTEGER,
   DRAMT                NUMBER(15,2),
   CRAMT                NUMBER(15,2),
   CONSTRAINT PK_T_RPTTERMLEDGER PRIMARY KEY (ACCDATE, TERMID, ACCNO, SUMMARY)
)
TABLESPACE TS_YKT_CUR;

COMMENT ON TABLE YKT_CUR.T_RPTTERMLEDGER IS
'T_RPTTERMLEDGER-终端分类账表';

COMMENT ON COLUMN YKT_CUR.T_RPTTERMLEDGER.ACCDATE IS
'业务日期';

COMMENT ON COLUMN YKT_CUR.T_RPTTERMLEDGER.TERMID IS
'终端编号';

COMMENT ON COLUMN YKT_CUR.T_RPTTERMLEDGER.SUBJNO IS
'科目号';

COMMENT ON COLUMN YKT_CUR.T_RPTTERMLEDGER.ACCNO IS
'账号';

COMMENT ON COLUMN YKT_CUR.T_RPTTERMLEDGER.TRANSTYPE IS
'交易类型';

COMMENT ON COLUMN YKT_CUR.T_RPTTERMLEDGER.SUMMARY IS
'摘要';

COMMENT ON COLUMN YKT_CUR.T_RPTTERMLEDGER.TRANSCNT IS
'交易次数';

COMMENT ON COLUMN YKT_CUR.T_RPTTERMLEDGER.DRAMT IS
'借方发生额';

COMMENT ON COLUMN YKT_CUR.T_RPTTERMLEDGER.CRAMT IS
'贷方发生额';


CREATE TABLE YKT_CUR.T_RPTDEPTLEDGER  (
   ACCDATE              VARCHAR(8)                      NOT NULL,
   DEPTCODE             VARCHAR(30)                     NOT NULL,
   SUBJNO               VARCHAR(6)                      NOT NULL,
   TRANSTYPE            INTEGER                         NOT NULL,
   SUMMARY              VARCHAR(60)                     NOT NULL,
   TRANSCNT             INTEGER,
   DRAMT                NUMBER(15,2),
   CRAMT                NUMBER(15,2),
   CONSTRAINT PK_T_RPTDEPTLEDGER PRIMARY KEY (ACCDATE, DEPTCODE, SUBJNO, SUMMARY)
)
TABLESPACE TS_YKT_CUR;

COMMENT ON TABLE YKT_CUR.T_RPTDEPTLEDGER IS
'T_RPTDEPTLEDGER-部门分类账表';

COMMENT ON COLUMN YKT_CUR.T_RPTDEPTLEDGER.ACCDATE IS
'业务日期';

COMMENT ON COLUMN YKT_CUR.T_RPTDEPTLEDGER.DEPTCODE IS
'部门代码';

COMMENT ON COLUMN YKT_CUR.T_RPTDEPTLEDGER.SUBJNO IS
'科目号';

COMMENT ON COLUMN YKT_CUR.T_RPTDEPTLEDGER.TRANSTYPE IS
'交易类型';

COMMENT ON COLUMN YKT_CUR.T_RPTDEPTLEDGER.SUMMARY IS
'摘要';

COMMENT ON COLUMN YKT_CUR.T_RPTDEPTLEDGER.TRANSCNT IS
'交易次数';

COMMENT ON COLUMN YKT_CUR.T_RPTDEPTLEDGER.DRAMT IS
'借方发生额';

COMMENT ON COLUMN YKT_CUR.T_RPTDEPTLEDGER.CRAMT IS
'贷方发生额';


-- Create table
create table ykt_cur.T_RCSTATDATA
(
  CARD_NO INTEGER not null,
  MEAL    CHAR(20) not null,
  TX_DATE CHAR(8) not null,
  AMOUNT  NUMBER(15,2),
  CONSTRAINT PK_T_RCSTATDATA PRIMARY KEY (CARD_NO, MEAL, TX_DATE)
)
tablespace TS_YKT_CUR
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    minextents 1
    maxextents unlimited
  );
-- Create/Recreate indexes 
create index IDX_RCSTATDATA on ykt_cur.T_RCSTATDATA (CARD_NO, MEAL, TX_DATE)
  tablespace TS_YKT_CUR
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    minextents 1
    maxextents unlimited
  );
  
  
  