grant select on YKT_CUR.T_TRANSDTL to YKT_PORTAL;
grant select on YKT_CUR.T_POSDTL to YKT_PORTAL;
grant select, insert, delete, index on YKT_CUR.T_MSGLIST to YKT_PORTAL;
grant select, insert, delete, index on YKT_CUR.T_CARDVER to YKT_PORTAL;
grant select on YKT_CUR.T_DICTIONARY to YKT_PORTAL;
grant select on YKT_CUR.T_TRANSCODE to YKT_PORTAL;
grant select, update on YKT_CUR.T_CARD to YKT_PORTAL;
grant select on YKT_CUR.T_DEVICE to YKT_PORTAL;
grant select on YKT_CUR.T_PHOTO to YKT_PORTAL;
grant select on YKT_CUR.T_SPECIALTY to YKT_PORTAL;
grant select on YKT_CUR.T_CUSTOMER to YKT_PORTAL;
grant select on YKT_CUR.T_DEPT to YKT_PORTAL;
grant select on YKT_CUR.T_ACCOUNT to YKT_PORTAL;
grant select on YKT_CUR.T_CARDTYPE to YKT_PORTAL;
grant select on ykt_cur.t_feetype to YKT_PORTAL;

grant select on ykt_cur.t_rptposledger to YKT_PORTAL;
grant select on ykt_cur.t_rptshoprakeoff to YKT_PORTAL;
grant select on ykt_cur.t_shop to YKT_PORTAL;
grant select on ykt_cur.v_device to YKT_PORTAL;
grant select on ykt_cur.t_transtype to YKT_PORTAL;
grant select on ykt_cur.t_rptsubjledger to YKT_PORTAL;
grant select on ykt_cur.t_custtype to YKT_PORTAL;
grant select on ykt_cur.t_rptopercash to YKT_PORTAL;
grant select on ykt_cur.t_specialty to YKT_PORTAL;
grant select on ykt_cur.T_RCSTATDATA to YKT_PORTAL;
grant select on ykt_cur.t_rpttermledger to ykt_portal;
grant select on ykt_cur.t_rptdeptledger to ykt_portal;
grant select on ykt_cur.v_term to ykt_portal;
grant select on YKT_CUR.V_TRANSDTL to YKT_PORTAL;
grant select on ykt_cur.t_doordtl  to ykt_portal;
grant select on YKT_CUR.T_TRANSDTL to YKT_PORTAL;
grant select on YKT_CUR.T_POSDTL to YKT_PORTAL;
grant select, insert, delete, index on YKT_CUR.T_MSGLIST to YKT_PORTAL;
grant select, insert, delete, index on YKT_CUR.T_CARDVER to YKT_PORTAL;
grant select on YKT_CUR.T_DICTIONARY to YKT_PORTAL;
grant select on YKT_CUR.T_TRANSCODE to YKT_PORTAL;
grant select, update on YKT_CUR.T_CARD to YKT_PORTAL;
grant select on YKT_CUR.T_DEVICE to YKT_PORTAL;
grant select on YKT_CUR.T_PHOTO to YKT_PORTAL;
grant select on YKT_CUR.T_SPECIALTY to YKT_PORTAL;
grant select on YKT_CUR.T_CUSTOMER to YKT_PORTAL;
grant select on YKT_CUR.T_DEPT to YKT_PORTAL;
grant select on YKT_CUR.T_ACCOUNT to YKT_PORTAL;
grant select on YKT_CUR.T_CARDTYPE to YKT_PORTAL;
grant select on ykt_cur.t_feetype to YKT_PORTAL;
grant select on YKT_CUR.t_cardtype to YKT_PORTAL;
grant select on YKT_CUR.t_area to YKT_PORTAL;
grant select, insert, update, delete, index on YKT_CUR.t_bankcard to YKT_PORTAL;
grant select on ykt_cur.t_brastransdtl to ykt_portal;

grant select on ykt_cur.t_rptposledger to YKT_PORTAL;
grant select on ykt_cur.t_rptshoprakeoff to YKT_PORTAL;
grant select on ykt_cur.t_shop to YKT_PORTAL;
grant select on ykt_cur.v_device to YKT_PORTAL;
grant select on ykt_cur.t_transtype to YKT_PORTAL;
grant select on ykt_cur.t_custtype to YKT_PORTAL;
grant select on ykt_cur.t_rptopercash to YKT_PORTAL;
grant select on ykt_cur.t_specialty to YKT_PORTAL;
grant select on ykt_cur.v_term to ykt_portal;
grant select on YKT_CUR.V_TRANSDTL to YKT_PORTAL;
grant select,insert,update,delete,index on ykt_cur.t_losscardinfo to YKT_PORTAL;
grant select,insert,update,delete,index on ykt_cur.t_losscardshop to YKT_PORTAL;
grant select on ykt_cur.v_accdtl to ykt_portal;
grant select,update,insert,delete on ykt_cur.t_cardbalance to ykt_portal;
grant select,update,insert,delete on ykt_cur.t_account to ykt_portal;
grant select on ykt_cur.t_doordtl  to ykt_portal;
grant select on YKT_CUR.T_RPTSYSSTAT   to ykt_portal;