package com.kingstargroup.mobileMessage.hibernate;

import java.util.Date;


/**
 * AbstractSCmMessages generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSCmMessages  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String SDate;
     private String STime;
     private Integer SObjectType;
     private String SObject;
     private String SContent;
     private Integer SSuccess;
     private Integer SPro;


    // Constructors

    /** default constructor */
    public AbstractSCmMessages() {
    }

    
    /** full constructor */
    public AbstractSCmMessages(Long id, String SDate, String STime, Integer SObjectType, String SObject, String SContent, Integer SSuccess, Integer SPro) {
        this.id = id;
        this.SDate = SDate;
        this.STime = STime;
        this.SObjectType = SObjectType;
        this.SObject = SObject;
        this.SContent = SContent;
        this.SSuccess = SSuccess;
        this.SPro = SPro;
    }
    

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getSDate() {
        return this.SDate;
    }
    
    public void setSDate(String SDate) {
        this.SDate = SDate;
    }

    public String getSTime() {
        return this.STime;
    }
    
    public void setSTime(String STime) {
        this.STime = STime;
    }

    public Integer getSObjectType() {
        return this.SObjectType;
    }
    
    public void setSObjectType(Integer SObjectType) {
        this.SObjectType = SObjectType;
    }

    public String getSObject() {
        return this.SObject;
    }
    
    public void setSObject(String SObject) {
        this.SObject = SObject;
    }

    public String getSContent() {
        return this.SContent;
    }
    
    public void setSContent(String SContent) {
        this.SContent = SContent;
    }

    public Integer getSSuccess() {
        return this.SSuccess;
    }
    
    public void setSSuccess(Integer SSuccess) {
        this.SSuccess = SSuccess;
    }

    public Integer getSPro() {
        return this.SPro;
    }
    
    public void setSPro(Integer SPro) {
        this.SPro = SPro;
    }
   








}