package org.king.security.domain;

import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;



/**
 * AbstractAccount generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractAccount extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String id;
     private String name;
     private String password;
     private String enabled;
     private Integer custId;

     private String repassword;

     private Person person = new Person();
     
     private Set roles;
     
    // Constructors

    /** default constructor */
    public AbstractAccount() {
    }

	/** minimal constructor */
    public AbstractAccount(String name) {
        this.name = name;
    }
    
    /** full constructor */
    public AbstractAccount(String name, String password, String enabled,Integer custId) {
        this.name = name;
        this.password = password;
        this.enabled = enabled;
        this.custId = custId;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    public String getRepassword() {
		return repassword;
	}

	public void setRepassword(String repassword) {
		this.repassword = repassword;
	}

	public String getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }

    public Person getPerson() {
		return person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Set getRoles() {
		return roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

    public Integer getCustId() {
        return custId;
    }

    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof AbstractAccount)) {
			return false;
		}
		AbstractAccount rhs = (AbstractAccount) object;
		return new EqualsBuilder().append(this.password, rhs.password).append(
				this.enabled, rhs.enabled).append(this.name, rhs.name).append(
				this.id, rhs.id).isEquals();
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(-1087829107, -1278696151).append(
				this.password).append(this.enabled).append(this.name).append(
				this.id).toHashCode();
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
				.append("name", this.name).append("id", this.id).append(
						"enabled", this.enabled).append("password",
						this.password).toString();
	}
   

    







}