package org.king.check.domain;



/**
 * AbstractTattserial generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTattserial extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private TattserialId id;
     private Integer cardId;
     private String phyId;
     private String showCardno;
     private String attDate;
     private String attTime;
     private Integer txMark;
     private String status;


    // Constructors

    /** default constructor */
    public AbstractTattserial() {
    }

    
    /** full constructor */
    public AbstractTattserial(Integer cardId, String phyId, String showCardno, String attDate, String attTime, Integer txMark, String status) {
        this.cardId = cardId;
        this.phyId = phyId;
        this.showCardno = showCardno;
        this.attDate = attDate;
        this.attTime = attTime;
        this.txMark = txMark;
        this.status = status;
    }

   
    // Property accessors

    public TattserialId getId() {
        return this.id;
    }
    
    public void setId(TattserialId id) {
        this.id = id;
    }

    public Integer getCardId() {
        return this.cardId;
    }
    
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }

    public String getPhyId() {
        return this.phyId;
    }
    
    public void setPhyId(String phyId) {
        this.phyId = phyId;
    }

    public String getShowCardno() {
        return this.showCardno;
    }
    
    public void setShowCardno(String showCardno) {
        this.showCardno = showCardno;
    }

    public String getAttDate() {
        return this.attDate;
    }
    
    public void setAttDate(String attDate) {
        this.attDate = attDate;
    }

    public String getAttTime() {
        return this.attTime;
    }
    
    public void setAttTime(String attTime) {
        this.attTime = attTime;
    }

    public Integer getTxMark() {
        return this.txMark;
    }
    
    public void setTxMark(Integer txMark) {
        this.txMark = txMark;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
   








}