/************************************************************************
*               BY:  M.Kuwahara
*             DATE:  1997/04/23
*        FILE NAME:  fla_tbl.h
*       Task ID No:  Not Valid
*      DESCRIPTION:  ÇqÇnÇlÅQÇlÇ`ÇoÉeÅ[ÉuÉãíËã`
*        REFERENCE:
************************************************************************/
#include "\src\atlanta\define\product.h"

/************************************************************************
*               BY:  M.Kuwahara
*             DATE:  97/04/23
*             TYPE:
*      VAR TO HOLD:
*      DESCRIPTION:  ÇqÇnÇlÅQÇlÇ`ÇoÉeÅ[ÉuÉã
************************************************************************/
extern CONST struct ROM_MAP_t SYS_RomMap[];

