/*--------------------------------------------------------------------------*/
/*プロジェクト: POPLAR_H													*/
/*モジュ-ル名 : POPHVTIB.C													*/
/*作成者名	  : 小谷正樹													*/
/*日  付	  : 97.06.24													*/
/*概  要	  : タスク登録													*/
/*修正履歴	  : \src\atlanta\sh7043\def_v\defv_tib.cから機種別に移動		*/
/*            : とりあえず、POPLAR_Hからコピーしました1998/05/07 H.Yoshikawa*/
/*--------------------------------------------------------------------------*/
#include "\src\atlanta\hinoki\define\hino_tib.h"
#include "\src\atlanta\sh7043\define\tib_pro.h"
#include "\src\atlanta\sh7043\define\mon_func.h"

/*---------------------------------------------------------------*/
/* !!!!!!!!!!!!!!!!!!!!!!!!!!!!注意 !!!!!!!!!!!!!!!!!!!!!!!!!!!! */
/* タクス優先順位に付いては、必ず木元まで相談してください。
** 尚、当面、下記ユーティリティーの使用を全面禁止します。
** By O.Kimoto 1998/04/03 */

/* タスクの親子関係見直しにて以下の優先順位に矛盾がありましたので直接変更します
**
**	ATD_TONEDETECTPATTERN1TASK 210->170
**	MAN_WATCHDOCUMENTSETTASK   190->120
**	MAN_WATCHDOCUMENTOUTTASK   190->120
**	MAN_WATCHDOCUMENTFEEDTASK  190->120
**	MAN_WATCHDOCUMENTCOVERTASK 190->120
**	ATD_TONEDETECTPATTERN0TASK 210->170
**	ATD_CHECKFILTER1OFFTASK    200->160
**	ATD_CHECKFILTER2OFFTASK    200->160
**	ATD_CHECKFILTER3OFFTASK    200->160
**	PRN_PAPERFEEDTASK          190->120
**	PRN_LISTDOCUMENTOUTTASK    190->120
**	CMN_EVENTTOMESSAGETASK     140->110
**	CMN_MAN_TIMER10MSTASK      140->110
**	PRN_CHECKTONERTASK         190->120
**	PRN_HIGHVOLTAGETASK        150->120
**	PRN_GETRESISTTASK          150->110
**	ATD_LC_OFFCHECKTASK        210->200
**	MDM_ABCODE_TASK            210->200
**	V34_TXHANDSHAKEMONITORTASK 210->200
**	V34_RXHANDSHAKEMONITORTASK 210->200
**
** 1998/04/06 by T.Soenoka */

/* 
**     このファイル (POPHVTIB.C) は直接編集しないでください。
**
**  タスクの追加は \src\atlanta\poplar_h\cmn\tib.cmn で行ってください。
*/
/*---------------------------------------------------------------*/

/*-------------------------*/
/*
*   Kubo Hiroshi 1997/07/02
*	This part is generated by TASKPRIO command.
*    See template file in cmn\template\pophvtib.c and cmn\tib.cmn
*/

CONST struct	tib_table_data_t tib[] = {
/*-------------------------------------------------------------------*/
/* \
*	タスク順序記述ファイル \
* \
* Originally created from \src\atlanta\poplar_h\def_v\tib_pro.h by H.Kubo 1997/07/01 \
* \
* \
*/
/* スタックの大きさ : 1 => small , 0 => large
/* タスク名 終了関数 スタックの大きさ （仮）タスク順位 下位のタスク名 */
	{											/* 0 */
		/* イニシャル */                        
		MAN_IdleTask,                           
		exi_tsk_irom,                           
		1,                                      
		250
	},                                          
	{                                           /* 1 */
		/*  メインタスク */                     
		MAN_Task,                               
		exi_tsk_irom,                           
		0,                                      
		240
	},                                          
	{                                           /* 2 */
		/*  Timer Task */                       
		MAN_TimerTask,                          
		exi_tsk_irom,                           
		0,                                      
		210
	},                                          
	{                                           /* 3 */
		/*  Sensor Task */                      
		MAN_SensorTask,                         
		exi_tsk_irom,                           
		0,                                      
		210
	},                                          
	{                                           /* 4 */
		/* 標準10msタイマータスク */            
		CMN_WatchTimer10msTask,                 
		exi_tsk_irom,                           
		1,                                      
		140
	},                                          
	{                                           /* 5 */
		/* 標準10msタイマーイベント発生タスク */
		CMN_WatchTimer10msEventTask,            
		exi_tsk_irom,                           
		1,                                      
		120
	},                                          
	{                                           /* 6 */
		/* メインタスクと同期をとるための10msタイマータスク */
		CMN_MAN_Timer10msTask,                  
		exi_tsk_irom,                           
		1,                                      
		110
	},                                          
	{                                           /* 7 */
		/* １０ｍＳマルチタイマータスク */      
		CMN_MultiTimer10msTask,                 
		exi_tsk_irom,                           
		1,                                      
		140
	},                                          
	{                                           /* 8 */
		/*  イベントを検出したらメッセージを送るタスク */
		CMN_EventToMessageTask,                 
		exi_tsk_irom,                           
		1,                                      
		110
	},                                          
	{                                           /* 9 */
		/* アック・ナックブザー鳴動タスク */    
		CMN_BuzzerTask,                         
		exi_tsk_irom,                           
		1,                                      
		170
	},                                          
	{                                           /* 10 */
		/* エンドブザー鳴動タスク */            
		CMN_EndBuzzerTask,                      
		CMN_EndBuzzerExit,                      
		1,                                      
		210
	},                                          
	{                                           /* 11 */
		/* 保留アラーム鳴動タスク */            
		CMN_HoldAlarmTask,                      
		exi_tsk_irom,                           
		1,                                      
		210
	},                                          
	{                                           /* 12 */
		/* エラーアラーム鳴動タスク */          
		CMN_ErrorAlarmTask,                     
		CMN_ErrorAlarmExit,                     
		1,                                      
		210
	},                                          
	{                                           /* 13 */
		/* エラーエンドレスアラーム鳴動タスク */
		CMN_ErrorEndlessAlarmTask,              
		CMN_ErrorEndlessAlarmExit,              
		1,                                      
		210
	},                                          
	{                                           /* 14 */
		/* 通信終了後受話器上がりアラーム鳴動タスク */
		CMN_HungUpErrorAramTask,                
		CMN_HungUpErrorAramExit,                
		1,                                      
		210
	},                                          
	{                                           /* 15 */
		/* 保留終了ブザー鳴動タスク */          
		CMN_HoldEndBuzzerTask,                  
		exi_tsk_irom,                           
		1,                                      
		210
	},                                          
	{                                           /* 16 */
		/* 着信トーン検出（短縮用）10msタイマーイベント発生タスク */
		ATD_WatchTimer10msEventTask,            
		exi_tsk_irom,                           
		1,                                      
		140
	},                                          
	{                                           /* 17 */
		/* Check Filter1 Off  ﾌｨﾙﾀｰ1を通過するﾄｰﾝが無い時にﾒｯｾｰｼﾞを送信するﾀｽｸ */
		ATD_CheckFilter1OffTask,                
		exi_tsk_irom,                           
		1,                                      
		160
	},                                          
	{                                           /* 18 */
		/* Check Filter2 Off  ﾌｨﾙﾀｰ2を通過するﾄｰﾝが無い時にﾒｯｾｰｼﾞを送信するﾀｽｸ */
		ATD_CheckFilter2OffTask,                
		exi_tsk_irom,                           
		1,                                      
		160
	},                                          
	{                                           /* 19 */
		/* Check Filter3 Off  ﾌｨﾙﾀｰ2を通過するﾄｰﾝが無い時にﾒｯｾｰｼﾞを送信するﾀｽｸ */
		ATD_CheckFilter3OffTask,                
		exi_tsk_irom,                           
		1,                                      
		160
	},                                          
	{                                           /* 20 */
		/* Tone Detect Pattern 0 連続ﾊﾟﾀｰﾝのﾄｰﾝ検出ﾀｽｸ */
		ATD_ToneDetectPattern0Task,             
		ATD_ToneDetectPattern0Exit,             
		1,                                      
		170
	},                                          
	{                                           /* 21 */
		/* Tone Detect Pattern 1 断続ﾊﾟﾀｰﾝのﾄｰﾝ検出ﾀｽｸ */
		ATD_ToneDetectPattern1Task,             
		exi_tsk_irom,                           
		1,                                      
		170
	},                                          
	{                                           /* 22 */
		/* LC Off Check ﾙｰﾌﾟ電流検出ﾀｽｸ */      
		ATD_LC_OffCheckTask,                    
		exi_tsk_irom,                           
		1,                                      
		200
	},                                          
	{                                           /* 23 */
		/* AD Check DSE 極性反転検出ﾀｽｸ */      
		ATD_CheckDSETask,                       
		exi_tsk_irom,                           
		1,                                      
		210
	},                                          
	{                                           /* 24 */
		/*  Check Stop	ストップ・キー監視タスク（トーン検出時） */
		ATD_CheckStopTask,                      
		exi_tsk_irom,                           
		1,                                      
		210
	},                                          
	{                                           /* 25 */
		/*  Check	SPD_TONE ﾀｽｸ */             
		ATD_CheckToneTask,                      
		ATD_CheckToneExit,                      
		1,                                      
		210
	},                                          
	{                                           /* 26 */
		/*  Ｖ２５アンサートーン検出タスク */   
		ATD_DetectAnswerToneV25Task,            
		exi_tsk_irom,                           
		1,                                      
		210
	},                                          
	{                                           /* 27 */
		/* ｺｰﾃﾞｯｸが1ﾍﾟｰｼﾞｴﾝｺｰﾄﾞするﾀｽｸ */       
		CDC_EncodePageTask,                     
		exi_tsk_irom,                           
		0,                                      
		180 /*130*/
	},                                          
	{                                           /* 28 */
		/* ｺｰﾃﾞｯｸが1ﾍﾟｰｼﾞﾃﾞｺｰﾄﾞしﾌﾟﾘﾝﾄするﾀｽｸ */
		CDC_DecodePageTask,                     
		exi_tsk_irom,                           
		0,                                      
		120
	},                                          
	{                                           /* 29 */
		/* コーデックがスキャナイメージからエンコードするタスク */
		CDC_STxEncodePageTask,                  
		exi_tsk_irom,                           
		0,                                      
		190
	},                                          
	{                                           /* 30 */
		/* コーデックがキャラクタイメージからエンコードするタスク */
		CDC_CTxCodeConvertPageTask,             
		exi_tsk_irom,                           
		0,                                      
		210
	},                                          
	{                                           /* 31 */
		/* ｺｰﾃﾞｯｸが1ﾍﾟｰｼﾞ蓄積符号から符号変換するﾀｽｸ */
		CDC_MTxCodeConvertPageTask,             
		exi_tsk_irom,                           
		0,                                      
		210
	},                                          
	{                                           /* 32 */
		/* ｺｰﾃﾞｯｸが1ﾍﾟｰｼﾞ蓄積符号に符号変換するﾀｽｸ */
		CDC_MRxCodeConvertPageTask,             
		exi_tsk_irom,                           
		0,                                      
		210
	},                                          
	{                                           /* 33 */
		/* ｺｰﾃﾞｯｸがｲﾒｰｼﾞﾊﾞｯﾌｧにﾃﾞｰﾀ転送するﾀｽｸ */
		CDC_DataTransferPageTask,               
		exi_tsk_irom,                           
		0,                                      
		120
	},                                          
	{                                           /* 34 */
		/* ジャーナルデータ復号化タスク */      
		CDC_DecodeJournalPageTask,              
		exi_tsk_irom,                           
		0,                                      
		120
	},                                          
	{                                           /* 35 */
		/* 56.ＮＣＵタイマタスク */             
		NCU_TimeUpTask,                         
		exi_tsk_irom,                           
		1,                                      
		150
	},                                          
	{                                           /* 36 */
		/* 51.待機状態回線監視タスク */         
		NCU_Task,                               
		NCU_TaskExit,                           
		1,                                      
		230
	},                                          
	{                                           /* 37 */
		/* 52.着信検出タスク */                 
		NCU_DetectCalledTask,                   
		NCU_DetectCalledExit,                   
		1,                                      
		185 /* 190 -> 185 原稿蓄積中（特に中間調）でＣＩのＯＮ期間のサンプリングの処理が、まわってこないので
			** ＣＩリングが検出できないことがあります StorePageTaskより高く、NCU_DetectFnetTaskより低くします
			** changed by H.Hirao 1998/12/29
			*/
	},                                          
	{                                           /* 38 */
		/* 53.受話器ＯＨ状態監視タスク */       
		NCU_TelephoneHookCheckTask,             
		exi_tsk_irom,                           
		1,                                      
		190
	},                                          
	{                                           /* 39 */
		/* 54.Ｆ網監視タスク */                 
		NCU_DetectFnetTask,                     
		exi_tsk_irom,                           
		0,                                      
		180
	},                                          
	{                                           /* 40 */
		/* 55.ＮＣＵ周波数チェックタスク */     
		NCU_FrequencyCheckTask,                 
		exi_tsk_irom,                           
		1,                                      
		170
	},                                          
	{                                           /* 41 */
		/* 57.多機能電話制御メインタスク */     
		NCU_TelephoneOperationTask,             
		NCU_TelephoneOperationExit,             
		0,                                      
		230
	},                                          
	{                                           /* 42 */
		/* 58.(外付)留守番電話着信後タスク */   
		NCU_FaxTadAutoSwitchTask,               
		NCU_FaxTadAutoSwitchExit,               
		0,                                      
		220
	},                                          
	{                                           /* 43 */
		/* 59.電話機能実行タスク */             
		NCU_TelephoneExecuteTask,               
		NCU_TelephoneExecuteExit,               
		0,                                      
		210
	},                                          
	{                                           /* 44 */
		/* 60.外付電話ＤＴＭＦ検出タスク */     
		NCU_ReceiveDTMFTask,                    
		NCU_ReceiveDTMFExit,                    
		1,                                      
		160
	},                                          
	{                                           /* 45 */
		/* 61.(外付)無音検出タスク */           
		NCU_DetectSilentTask,                   
		NCU_DetectSilentExit,                   
		1,                                      
		200
	},                                          
	{                                           /* 46 */
		/* 62.ダイヤルイン着信後タスク */       
		NCU_DialInAutoSwitchTask,               
		exi_tsk_irom,                           
		1,                                      
		230
	},                                          
	{                                           /* 47 */
		/* 63.擬似ＲＢＴ送出(ＣＮＧ検出)タスク */
		NCU_TransRBTAndDetCNGTask,              
		NCU_TransRBTAndDetCNGExit,              
		0,                                      
		180
	},                                          
	{                                           /* 48 */
		/* 64.擬似ベル鳴動ＯＨ検出タスク */     
		NCU_GenerateRingSignalTask,             
		NCU_GenerateRingSignalExit,             
#if (PRO_VOICE_ANSWER == ENABLE) && ((PRO_MODEM == R288F) || (PRO_MODEM == MN195006))	/* NTT音声応答 && ORANGE以外のモデム by J.Kishida 2002/10/22 */
		0,                                      
#else
		1,                                      
#endif
		180
	},                                          
	{                                           /* 49 */
		/* 66 ダイヤル・イン疑似ベル鳴動時極性反転検出 */
		NCU_DetectDSETask,                      
		exi_tsk_irom,                           
		1,                                      
		180
	},                                          
	{                                           /* 50 */
		/* 留守／ＦＡＸ待機時のリモートからのＤＴＭＦ検出タスク 1997/11/19 by H.Kubo */
		NCU_DetectRemoteDTMFTask,               
		exi_tsk_irom,                           
		1,                                      
		160
	},                                          
	{                                           /* 51 */
		/* 通信中のＨＯＯＫ状態変化監視タスク *//* Upper FCM_TASK */
		NCU_FaxComTelHookChkTask,               
		exi_tsk_irom,                           
		1,                                      
		210
	},                                          
	{                                           /* 52 */
		/* 70. ＦＣＳ検出 */                    
		MDM_FcsDetectTask,                      
		exi_tsk_irom,                           
		1,                                      
		170
	},                                          
	{                                           /* 53 */
		/* 72. エンコードＤＭＡ転送終了監視 */  
		MDM_EncodeDMA_TC_DetectTask,            
		exi_tsk_irom,                           
		0,                                      
		200
	},                                          
	{                                           /* 54 */
		/* 73 デコードＤＭＡ転送終了監視 */     
		MDM_DecodeDMA_TC_DetectTask,            
		exi_tsk_irom,                           
		1,                                      
		200
	},                                          
	{                                           /* 55 */
		/* 67. ＦＳＫ送信フレーム監視 */        
		MDM_TxFskFrameControlTask,              
		MDM_TxFskFrameControlExit,              
		0,                                      
		210
	},                                          
	{                                           /* 56 */
		/* 68. ＦＳＫ受信フレーム監視 */        
		MDM_RxFskFrameControlTask,              
		MDM_RxFskFrameControlExit,              
		0,                                      
		210
	},                                          
	{                                           /* 57 */
		/* 69. フラグ検出 */                    
		MDM_FlagDetectTask,                     
		exi_tsk_irom,                           
		1,                                      
		200
	},                                          
	{                                           /* 58 */
		/* 71 モデム割り込み監視タスク */       
		MDM_ModemInterruptTask,                 
		exi_tsk_irom,                           
		1,                                      
		200
	},                                          
	{                                           /* 59 */
		/*  モデムステータス監視タスク */       
		MDM_ModemStatusCheckTask,               
		exi_tsk_irom,                           
		1,                                      
		210
	},                                          
	{                                           /* 60 */
		/*  ＥＣＭ送信フレーム監視 */           
		MDM_TxEcmFrameControlTask,              
		exi_tsk_irom,                           
		0,                                      
		210
	},                                          
	{                                           /* 61 */
		/* ＥＣＭ受信監視タスク */              
		MDM_RxEcmControlTask,                   
		exi_tsk_irom,                           
		0,                                      
		210
	},                                          
	{                                           /* 62 */
		/*  受信デバイス監視タスク */           
		MDM_RxDeviceControlTask,                
		exi_tsk_irom,                           
		0,                                      
		190
	},                                          
	{                                           /* 63 */
		/*  送信デバイス監視タスク */           
		MDM_MTxReadDMA_Task,                    
		exi_tsk_irom,                           
		0,                                      
		210
	},                                          
	{                                           /* 64 */
		/*ＥＱＭリードタスク  Add By O.K Feb.22,1996 *//* Upper FCM_TASK */
		MDM_ReadEqmValueTask,                   
		exi_tsk_irom,                           
		1,                                      
		210
	},                                          
	{                                           /* 65 */
		/* モデムＤＭＡ転送終了監視（受信方向）*//* Upper _CDC_MRxCodeConvertPageTask */
		MDM_RxDMA_TC_DetectTask,                
		exi_tsk_irom,                           
		1,                                      
		200
	},                                          
	{                                           /* 66 */
		/* コントロールチャンネル  リトレイン検出タスク*//* Upper _MDM_FcsDetectTask */
		MDM_CcRetrainDetectTask,                
		exi_tsk_irom,                           
		1,                                      
		160
	},                                          
	{                                           /* 67 */
		/*  サービスファンクション用ＦＳＫ送信タスク */
		MDM_FskTxTask,                          
		exi_tsk_irom,                           
		0,                                      
		210
	},                                          
	{                                           /* 68 */
		/*  サービスファンクション用画データ送信タスク */
		MDM_PixTxTask,                          
		exi_tsk_irom,                           
		0,                                      
		210
	},                                          
	{                                           /* 69 */
		/*  サービスファンクション用タスク *//* Upper FCM_TASK */
		MDM_FactoryFunctionTask,                
		MDM_FactoryFunctionExit,                
		0,                                      
		210
	},                                          
	{                                           /* 70 */
		/*  高速ＲＤＳ データリードタスク */    
		MDM_BackupRamToEcmBufTask,              
		MDM_BackupRamToEcmBufTaskExit,          
		1,                                      
		210
	},                                          
	{                                           /* 71 */
		/*トーンフィルター１状態監視タスク *//* Upper _NCU_DetectSilentTask */
		MDM_DetectFilter1Task,                  
		exi_tsk_irom,                           
		1,                                      
		190
	},                                          
	{                                           /* 72 */
		/* トーンフィルター２状態監視タスク *//* Upper _NCU_DetectSilentTask */
		MDM_DetectFilter2Task,                  
		exi_tsk_irom,                           
		1,                                      
		190
	},                                          
	{                                           /* 73 */
		/*通信タスク */                         
		FCM_Task,                               
		exi_tsk_irom,                           
		0,                                      
		220
	},                                          
	{                                           /* 74 */
		/* Ｖ８ CI 検出タスク *//* Uppe FCM_TASK */
		V34_DetectV8CITask,                     
		exi_tsk_irom,                           
		1,                                      
#if (PRO_VOICE_ANSWER == ENABLE) && ((PRO_MODEM == R288F) || (PRO_MODEM == MN195006))	/* NTT音声応答 && ORANGE以外のモデム by J.Kishida 2002/10/22 */
		/* NCUの音声応答の処理(タスク順位180)から制御しようとしているのでタスクを殺せない */
		160			/* 210 -> 160 1999/10/18 Y.M */
#else
		210
#endif
	},                                          
	{                                           /* 75 */
		/* Ｖ８モード中のＶ２１チャンネル２フラグ検出タスク *//* Upper FCM_TASK */
		MDM_DetectV21Ch2FlagV8Task,             
		MDM_DetectV21Ch2FlagV8TaskExit,         
		1,                                      
#if (PRO_VOICE_ANSWER == ENABLE) && ((PRO_MODEM == R288F) || (PRO_MODEM == MN195006))	/* NTT音声応答 && ORANGE以外のモデム by J.Kishida 2002/10/22 */
		160			/* 210 -> 160 1999/10/18 Y.M */
#else
		210
#endif
	},                                          
	{                                           /* 76 */
		/* ハンドチェークエラー検出タスク *//* Upper FCM_TASK */
		MDM_ABCODE_Task,                        
		exi_tsk_irom,                           
		1,                                      
#if (PRO_VOICE_ANSWER == ENABLE) && ((PRO_MODEM == R288F) || (PRO_MODEM == MN195006))	/* NTT音声応答 && ORANGE以外のモデム by J.Kishida 2002/10/22 */
		150			/* 200 -> 150 1999/10/18 Y.M */
#else
		200
#endif
	},                                          
	{                                           /* 77 */
		/* Ｖ２５アンサートーン検出タスク *//* Upper FCM_TASK */
		V34_DetectV25AnswerToneTask,            
		exi_tsk_irom,                           
		1,                                      
#if (PRO_VOICE_ANSWER == ENABLE) && ((PRO_MODEM == R288F) || (PRO_MODEM == MN195006))	/* NTT音声応答 && ORANGE以外のモデム by J.Kishida 2002/10/22 */
		160			/* 210 -> 160 1999/10/18 Y.M */
#else
		210
#endif
	},                                          
	{                                           /* 78 */
		/* Ｖ８コントールタスク	*//* Upper FCM_TASK */
		V34_V8ControlTask,                      
		V34_V8ControlTaskExit,                  
		1,                                      
#if (PRO_VOICE_ANSWER == ENABLE) && ((PRO_MODEM == R288F) || (PRO_MODEM == MN195006))	/* NTT音声応答 && ORANGE以外のモデム by J.Kishida 2002/10/22 */
		160			/* 210 -> 160 1999/10/18 Y.M */
#else
		210
#endif
	},                                          
	{                                           /* 79 */
		/* 送信ハンドシェークモニタ監視タスク *//* Upper FCM_TASK */
		V34_TxHandshakeMonitorTask,             
		exi_tsk_irom,                           
		1,                                      
#if (PRO_VOICE_ANSWER == ENABLE) && ((PRO_MODEM == R288F) || (PRO_MODEM == MN195006))	/* NTT音声応答 && ORANGE以外のモデム by J.Kishida 2002/10/22 */
		150 		/* 200 -> 150 1999/10/18 Y.M */
#else
		200
#endif
	},                                          
	{                                           /* 80 */
		/* 受信ハンドシェークモニタ監視タスク *//* Uppe FCM_TASK */
		V34_RxHandshakeMonitorTask,             
		exi_tsk_irom,                           
		1,                                      
#if (PRO_VOICE_ANSWER == ENABLE) && ((PRO_MODEM == R288F) || (PRO_MODEM == MN195006))	/* NTT音声応答 && ORANGE以外のモデム by J.Kishida 2002/10/22 */
		150			/* 200 -> 150 1999/10/18 Y.M */
#else
		200
#endif
	},                                          
	{                                           /* 81 */
		/* リストプリント */                    
		LST_PrintTask,                          
		exi_tsk_irom,                           
		0,                                      
/* 
** スキャナ送信中／蓄積中にリストプリントすると
** スキャナバッファからページメモリに転送しているタスクがとまる、蓄積画データが乱れる
** PRN_ImagePrintTaskと同じ優先順位にする
** 1999/02/08 by T.Soneoka
*/
#if (0)
**		130
#else
		230
#endif
	},                                          
	{   /* 未使用 */                                        /* 82 */
		/* リストプリント中ジャムリカバータスク */
		LST_PrinterErrorDetectTask,             
		exi_tsk_irom,                           
		1,                                      
		120
	},                                          
	{                                           /* 83 */
		/* 中継配信不達通知のキャラクタイメージデータ作成タスク *//* Upper CDC_CTxCodeConvertPageTask */
		LST_RelayedTxReportImageTask,           
		exi_tsk_irom,                           
		0,                                      
		200
	},                                          
	{                                           /* 84 */
		/* オペレーション */                    
		OPR_Task,                               
		exi_tsk_irom,                           
		0,                                      
		230
	},                                          
	{                                           /* 85 */
		/* キースキャン */                      
		OPR_KeyTask,                            
		exi_tsk_irom,                           
		1,                                      
		235		/* 235 <- 220 変更Log No.1160 T.Nose 1999/02/03 */
				/* ↓OPR_SubMessageReceiveTask()と同値にすること */
	},                                          
	{                                           /* 86 */
		/* Message Receive Task From MAN_Task() */
		OPR_SubMessageReceiveTask,              
		exi_tsk_irom,                           
		1,                                      
		235
	},                                          
	{                                           /* 87 */
		/*  原稿排出タスク */                   
		PRN_DocumentOutTask,                    
		exi_tsk_irom,                           
		1,                                      
		190
	},                                          
	{                                           /* 88 */
		/*  プリントデータ送出タスク */         
		PRN_DataTxTask,                         
		PRN_DataTxExit,                         
		1,                                      
		180
	},                                          
	{                                           /* 89 */
		/* プリント時 DRAM -> CODEC DMA起動タスク */
		PRN_MemoryDataTxTask,                   
		exi_tsk_irom,                           
		0,                                      
		110
	},                                          
	{                                           /* 90 */
		/* ジャーナルプリントタスク */          
		PRN_JournalPrintTask,                   
		exi_tsk_irom,                           
		0,                                      
		200
	},                                          
	{                                           /* 91 */
		/* プリント中ジャムリカバータスク */    
		PRN_JAMRecoverTask,                     
		exi_tsk_irom,                           
		1,                                      
		110
	},                                          
	{                                           /* 92 */
		/* CLASS1 メインタスク */               
		CL1_Task,                               
		exi_tsk_irom,                           
		0,                                      
		230
	},                                          
	{                                           /* 93 */
		/* CLASS1 疑似通信タスク */             
		CL1_FaxComTask,                         
		CL1_FaxComExit,                         
		0,                                      
		190
	},                                          
	{                                           /* 94 */
		/* CLASS1 RS232C監視タイマータスク */   
		CL1_RsTimerTask,                        
		exi_tsk_irom,                           
		1,                                      
		150
	},                                          
	{                                           /* 95 */
		/* CLASS1 RS232Cステータス監視タスク */ 
		CL1_RsControlTask,                      
		exi_tsk_irom,                           
		1,                                      
		210
	},                                          
	{                                           /* 96 */
		/* CLASS1 コマンド受信タスク */         
		CL1_CommandReceiveTask,                 
		exi_tsk_irom,                           
		1,                                      
		220
	},                                          
	{                                           /* 97 */
		/* CLASS1 ＨＤＬＣ受信タスク */         
		CL1_HdlcReceiveTask,                    
		CL1_HdlcReceiveExit,                    
		0,                                      
		220
	},                                          
	{                                           /* 98 */
		/*  CLASS1 データ受信タスク */          
		CL1_DataReceiveTask,                    
		CL1_DataReceiveExit,                    
		0,                                      
		220
	},                                          
	{                                           /* 99 */
		/* CLASS1 ダミーデータ送出タスク */     
		CL1_DummyDataTxTask,                    
		exi_tsk_irom,                           
		0,                                      
		220
	},                                          
	{                                           /* 100 */
		/* CLASS1 ＣＥＤ送出タスク */           
		CL1_CEDTxTask,                          
		CL1_CEDTxExit,                          
		0,                                      
		220
	},                                          
	{                                           /* 101 */
		/* CLASS1 オートダイアルタスク */       
		CL1_AutoDialTask,                       
		exi_tsk_irom,                           
		0,                                      
		220
	},                                          
	{                                           /* 102 */
		/* CLASS1 オートダイアルアボートタスク */
		CL1_DialAbortTask,                      
		exi_tsk_irom,                           
		1,                                      
		215
	},                                          
	{                                           /* 103 */
		/* CLASS 1 高速 HDLC 受信タスク *//* Upper CL1_TASK */
		CL1_FRH_ReceiveFrameTask,               
		CL1_FRH_ReceiveFrameTaskExit,           
		0,                                      
		220
	},                                          
	{                                           /* 104 */
		/* CLASS 1 高速 HDLC キャリアダウン検知タスク *//* Upper CL1_FRH_ReceiveFrameTask */
		CL1_FRH_CarDownDetectTask,              
		exi_tsk_irom,                           
		0,                                      
		210
	},                                          
	{                                           /* 105 */
		/*  ２８．８Ｋオプションボードからの命令受信タスク */
		DPR_UpLoadRxTask,                       
		exi_tsk_irom,                           
		1,                                      
		220
	},                                          
	{                                           /* 106 */
		/* ＤＰＲＡＭを通じてホストからのリモート関数を実行するタスク */
		DPR_RemoteFuncExecTask,                 
		exi_tsk_irom,                           
		0,                                      
		230
	},                                          
	{                                           /* 107 */
		/* ＤＰＲＡＭを通じてホストからのリモートデータ関数を実行するタスク */
		DPR_RemoteDataExecTask,                 
		exi_tsk_irom,                           
		0,                                      
		230
	},                                          
	{                                           /* 108 */
		/*ＤＰＲＡＭを通じてスレーブが動いていないときに、代わりに疑似命令を出すタスク */
		DPR_InsteadOfSlaveTask,                 
		exi_tsk_irom,                           
		0,                                      
		230
	},                                          
	{                                           /* 109 */
		/* 一定時間後、引数のrcv_msg()を行うタスク（snd_msgロックアップ救済用） */
		DPR_FuncReceiveMessageTask,             
		exi_tsk_irom,                           
		1,                                      
		230
	},                                          
	{                                           /* 110 */
		/* 一定時間後、引数のrcv_msg()を行うタスク（snd_msgロックアップ救済用） */
		DPR_DataReceiveMessageTask,             
		exi_tsk_irom,                           
		1,                                      
		230
	},                                          
	{                                           /* 111 */
		/*  一定時間後、snd_msg()を行うタスク（rcv_msgロックアップ救済用） */
		DPR_FuncSendMessageTask,                
		exi_tsk_irom,                           
		1,                                      
		230
	},                                          
	{                                           /* 112 */
		/* 一定時間後、snd_msg()を行うタスク（rcv_msgロックアップ救済用） */
		DPR_DataSendMessageTask,                
		exi_tsk_irom,                           
		1,                                      
		230
	},                                          
	{                                           /* 113 */
		/* グレープを使用してスキャナ送信を行うとき、一定時間毎にＥＣＭバッファの状態をコピーする */
		DPR_CopyECM_BufferTask,                 
		exi_tsk_irom,                           
		1,                                      
		230
	},                                          
	{                                           /* 114 */
		/*  定着器温度制御タスク */             
		PRN_FuserTempTask,                      
		exi_tsk_irom,                           
		1,                                      
		190
	},                                          
	{                                           /* 115 */
		/*  ペーパーセンサータスク */           
		PRN_PaperSensorTask,                    
		exi_tsk_irom,                           
		1,                                      
		140
	},                                          
	{                                           /* 116 */
		/*  トナー残量検出タスク */             
		PRN_CheckTonerTask,                     
		exi_tsk_irom,                           
		1,                                      
		120
	},                                          
	{                                           /* 117 */
		/*  高電圧制御タスク */                 
		PRN_HighVoltageTask,                    
		PRN_HighVoltageExit,                    
		0,                                      
		120
	},                                          
	{                                           /* 118 */
		/* ペーパーフィードタスク */            
		PRN_PaperFeedTask,                      
		exi_tsk_irom,                           
		1,                                      
		120
	},                                          
	{                                           /* 119 */
		/* 手差し用紙繰込みタスク 1997/11/19 by H.Kubo */
		PRN_ManualDocumentInTask,               
		exi_tsk_irom,                           
		1,                                      
		190
	},                                          
	{                                           /* 120 */
		/*  ウォームアップ制御タスク */         
		PRN_PrinterWarmUpTask,                  
		exi_tsk_irom,                           
		1,                                      
		200
	},                                          
	{                                           /* 121 */
		/*  ウォームアップ制御タスク */         
		PRN_WarmUpControlTask,                  
		PRN_WarmUpControlExit,                  
		1,                                      
		190
	},                                          
	{                                           /* 122 */
		/*  ウォームアップ中の原稿排出タスク */ 
		PRN_WarmUpDcoumentOutTask,              
		exi_tsk_irom,                           
		1,                                      
		190
	},                                          
	{   /* 未使用 */                                        /* 123 */
		/*  リストプリント原稿排出タスク */     
		PRN_ListDocumentOutTask,                
		PRN_ListDocumentOutExit,                
		0,                                      
		120
	},                                          
	{                                           /* 124 */
		/*  転写電流の測定タスク */             
		PRN_GetResistTask,                      
		exi_tsk_irom,                           
		1,                                      
		110
	},                                          
	{                                           /* 125 */
		/*  回転受信メインタスク */             
		ROT_Task,                               
		exi_tsk_irom,                           
		1,                                      
		230
	},                                          
	{                                           /* 126 */
		/* 暗号化用タスク */                    
		SCD_CipherTask,                         
		exi_tsk_irom,                           
		0,                                      
		200
	},                                          
	{                                           /* 127 */
		/* モデム不具合救済タスク *//* Upper MDM_ABCODE_Task */
		MDM_ModemRecoverTask,                   
		exi_tsk_irom,                           
		1,                                      
		200
	},                                          
	{                                           /* 128 */
		/* ナンバーディスプレイ情報受信タスク*/ 
		NCU_ND_RxProcedureTask,                 
		NCU_ND_RxProcedureTaskExit,             
		0,	/* 1 > 0 by H.Hirao 1998/11/16 */                                      
		120
	},                                          
	{                                           /* 129 */
		/* ナンバーディスプレイ用Ｖ２３受信タスク*/
		MDM_ND_RxV23Task,                       
		exi_tsk_irom,                           
		0,	/* 1 > 0 by H.Hirao 1998/11/16 */                                      
		110
	},                                          
	{                                           /* 130 */
		/* ナンバーディスプレイ用極反検出タスク*/
		NCU_ND_DetectDSETask,                   
		exi_tsk_irom,                           
		1,                                      
		110
	},                                          
	{                                           /* 131 */
		/* 表示点滅用タスク */                  
		OPR_DisplayFlashTask,                   
		exi_tsk_irom,                           
		1,                                      

#if (0)
** 		/* マルチ動作時の点滅が非常にばらつく。
** 		** 最悪の場合、点滅しなかったり、点滅位置がずれたりする。
** 		** よって、読み取り処理よりもあげておく。
** 		** by O.Kimoto 1999/02/26
** 		*/
** 		220
#else
		210
#endif

	},                                          
	{                                           /* 132 */
		/* 原稿繰り込みタスク */                
		DocInTask,                              
		ExitDocInTask,                          
		1,                                      
		127
	},                                          
	{                                           /* 133 */
		/*  原稿排出監視タスク */               
		MAN_DocumentOutTask,                    
		MAN_DocumentOutTaskExit,                
		1,                                      
		200
	},                                          
	{                                           /* 134 */
		/* 原稿蓄積タスク */                    
		DocStoreTask,                           
		ExitDocStoreTask,                       
		0,                                      
		230	/* 200->230 優先順位見直し 1999/01/06 by T.Soneoka */
	},                                          
	{                                           /* 135 */
		/* 蓄積中のフィーダーエラー等を検出 */  
		WatchDocFeedTask,                       
		ExitWatchDocFeedTask,                   
		1,                                      
		190	
	},                                          
	{                                           /* 136 */
		/* 1ページをエンコードし、画像メモリに蓄積する */
		StorePageTask,                          
		ExitStorePageTask,                      
		0,                                      
#if (0)
**		220	/* 190->220 優先順位見直し 1999/01/06 by T.Soneoka */
#else
		225	/* 220->225 優先順位見直し Ｒｘ中の蓄積をするとポストメッセージをこぼす FCM_Taskより低くします 1999/03/17 by T.Soneoka */
#endif
	},                                          
	{                                           /* 137 */
		/*  GateArray が書いた ScannerBuffer(SRAM)を読んでScanner Page Memory に張る */
		ScanPageTask,                           
		exi_tsk_irom,                           
		0,	/* 1->0 大タスクに変更  1999/01/19 by T.Soneoka */
/* 
** スキャナ送信中／蓄積中にリストプリントすると
** スキャナバッファからページメモリに転送しているタスクがとまる、蓄積画データが乱れる
** PRN_ImagePrintTaskと同じ優先順位にする
** 1999/02/08 by T.Soneoka
*/
#if (0)
**		200	/* 110->200 優先順位見直し 1999/01/06 by T.Soneoka */
#else
		150	/* 200->150 */
#endif
	},                                          
	{                                           /* 138 */
		/* シェーディングデータを取り込みタスク */
		GetShadeTask,                           
		exi_tsk_irom,                           
		1,                                      
		190
	},                                          
	{                                           /* 139 */
		/* 済みスタンプテストタスク */          
		StampTestTask,                          
		ExitStampTestTask,                      
		1,                                      
		190
	},                                          
	{                                           /* 140 */
		/* リアルタイムコピータスク */          
		CopyStoreTask,              
		ExitCopyStoreTask,                      
		1,                                      
		230	/* 190->230 優先順位見直し 1999/01/06 by T.Soneoka */
	},                                          
	{                                           /* 141 */
		/* GateArray が書いた ScannerBuffer(SRAM)を読んで、 Page Memory に張るタスク */
		PageMemStoreTask,                       
		ExitPageMemStoreTask,                   
		1,                                      
		200	/* 110->200 優先順位見直し 1999/01/06 by T.Soneoka */
	},                                          
	{                                           /* 142 */
		/* ギア・バック・ラッシュ監視タスク HINOKIはDUMMYタスクです */
		SCN_GearBackLashTask,                   
		exi_tsk_irom,                           
		1,                                      
		200
	},                                          
	{                                           /* 143 */
		/*  原稿排出テスト・タスク HINOKIはDUMMYタスクです */
		SCN_DocumentOutTestTask,                
		exi_tsk_irom,                           
		1,                                      
		200
	},
	{                                           /* 144 */
		/* プリントタスク＜－＞メインタスクとのインターフェースタスク */
#if (0)
** 		/* Rename By O.Kimoto 1998/10/27 */
** 		PRN_ImagePrintTask,                     
** 		PRN_ExitImagePrintTask,                 
#else
		PRN_CopyPrintTask,                     
		PRN_ExitCopyPrintTask,                 
#endif
		1,                                      
		200
	},                                          
	{                                           /* 145 */
		/* プリントキュー作成タスク */          
		AddIndexQueueTask,                      
		ExitAddIndexQueueTask,                  
		0,                                      
		180                                     
	},                                          
	{                                           /* 146 */
		/* イメージ作成メインタスク */          
		MakeImageTask,                          
		ExitMakeImageTask,                      
		0,                                      
		180                                     
	},                                          
	{                                           /* 147 */
		/* 符号化データ－＞イメージ作成タスク */
		MakeImageDecodeTask,                    
		exi_tsk_irom,                           
		0,                                      
		170                                     
	},                                          
	{                                           /* 148 */
		/* キャラクタ－＞イメージ作成タスク */  
		MakeImageListTask,                      
		exi_tsk_irom,                           
		0,                                      
		170                                     
	},                                          
	{                                           /* 149 */
		/* イメージ－＞イメージ作成タスク */    
		MakeImageDirectTask,                    
		exi_tsk_irom,                           
		0,                                      
		170                                     
	},                                          
	{                                           /* 150 */
		/* イメージデータをプリントするタスク */
		PrintImageTask,                         
		ExitPrintImageTask,                     
		0,                                      
		180
	},                                          
	{                                           /* 151 */
		/* 割り込みからのイベント処理タスク */  
		PrintImageEventTask,                    
		ExitPrintImageEventTask,                
		1,                                      
		170                                     
	},                                          
	{                                           /* 152 */
		/* プリンタ初期化タスク */              
		PrinterResetTask,                       
		exi_tsk_irom,                           
		1,                                      
		180                                     
	},                                          
	{                                           /* 153 */
		/* プリンタ監視タスク */                
		WatchPrinterTask,                       
		ExitWatchPrinterTask,                   
		1,                                      
		180                                     
	},                                          
	{                                           /* 154 */
		/* 1秒ごとにプリンタ関連ステータスを監視 */
		WatchPrinter1SecTask,                   
		exi_tsk_irom,                           
		1,                                      
		170                                     
	},
	{                                           /* 155 */
		/* スキャナバッファからコーデックにＤＭＡを起動するタスク */
		CDC_STxDMA_Task,                        
		exi_tsk_irom,                           
		1,                                      
		190                                     
	},
	{                                           /* 156 */
		/* プリンタバッファからＧ／ＡプリントＩ／Ｏに転送する */
		PrintDataTransTask,                     
		exi_tsk_irom,                           
		1,                                      
		110                                     
	},
	{                                           /* 157 */
		/* 原稿排出タスク（SCN内部で使用） */
		DocOutTask,                             
		ExitDocOutTask,                         
		1,                                      
		190	/* 180->190 優先順位見直し 1999/01/06 by T.Soneoka */
	},
	{                                           /* 158 */
		/* コーデックからプリンタページメモリにＤＭＡを起動するタスク */
		CDC_PRxDMA_Task,                        
		exi_tsk_irom,                           
		1,                                      
		190                                     
	},
	{                                           /* 159 */
		/* ＥＣＭバッファからプリンタバッファに1論理ページ複合するタスク */
		CDC_PRxDecodePageTask,                  
		CDC_PRxDecodePageTaskExit,				
		0, /* 大きいタスクに変更 by H.Hirao 1998/12/05 */                                      
		190                                     
	},
	{                                           /* 160 */
		/* イメージプリントタスク */
		PRN_ImagePrintTask,                     
		PRN_ImagePrintExit,                     
		0,                                      
		230 /*200 V34受信でR4.2 by H.Hirao 1998/12/02 */                             
	},
	{                                           /* 161 */
		/* スキャナ送信原稿蓄積タスク */        
		SCN_STxStoreTask,                       
		SCN_STxStoreTaskExit,                   
		1,
		210	/* 180->210 優先順位見直し 1999/01/06 by T.Soneoka */
	},
	{                                           /* 162 */
		/* RS232C CTS 監視タスク */             
		CL1_WatchCTS_Task,                      
		exi_tsk_irom,                           
		1,                                      
		210                                     
	},
	{                                           /* 163 */
		/* エンコードタスクからのイベント待ちをするタスク、リスケジューラを走らせるため 1999/03/16 by T.Soneoka */            
		SCN_DummyTask, 		                    
		exi_tsk_irom,                           
		1,                                      
		215                                     
	},
	{											/* 164 */
		/* パルスダイヤル送出タスク */ /* PRO_DIAL_PULSE_TASK パルスダイヤルの誤ダイヤル H.Yoshikawa 2000/11/24 by T.Soneoka*/
		ATD_DialPulseTask,
		exi_tsk_irom,
		1,
		70
	},
	{											/* 165 */
		/* 音声送出タスク */
		MDM_VoiceTxTask,
		exi_tsk_irom,
		1,
		200	/* 26 */
	},
	{											/* 166 */
		/* リモート受信信号検出タスク */	/* REMOTE_RX_FUNC By T.Takagi 2003/01/24 */
		NCU_RemoteRxSignalDetTask,
		exi_tsk_irom,
		1,
		160
	},
#if defined (KEISATSU) /* Added by SMuratec 李 2005/07/01 */
	{                                           /* 167 */
		/* 167.ＮＣＵタイマタスク */             
		NCU_DBCITimeUpTask,                         
		exi_tsk_irom,                           
		1,                                      
		150
	},                                          
	{                                           /* 168 */
		/* 168.ＮＣＵ周波数チェックタスク */     
		NCU_DBCIFreqCheckTask,                 
		exi_tsk_irom,                           
		1,                                      
		170
	},
	{                                           /* 169 */
		/* 169.２回線同時呼出によって着信検出タスク */                 
		NCU_Detect2ndCalledTask,                   
		NCU_Detect2ndCalledExit,			                   
		1,                                      
		180
	},
#else /* defined (KEISATSU) */
#if (PRO_MODEM == MN195006)
	{											/* 167 */
		MDM_FskModemReadTask,
		exi_tsk_irom,
		1,
		160
	},
	{											/* 168 */
		MDM_TCF_ReadTask,
		exi_tsk_irom,
		1,
		160
	},
	{											/* 169 */
		MDM_FedDetectTask,
		exi_tsk_irom,
		1,
		160
	},
#endif
#endif /* defined (KEISATSU) */                                         
#if defined (KEISATSU) /* 警察FAX 05/08/23 石橋正和 */
	{
		S1_ReceiveTCF_DataTask,
		exi_tsk_irom,
		0,
		225
	},
#endif
};
