/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Dec 05 10:42:30 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.kingstargroup.advquery.reportdepttrade;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the T_TIF_REPORT_DEPTTRADE
 * table.  This object should only be instantiated for use with instances 
 * of the TTifReportDepttrade class.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized 
 * by MyEclipse Hibernate tool integration.
 */
public class TTifReportDepttradeKey
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private volatile int hashValue = 0;

    /** The value of the BALANCE_DATE component of this composite id. */
    private java.lang.String balanceDate;

    /** The value of the DEPT_CODE component of this composite id. */
    private java.lang.String deptCode;

    /** The value of the SERI_TYPE component of this composite id. */
    private java.lang.Integer seriType;

    /** The value of the FEE_TYPE component of this composite id. */
    private java.lang.Integer feeType;

    /** The value of the OUTORIN component of this composite id. */
    private java.lang.Integer outorin;

    /**
     * Simple constructor of TTifReportDepttradeKey instances.
     */
    public TTifReportDepttradeKey()
    {
    }

    /**
     * Returns the value of the balanceDate property.
     * @return java.lang.String
     */
    public java.lang.String getBalanceDate()
    {
        return balanceDate;
    }

    /**
     * Sets the value of the balanceDate property.
     * @param balanceDate
     */
    public void setBalanceDate(java.lang.String balanceDate)
    {
        hashValue = 0;
        this.balanceDate = balanceDate;
    }

    /**
     * Returns the value of the deptCode property.
     * @return java.lang.String
     */
    public java.lang.String getDeptCode()
    {
        return deptCode;
    }

    /**
     * Sets the value of the deptCode property.
     * @param deptCode
     */
    public void setDeptCode(java.lang.String deptCode)
    {
        hashValue = 0;
        this.deptCode = deptCode;
    }

    /**
     * Returns the value of the seriType property.
     * @return java.lang.Integer
     */
    public java.lang.Integer getSeriType()
    {
        return seriType;
    }

    /**
     * Sets the value of the seriType property.
     * @param seriType
     */
    public void setSeriType(java.lang.Integer seriType)
    {
        hashValue = 0;
        this.seriType = seriType;
    }

    /**
     * Returns the value of the feeType property.
     * @return java.lang.Integer
     */
    public java.lang.Integer getFeeType()
    {
        return feeType;
    }

    /**
     * Sets the value of the feeType property.
     * @param feeType
     */
    public void setFeeType(java.lang.Integer feeType)
    {
        hashValue = 0;
        this.feeType = feeType;
    }

    /**
     * Returns the value of the outorin property.
     * @return java.lang.Integer
     */
    public java.lang.Integer getOutorin()
    {
        return outorin;
    }

    /**
     * Sets the value of the outorin property.
     * @param outorin
     */
    public void setOutorin(java.lang.Integer outorin)
    {
        hashValue = 0;
        this.outorin = outorin;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the id components.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof TTifReportDepttradeKey))
            return false;
        TTifReportDepttradeKey that = (TTifReportDepttradeKey) rhs;
        if (this.getBalanceDate() == null || that.getBalanceDate() == null)
        {
            return false;
        }
        if (! this.getBalanceDate().equals(that.getBalanceDate()))
        {
            return false;
        }
        if (this.getDeptCode() == null || that.getDeptCode() == null)
        {
            return false;
        }
        if (! this.getDeptCode().equals(that.getDeptCode()))
        {
            return false;
        }
        if (this.getSeriType() == null || that.getSeriType() == null)
        {
            return false;
        }
        if (! this.getSeriType().equals(that.getSeriType()))
        {
            return false;
        }
        if (this.getFeeType() == null || that.getFeeType() == null)
        {
            return false;
        }
        if (! this.getFeeType().equals(that.getFeeType()))
        {
            return false;
        }
        if (this.getOutorin() == null || that.getOutorin() == null)
        {
            return false;
        }
        if (! this.getOutorin().equals(that.getOutorin()))
        {
            return false;
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int balanceDateValue = this.getBalanceDate() == null ? 0 : this.getBalanceDate().hashCode();
            result = result * 37 + balanceDateValue;
            int deptCodeValue = this.getDeptCode() == null ? 0 : this.getDeptCode().hashCode();
            result = result * 37 + deptCodeValue;
            int seriTypeValue = this.getSeriType() == null ? 0 : this.getSeriType().hashCode();
            result = result * 37 + seriTypeValue;
            int feeTypeValue = this.getFeeType() == null ? 0 : this.getFeeType().hashCode();
            result = result * 37 + feeTypeValue;
            int outorinValue = this.getOutorin() == null ? 0 : this.getOutorin().hashCode();
            result = result * 37 + outorinValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
