DROP TABLE YKT_CUR.T_TIF_REPORT_SHOP_BALANCE_01 CASCADE CONSTRAINTS;

CREATE TABLE YKT_CUR.T_TIF_REPORT_SHOP_BALANCE_01
(
  BALANCE_DATE  VARCHAR2(10 BYTE)               NOT NULL,
  SHOP_ID       NUMBER                          NOT NULL,
  SHOP_NAME     VARCHAR2(50 BYTE),
  DEPT_ID       NUMBER,
  OPERATE_DATE  VARCHAR2(10 BYTE),
  TRADE_NUM     NUMBER,
  TRADE_AMT     NUMBER(15,6),
  MNG_AMT       NUMBER(15,6),
  TOTAL_AMT     NUMBER(15,6),
  DATA_SIGN     VARCHAR2(8 BYTE),
  RESERVE1      VARCHAR2(20 BYTE),
  RESERVE2      VARCHAR2(20 BYTE),
  OUTORIN       NUMBER,
  SERI_TYPE     NUMBER
)
TABLESPACE TS_YKT_CUR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX YKT_CUR.idx_rep_shp01 ON YKT_CUR.T_TIF_REPORT_SHOP_BALANCE_01
(BALANCE_DATE, SHOP_ID, OPERATE_DATE, OUTORIN, SERI_TYPE)
LOGGING
TABLESPACE TS_YKT_CUR
NOPARALLEL;
