#ifndef _KSG_ADVANSTA_H_
#define _KSG_ADVANSTA_H_

#define MOC_ERROR_SUCCESS 0x00 //操作成功
#define MOC_ERROR_SAM_EMPTY 0x60 //没有安装SAM卡
#define MOC_ERROR_SAM_INIT 0x61 //SAM卡初始化错误或未初始化
#define MOC_ERROR_SAM_PIN 0x62 //SAM校验PIN错误
#define MOC_ERROR_SAM_TYPE 0x63 //SAM卡类型与交易类型不匹配
#define MOC_ERROR_SAM_SELECT 0x64 //SAM卡选择文件错误
#define MOC_ERROR_SAM_READ 0x65 //SAM读错误
#define MOC_ERROR_SAM_WRITE 0x66 //SAM卡写错误
#define MOC_ERROR_SAM_AUTH 0x67 //SAM卡认证错误
#define MOC_ERROR_SAM_CHALLENGE 0x68 //SAM卡取随机数错误
#define MOC_ERROR_SAM_DES 0x69 //SAM卡DES计算错误
#define MOC_ERROR_SAM_CREATE_KEY 0x6A //SAM卡生成钱包密钥错误
#define MOC_ERROR_PKI_RSA 0x71 //PKI卡RSA计算错误
#define MOC_ERROR_PKI_DES 0x72 //PKI卡DES计算错误
#define MOC_ERROR_SAM_APDU 0x7E //SAM卡执行APDU命令错误
#define MOC_ERROR_SAM_TIMEOUT 0x7F //SAM卡操作超时
#define MOC_ERROR_CARD_NOTAG 0x80 //没有卡
#define MOC_ERROR_CARD_SELECT 0x81 //选择卡片错误
#define MOC_ERROR_CARD_HALT 0x82 //停用卡片错误
#define MOC_ERROR_CARD_AUTH 0x83 //认证卡片错误
#define MOC_ERROR_CARD_READ 0x84 //卡片读错误
#define MOC_ERROR_CARD_WRITE 0x85 //卡片写错误
#define MOC_ERROR_CARD_PENDING 0x86 //卡片写操作中途中断
#define MOC_ERROR_CARD_UNKOWN 0x90 //不是本系统卡片
#define MOC_ERROR_CARD_OUTOFDATE 0x91 //卡片超出有效期
#define MOC_ERROR_CARD_CITY 0x92 //城市代码或应用代码错误
#define MOC_ERROR_CARD_INVALID 0x93 //非法卡
#define MOC_ERROR_CARD_NAMELIST 0x94 //黑名单卡
#define MOC_ERROR_CARD_OWEPAY 0x95 //钱包余额不足
#define MOC_ERROR_CARD_OVERLIMIT 0x96 //钱包余额超出上限
#define MOC_ERROR_CARD_PURSE_UNUSED 0x97 //钱包未启用
#define MOC_ERROR_CARD_PURSE_STOPPED 0x98 //钱包已停用
#define MOC_ERROR_CARD_PURSE_FAIL 0x99 //钱包正本被破坏
#define MOC_ERROR_CARD_PURSE_INUSE 0x9A //钱包已启用
#define MOC_ERROR_CARD_MUTEX_FAIL 0x9F //公共信息区被破坏
#define MOC_ERROR_CARD_TIMEOUT 0xAF //卡片操作超时
#define MOC_ERROR_TS_PENDING 0xB0 //交易操作中途中断
#define MOC_ERROR_TS_FAIL 0xB1 //交易失败
#define MOC_ERROR_TS_SETP 0xB2 //前一步指令未执行或执行失败
#define MOC_ERROR_ONTS_REFUSED 0xC1 //联机充值请求被拒绝
#define MOC_ERROR_ONTS_AUTH 0xC2 //联机充值认证失败
#define MOC_ERROR_ONTS_COMMIT 0xC3 //交易结果提交错误
#define MOC_ERROR_ONTS_PROTOCOL 0xCE //联机充值协议错误
#define MOC_ERROR_TS_TIMEOUT 0xCF //交易操作超时
#define MOC_ERROR_MIFARE_INIT 0xE0 //MIFARE硬件初始化错误
#define MOC_ERROR_ICC_INIT 0xE1 //SAM硬件初始化错误
#define MOC_ERROR_INVALID_COMMAND 0xE2 //命令错误
#define MOC_ERROR_INVALID_PARAM 0xE3 //参数错误
#define MOC_ERROR_CHECHSUM 0xE4 //校验和错误
#define MOC_ERROR_COMM_TIMEOUT 0xE5 //线路通讯超时
#define MOC_ERROR_FLASH_WRITE 0xE6 //内部Flash写错误
#define ERROR_OPEN_PORT 0x3E9 //串口打开错误
#define ERROR_TIME_OUT 0x41B //通讯超时
#define ERROR_CLOSE_HND 0x3EA //关闭句柄出错
#define ERROR_IPADDR 0x3EB //IP地址错误
#define ERROR_DEVICEID 0x3EC //传入的商户ID错误
#define ERROR_FOLDER 0x3ED //目录错误
#define ERROR_FULL_FILE 0x3EE //交易文件已满，继续写这会造成交易记录漏传
#define ERROR_INCREASE_WAIT 0x3EF //等待充值信号出错，一般由网络引起
#define ERROR_CONNECT_SOCKET 0x44D //网络连接失败
#define ERROR_CHECK_SUM 0x44E //通讯校验错误
#define ERROR_NO_CONFIG_PARAM 0x3F4 //未配置参数
#define ERROR_NO_OPENCOM 0x3F5 //串口未打开
#define ERROR_RE_OPENCOM 0x3F6 //重复打开串口
#define ERROR_SOCKET -1 //网络连接错误
#define ERROR_EP_SOCKET 0x4B0 //连接易票联服务器失败
#define ERROR_EP_YCT_LOGIN 0x4B1 //登录易票联服务器失败
#define ERROR_EP_YCT_READY 0x4B2 //E票联帐户羊城通扣费错误
#define ERRPR_EP_YCT_OK 0x4B3 //E票联帐户羊城通扣费确认错误
#define ERROR_EP_YCT_BACK 0x4B4 //E票联帐户羊城通冲正错误
#define ERROR_EP_YCT_GETOUT 0x4B5 //违反业务规则，如充值金额不符合规范
#define ERROR_GET_INC_KEY 0x9106 //获取充值密钥错误

#endif // _KSG_ADVANSTA_H_
