insert into t_pif_phydevice values(1005,'昊星考勤','haoxing','昊星','考勤机');
insert into t_pif_syskey values('T_ATTSERIAL','考勤流水号',1,99999999,'0');

--创建表空间
create tablespace TS_YKT_CK
datafile  '/oradata/yktdb/ts_ykt_ck.dbf'
size 100M
reuse
  autoextend on
    next 10M
    maxsize UNLIMITED
logging
extent management  local  autoallocate
segment space management auto
flashback on;


--创建用户
create user YKT_CK
  identified by "kingstar"
  default tablespace TS_YKT_CK
  temporary tablespace TEMP
  profile DEFAULT
  quota unlimited on ts_ykt_ck;
 
GRANT CONNECT TO YKT_CK;


--创建表
CREATE TABLE "YKT_CK"."T_ATTSERIAL" 
   (	"SERIAL_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"DEVICE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CUST_ID" NUMBER(*,0), 
	"CARD_ID" NUMBER(*,0), 
	"PHY_ID" VARCHAR2(20), 
	"SHOW_CARDNO" VARCHAR2(20), 
	"ATT_DATE" VARCHAR2(8), 
	"ATT_TIME" VARCHAR2(6), 
	"TX_MARK" NUMBER(*,0), 
	"STATUS" CHAR(1), 
	 CONSTRAINT "P_KEY_1" PRIMARY KEY ("SERIAL_ID", "DEVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TS_YKT_CK"  ENABLE
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TS_YKT_CK" ;
 
  CREATE INDEX "YKT_CK"."IDX_1" ON "YKT_CK"."T_ATTSERIAL" ("CUST_ID", "ATT_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TS_YKT_CK" ;
 
  CREATE UNIQUE INDEX "YKT_CK"."P_KEY_1" ON "YKT_CK"."T_ATTSERIAL" ("SERIAL_ID", "DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TS_YKT_CK" ;
 
  ALTER TABLE "YKT_CK"."T_ATTSERIAL" ADD CONSTRAINT "P_KEY_1" PRIMARY KEY ("SERIAL_ID", "DEVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TS_YKT_CK"  ENABLE;
 
  ALTER TABLE "YKT_CK"."T_ATTSERIAL" MODIFY ("SERIAL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "YKT_CK"."T_ATTSERIAL" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
 
   COMMENT ON COLUMN "YKT_CK"."T_ATTSERIAL"."SERIAL_ID" IS '流水号';
 
   COMMENT ON COLUMN "YKT_CK"."T_ATTSERIAL"."DEVICE_ID" IS '设备编号';
 
   COMMENT ON COLUMN "YKT_CK"."T_ATTSERIAL"."CUST_ID" IS '客户号';
 
   COMMENT ON COLUMN "YKT_CK"."T_ATTSERIAL"."CARD_ID" IS '卡号';
 
   COMMENT ON COLUMN "YKT_CK"."T_ATTSERIAL"."PHY_ID" IS '物理卡号';
 
   COMMENT ON COLUMN "YKT_CK"."T_ATTSERIAL"."SHOW_CARDNO" IS '显示卡号';
 
   COMMENT ON COLUMN "YKT_CK"."T_ATTSERIAL"."ATT_DATE" IS '打卡日期';
 
   COMMENT ON COLUMN "YKT_CK"."T_ATTSERIAL"."ATT_TIME" IS '打卡时间';
 
   COMMENT ON COLUMN "YKT_CK"."T_ATTSERIAL"."TX_MARK" IS '交易标记';
 
   COMMENT ON COLUMN "YKT_CK"."T_ATTSERIAL"."STATUS" IS '状态';
 
   COMMENT ON TABLE "YKT_CK"."T_ATTSERIAL"  IS '考勤流水表';