/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Oct 19 14:05:58 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.kingstargroup.advquery.tradeserialhis;

import java.io.Serializable;

/**
 * A class that represents a row in the T_TIF_TRADESERIAL_HIS table. 
 * You can customize the behavior of this class by editing the class, {@link TTifTradeserialHis()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractTTifTradeserialHis 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The simple primary key value. */
    private TTifTradeserialHisKey id;

    /** The value of the simple otherSeriNo property. */
    private java.lang.Integer otherSeriNo;

    /** The value of the simple serialType property. */
    private java.lang.Integer serialType;

    /** The value of the simple serialState property. */
    private java.lang.Integer serialState;

    /** The value of the simple operateDate property. */
    private java.lang.String operateDate;

    /** The value of the simple operateTime property. */
    private java.lang.String operateTime;

    /** The value of the simple collectDate property. */
    private java.lang.String collectDate;

    /** The value of the simple collectTime property. */
    private java.lang.String collectTime;

    /** The value of the simple enteractDate property. */
    private java.lang.String enteractDate;

    /** The value of the simple enteractTime property. */
    private java.lang.String enteractTime;

    /** The value of the simple maindeviceId property. */
    private java.lang.Integer maindeviceId;

    /** The value of the simple deviceId property. */
    private java.lang.Integer deviceId;

    /** The value of the simple devphy999Id property. */
    private java.lang.String devphy999Id;

    /** The value of the simple showid property. */
    private java.lang.String showid;

    /** The value of the simple cardId property. */
    private java.lang.Integer cardId;

    /** The value of the simple purseId property. */
    private java.lang.Integer purseId;

    /** The value of the simple tradeCount property. */
    private java.lang.Integer tradeCount;

    /** The value of the simple tradeFee property. */
    private java.lang.Double tradeFee;

    /** The value of the simple inBalance property. */
    private java.lang.Double inBalance;

    /** The value of the simple outBalance property. */
    private java.lang.Double outBalance;

    /** The value of the simple depositFee property. */
    private java.lang.Double depositFee;

    /** The value of the simple inFee property. */
    private java.lang.Double inFee;

    /** The value of the simple costFee property. */
    private java.lang.Double costFee;

    /** The value of the simple boardfee property. */
    private java.lang.Double boardfee;

    /** The value of the simple oldpwd property. */
    private java.lang.String oldpwd;

    /** The value of the simple newpwd property. */
    private java.lang.String newpwd;

    /** The value of the simple customerId property. */
    private java.lang.Integer customerId;

    /** The value of the simple operCode property. */
    private java.lang.String operCode;

    /** The value of the simple outAccountId property. */
    private java.lang.String outAccountId;

    /** The value of the simple inAccountId property. */
    private java.lang.String inAccountId;

    /** The value of the simple bActId property. */
    private java.lang.String bactId;

    /** The value of the simple sysId property. */
    private java.lang.Integer sysId;

    /** The value of the simple conditionId property. */
    private java.lang.Integer conditionId;

    /** The value of the simple isOnline property. */
    private java.lang.String isOnline;

    /** The value of the simple tmark property. */
    private java.lang.Integer tmark;

    /** The value of the simple devAuth property. */
    private java.lang.String devAuth;

    /** The value of the simple comuVer property. */
    private java.lang.Integer comuVer;

    /** The value of the simple runReason property. */
    private java.lang.Integer runReason;

    /** The value of the simple crc property. */
    private java.lang.String crc;

    /** The value of the simple ecode property. */
    private java.lang.Integer ecode;

    /** The value of the simple reviseserialNo property. */
    private java.lang.Integer reviseserialNo;

    /** The value of the simple reserve1 property. */
    private java.lang.String reserve1;

    /** The value of the simple reserve2 property. */
    private java.lang.String reserve2;

    /** The value of the simple reserve3 property. */
    private java.lang.String reserve3;

    /**
     * Simple constructor of AbstractTTifTradeserialHis instances.
     */
    public AbstractTTifTradeserialHis()
    {
    }

    /**
     * Constructor of AbstractTTifTradeserialHis instances given a composite primary key.
     * @param id
     */
    public AbstractTTifTradeserialHis(TTifTradeserialHisKey id)
    {
        this.setId(id);
    }

    /**
     * Return the composite id instance that identifies this object.
     * @return TTifTradeserialHisKey
     */
    public TTifTradeserialHisKey getId()
    {
        return this.id;
    }

    /**
     * Set the composite id instance that identifies this object.
     * @param id
     */
    public void setId(TTifTradeserialHisKey id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the OTHER_SERI_NO column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getOtherSeriNo()
    {
        return this.otherSeriNo;
    }

    /**
     * Set the value of the OTHER_SERI_NO column.
     * @param otherSeriNo
     */
    public void setOtherSeriNo(java.lang.Integer otherSeriNo)
    {
        this.otherSeriNo = otherSeriNo;
    }

    /**
     * Return the value of the SERIAL_TYPE column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getSerialType()
    {
        return this.serialType;
    }

    /**
     * Set the value of the SERIAL_TYPE column.
     * @param serialType
     */
    public void setSerialType(java.lang.Integer serialType)
    {
        this.serialType = serialType;
    }

    /**
     * Return the value of the SERIAL_STATE column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getSerialState()
    {
        return this.serialState;
    }

    /**
     * Set the value of the SERIAL_STATE column.
     * @param serialState
     */
    public void setSerialState(java.lang.Integer serialState)
    {
        this.serialState = serialState;
    }

    /**
     * Return the value of the OPERATE_DATE column.
     * @return java.lang.String
     */
    public java.lang.String getOperateDate()
    {
        return this.operateDate;
    }

    /**
     * Set the value of the OPERATE_DATE column.
     * @param operateDate
     */
    public void setOperateDate(java.lang.String operateDate)
    {
        this.operateDate = operateDate;
    }

    /**
     * Return the value of the OPERATE_TIME column.
     * @return java.lang.String
     */
    public java.lang.String getOperateTime()
    {
        return this.operateTime;
    }

    /**
     * Set the value of the OPERATE_TIME column.
     * @param operateTime
     */
    public void setOperateTime(java.lang.String operateTime)
    {
        this.operateTime = operateTime;
    }

    /**
     * Return the value of the COLLECT_DATE column.
     * @return java.lang.String
     */
    public java.lang.String getCollectDate()
    {
        return this.collectDate;
    }

    /**
     * Set the value of the COLLECT_DATE column.
     * @param collectDate
     */
    public void setCollectDate(java.lang.String collectDate)
    {
        this.collectDate = collectDate;
    }

    /**
     * Return the value of the COLLECT_TIME column.
     * @return java.lang.String
     */
    public java.lang.String getCollectTime()
    {
        return this.collectTime;
    }

    /**
     * Set the value of the COLLECT_TIME column.
     * @param collectTime
     */
    public void setCollectTime(java.lang.String collectTime)
    {
        this.collectTime = collectTime;
    }

    /**
     * Return the value of the ENTERACT_DATE column.
     * @return java.lang.String
     */
    public java.lang.String getEnteractDate()
    {
        return this.enteractDate;
    }

    /**
     * Set the value of the ENTERACT_DATE column.
     * @param enteractDate
     */
    public void setEnteractDate(java.lang.String enteractDate)
    {
        this.enteractDate = enteractDate;
    }

    /**
     * Return the value of the ENTERACT_TIME column.
     * @return java.lang.String
     */
    public java.lang.String getEnteractTime()
    {
        return this.enteractTime;
    }

    /**
     * Set the value of the ENTERACT_TIME column.
     * @param enteractTime
     */
    public void setEnteractTime(java.lang.String enteractTime)
    {
        this.enteractTime = enteractTime;
    }

    /**
     * Return the value of the MAINDEVICE_ID column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getMaindeviceId()
    {
        return this.maindeviceId;
    }

    /**
     * Set the value of the MAINDEVICE_ID column.
     * @param maindeviceId
     */
    public void setMaindeviceId(java.lang.Integer maindeviceId)
    {
        this.maindeviceId = maindeviceId;
    }

    /**
     * Return the value of the DEVICE_ID column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getDeviceId()
    {
        return this.deviceId;
    }

    /**
     * Set the value of the DEVICE_ID column.
     * @param deviceId
     */
    public void setDeviceId(java.lang.Integer deviceId)
    {
        this.deviceId = deviceId;
    }

    /**
     * Return the value of the DEVPHY999_ID column.
     * @return java.lang.String
     */
    public java.lang.String getDevphy999Id()
    {
        return this.devphy999Id;
    }

    /**
     * Set the value of the DEVPHY999_ID column.
     * @param devphy999Id
     */
    public void setDevphy999Id(java.lang.String devphy999Id)
    {
        this.devphy999Id = devphy999Id;
    }

    /**
     * Return the value of the SHOWID column.
     * @return java.lang.String
     */
    public java.lang.String getShowid()
    {
        return this.showid;
    }

    /**
     * Set the value of the SHOWID column.
     * @param showid
     */
    public void setShowid(java.lang.String showid)
    {
        this.showid = showid;
    }

    /**
     * Return the value of the CARD_ID column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getCardId()
    {
        return this.cardId;
    }

    /**
     * Set the value of the CARD_ID column.
     * @param cardId
     */
    public void setCardId(java.lang.Integer cardId)
    {
        this.cardId = cardId;
    }

    /**
     * Return the value of the PURSE_ID column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getPurseId()
    {
        return this.purseId;
    }

    /**
     * Set the value of the PURSE_ID column.
     * @param purseId
     */
    public void setPurseId(java.lang.Integer purseId)
    {
        this.purseId = purseId;
    }

    /**
     * Return the value of the TRADE_COUNT column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getTradeCount()
    {
        return this.tradeCount;
    }

    /**
     * Set the value of the TRADE_COUNT column.
     * @param tradeCount
     */
    public void setTradeCount(java.lang.Integer tradeCount)
    {
        this.tradeCount = tradeCount;
    }

    /**
     * Return the value of the TRADE_FEE column.
     * @return java.lang.Double
     */
    public java.lang.Double getTradeFee()
    {
        return this.tradeFee;
    }

    /**
     * Set the value of the TRADE_FEE column.
     * @param tradeFee
     */
    public void setTradeFee(java.lang.Double tradeFee)
    {
        this.tradeFee = tradeFee;
    }

    /**
     * Return the value of the IN_BALANCE column.
     * @return java.lang.Double
     */
    public java.lang.Double getInBalance()
    {
        return this.inBalance;
    }

    /**
     * Set the value of the IN_BALANCE column.
     * @param inBalance
     */
    public void setInBalance(java.lang.Double inBalance)
    {
        this.inBalance = inBalance;
    }

    /**
     * Return the value of the OUT_BALANCE column.
     * @return java.lang.Double
     */
    public java.lang.Double getOutBalance()
    {
        return this.outBalance;
    }

    /**
     * Set the value of the OUT_BALANCE column.
     * @param outBalance
     */
    public void setOutBalance(java.lang.Double outBalance)
    {
        this.outBalance = outBalance;
    }

    /**
     * Return the value of the DEPOSIT_FEE column.
     * @return java.lang.Double
     */
    public java.lang.Double getDepositFee()
    {
        return this.depositFee;
    }

    /**
     * Set the value of the DEPOSIT_FEE column.
     * @param depositFee
     */
    public void setDepositFee(java.lang.Double depositFee)
    {
        this.depositFee = depositFee;
    }

    /**
     * Return the value of the IN_FEE column.
     * @return java.lang.Double
     */
    public java.lang.Double getInFee()
    {
        return this.inFee;
    }

    /**
     * Set the value of the IN_FEE column.
     * @param inFee
     */
    public void setInFee(java.lang.Double inFee)
    {
        this.inFee = inFee;
    }

    /**
     * Return the value of the COST_FEE column.
     * @return java.lang.Double
     */
    public java.lang.Double getCostFee()
    {
        return this.costFee;
    }

    /**
     * Set the value of the COST_FEE column.
     * @param costFee
     */
    public void setCostFee(java.lang.Double costFee)
    {
        this.costFee = costFee;
    }

    /**
     * Return the value of the BOARDFEE column.
     * @return java.lang.Double
     */
    public java.lang.Double getBoardfee()
    {
        return this.boardfee;
    }

    /**
     * Set the value of the BOARDFEE column.
     * @param boardfee
     */
    public void setBoardfee(java.lang.Double boardfee)
    {
        this.boardfee = boardfee;
    }

    /**
     * Return the value of the OLDPWD column.
     * @return java.lang.String
     */
    public java.lang.String getOldpwd()
    {
        return this.oldpwd;
    }

    /**
     * Set the value of the OLDPWD column.
     * @param oldpwd
     */
    public void setOldpwd(java.lang.String oldpwd)
    {
        this.oldpwd = oldpwd;
    }

    /**
     * Return the value of the NEWPWD column.
     * @return java.lang.String
     */
    public java.lang.String getNewpwd()
    {
        return this.newpwd;
    }

    /**
     * Set the value of the NEWPWD column.
     * @param newpwd
     */
    public void setNewpwd(java.lang.String newpwd)
    {
        this.newpwd = newpwd;
    }

    /**
     * Return the value of the CUSTOMER_ID column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getCustomerId()
    {
        return this.customerId;
    }

    /**
     * Set the value of the CUSTOMER_ID column.
     * @param customerId
     */
    public void setCustomerId(java.lang.Integer customerId)
    {
        this.customerId = customerId;
    }

    /**
     * Return the value of the OPER_CODE column.
     * @return java.lang.String
     */
    public java.lang.String getOperCode()
    {
        return this.operCode;
    }

    /**
     * Set the value of the OPER_CODE column.
     * @param operCode
     */
    public void setOperCode(java.lang.String operCode)
    {
        this.operCode = operCode;
    }

    /**
     * Return the value of the OUT_ACCOUNT_ID column.
     * @return java.lang.String
     */
    public java.lang.String getOutAccountId()
    {
        return this.outAccountId;
    }

    /**
     * Set the value of the OUT_ACCOUNT_ID column.
     * @param outAccountId
     */
    public void setOutAccountId(java.lang.String outAccountId)
    {
        this.outAccountId = outAccountId;
    }

    /**
     * Return the value of the IN_ACCOUNT_ID column.
     * @return java.lang.String
     */
    public java.lang.String getInAccountId()
    {
        return this.inAccountId;
    }

    /**
     * Set the value of the IN_ACCOUNT_ID column.
     * @param inAccountId
     */
    public void setInAccountId(java.lang.String inAccountId)
    {
        this.inAccountId = inAccountId;
    }

    /**
     * Return the value of the B_ACT_ID column.
     * @return java.lang.String
     */
    public java.lang.String getBactId()
    {
        return this.bactId;
    }

    /**
     * Set the value of the B_ACT_ID column.
     * @param bActId
     */
    public void setBactId(java.lang.String bActId)
    {
        this.bactId = bActId;
    }

    /**
     * Return the value of the SYS_ID column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getSysId()
    {
        return this.sysId;
    }

    /**
     * Set the value of the SYS_ID column.
     * @param sysId
     */
    public void setSysId(java.lang.Integer sysId)
    {
        this.sysId = sysId;
    }

    /**
     * Return the value of the CONDITION_ID column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getConditionId()
    {
        return this.conditionId;
    }

    /**
     * Set the value of the CONDITION_ID column.
     * @param conditionId
     */
    public void setConditionId(java.lang.Integer conditionId)
    {
        this.conditionId = conditionId;
    }

    /**
     * Return the value of the IS_ONLINE column.
     * @return java.lang.String
     */
    public java.lang.String getIsOnline()
    {
        return this.isOnline;
    }

    /**
     * Set the value of the IS_ONLINE column.
     * @param isOnline
     */
    public void setIsOnline(java.lang.String isOnline)
    {
        this.isOnline = isOnline;
    }

    /**
     * Return the value of the TMARK column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getTmark()
    {
        return this.tmark;
    }

    /**
     * Set the value of the TMARK column.
     * @param tmark
     */
    public void setTmark(java.lang.Integer tmark)
    {
        this.tmark = tmark;
    }

    /**
     * Return the value of the DEV_AUTH column.
     * @return java.lang.String
     */
    public java.lang.String getDevAuth()
    {
        return this.devAuth;
    }

    /**
     * Set the value of the DEV_AUTH column.
     * @param devAuth
     */
    public void setDevAuth(java.lang.String devAuth)
    {
        this.devAuth = devAuth;
    }

    /**
     * Return the value of the COMU_VER column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getComuVer()
    {
        return this.comuVer;
    }

    /**
     * Set the value of the COMU_VER column.
     * @param comuVer
     */
    public void setComuVer(java.lang.Integer comuVer)
    {
        this.comuVer = comuVer;
    }

    /**
     * Return the value of the RUN_REASON column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getRunReason()
    {
        return this.runReason;
    }

    /**
     * Set the value of the RUN_REASON column.
     * @param runReason
     */
    public void setRunReason(java.lang.Integer runReason)
    {
        this.runReason = runReason;
    }

    /**
     * Return the value of the CRC column.
     * @return java.lang.String
     */
    public java.lang.String getCrc()
    {
        return this.crc;
    }

    /**
     * Set the value of the CRC column.
     * @param crc
     */
    public void setCrc(java.lang.String crc)
    {
        this.crc = crc;
    }

    /**
     * Return the value of the ECODE column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getEcode()
    {
        return this.ecode;
    }

    /**
     * Set the value of the ECODE column.
     * @param ecode
     */
    public void setEcode(java.lang.Integer ecode)
    {
        this.ecode = ecode;
    }

    /**
     * Return the value of the REVISESERIAL_NO column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getReviseserialNo()
    {
        return this.reviseserialNo;
    }

    /**
     * Set the value of the REVISESERIAL_NO column.
     * @param reviseserialNo
     */
    public void setReviseserialNo(java.lang.Integer reviseserialNo)
    {
        this.reviseserialNo = reviseserialNo;
    }

    /**
     * Return the value of the RESERVE_1 column.
     * @return java.lang.String
     */
    public java.lang.String getReserve1()
    {
        return this.reserve1;
    }

    /**
     * Set the value of the RESERVE_1 column.
     * @param reserve1
     */
    public void setReserve1(java.lang.String reserve1)
    {
        this.reserve1 = reserve1;
    }

    /**
     * Return the value of the RESERVE_2 column.
     * @return java.lang.String
     */
    public java.lang.String getReserve2()
    {
        return this.reserve2;
    }

    /**
     * Set the value of the RESERVE_2 column.
     * @param reserve2
     */
    public void setReserve2(java.lang.String reserve2)
    {
        this.reserve2 = reserve2;
    }

    /**
     * Return the value of the RESERVE_3 column.
     * @return java.lang.String
     */
    public java.lang.String getReserve3()
    {
        return this.reserve3;
    }

    /**
     * Set the value of the RESERVE_3 column.
     * @param reserve3
     */
    public void setReserve3(java.lang.String reserve3)
    {
        this.reserve3 = reserve3;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof TTifTradeserialHis))
            return false;
        TTifTradeserialHis that = (TTifTradeserialHis) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            if (this.getId() == null)
            {
                result = super.hashCode();
            }
            else
            {
                result = this.getId().hashCode();
            }
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
