package com.sungard.smartcard.bccsvr.modules.operator.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class OperatorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public OperatorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOpercodeIsNull() {
            addCriterion("OPERCODE is null");
            return (Criteria) this;
        }

        public Criteria andOpercodeIsNotNull() {
            addCriterion("OPERCODE is not null");
            return (Criteria) this;
        }

        public Criteria andOpercodeEqualTo(String value) {
            addCriterion("OPERCODE =", value, "opercode");
            return (Criteria) this;
        }

        public Criteria andOpercodeNotEqualTo(String value) {
            addCriterion("OPERCODE <>", value, "opercode");
            return (Criteria) this;
        }

        public Criteria andOpercodeGreaterThan(String value) {
            addCriterion("OPERCODE >", value, "opercode");
            return (Criteria) this;
        }

        public Criteria andOpercodeGreaterThanOrEqualTo(String value) {
            addCriterion("OPERCODE >=", value, "opercode");
            return (Criteria) this;
        }

        public Criteria andOpercodeLessThan(String value) {
            addCriterion("OPERCODE <", value, "opercode");
            return (Criteria) this;
        }

        public Criteria andOpercodeLessThanOrEqualTo(String value) {
            addCriterion("OPERCODE <=", value, "opercode");
            return (Criteria) this;
        }

        public Criteria andOpercodeLike(String value) {
            addCriterion("OPERCODE like", value, "opercode");
            return (Criteria) this;
        }

        public Criteria andOpercodeNotLike(String value) {
            addCriterion("OPERCODE not like", value, "opercode");
            return (Criteria) this;
        }

        public Criteria andOpercodeIn(List<String> values) {
            addCriterion("OPERCODE in", values, "opercode");
            return (Criteria) this;
        }

        public Criteria andOpercodeNotIn(List<String> values) {
            addCriterion("OPERCODE not in", values, "opercode");
            return (Criteria) this;
        }

        public Criteria andOpercodeBetween(String value1, String value2) {
            addCriterion("OPERCODE between", value1, value2, "opercode");
            return (Criteria) this;
        }

        public Criteria andOpercodeNotBetween(String value1, String value2) {
            addCriterion("OPERCODE not between", value1, value2, "opercode");
            return (Criteria) this;
        }

        public Criteria andOpertypeIsNull() {
            addCriterion("OPERTYPE is null");
            return (Criteria) this;
        }

        public Criteria andOpertypeIsNotNull() {
            addCriterion("OPERTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOpertypeEqualTo(String value) {
            addCriterion("OPERTYPE =", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeNotEqualTo(String value) {
            addCriterion("OPERTYPE <>", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeGreaterThan(String value) {
            addCriterion("OPERTYPE >", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeGreaterThanOrEqualTo(String value) {
            addCriterion("OPERTYPE >=", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeLessThan(String value) {
            addCriterion("OPERTYPE <", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeLessThanOrEqualTo(String value) {
            addCriterion("OPERTYPE <=", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeLike(String value) {
            addCriterion("OPERTYPE like", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeNotLike(String value) {
            addCriterion("OPERTYPE not like", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeIn(List<String> values) {
            addCriterion("OPERTYPE in", values, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeNotIn(List<String> values) {
            addCriterion("OPERTYPE not in", values, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeBetween(String value1, String value2) {
            addCriterion("OPERTYPE between", value1, value2, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeNotBetween(String value1, String value2) {
            addCriterion("OPERTYPE not between", value1, value2, "opertype");
            return (Criteria) this;
        }

        public Criteria andBranchnoIsNull() {
            addCriterion("BRANCHNO is null");
            return (Criteria) this;
        }

        public Criteria andBranchnoIsNotNull() {
            addCriterion("BRANCHNO is not null");
            return (Criteria) this;
        }

        public Criteria andBranchnoEqualTo(BigDecimal value) {
            addCriterion("BRANCHNO =", value, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoNotEqualTo(BigDecimal value) {
            addCriterion("BRANCHNO <>", value, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoGreaterThan(BigDecimal value) {
            addCriterion("BRANCHNO >", value, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BRANCHNO >=", value, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoLessThan(BigDecimal value) {
            addCriterion("BRANCHNO <", value, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BRANCHNO <=", value, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoIn(List<BigDecimal> values) {
            addCriterion("BRANCHNO in", values, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoNotIn(List<BigDecimal> values) {
            addCriterion("BRANCHNO not in", values, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BRANCHNO between", value1, value2, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BRANCHNO not between", value1, value2, "branchno");
            return (Criteria) this;
        }

        public Criteria andCardnoIsNull() {
            addCriterion("CARDNO is null");
            return (Criteria) this;
        }

        public Criteria andCardnoIsNotNull() {
            addCriterion("CARDNO is not null");
            return (Criteria) this;
        }

        public Criteria andCardnoEqualTo(BigDecimal value) {
            addCriterion("CARDNO =", value, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoNotEqualTo(BigDecimal value) {
            addCriterion("CARDNO <>", value, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoGreaterThan(BigDecimal value) {
            addCriterion("CARDNO >", value, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CARDNO >=", value, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoLessThan(BigDecimal value) {
            addCriterion("CARDNO <", value, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CARDNO <=", value, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoIn(List<BigDecimal> values) {
            addCriterion("CARDNO in", values, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoNotIn(List<BigDecimal> values) {
            addCriterion("CARDNO not in", values, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CARDNO between", value1, value2, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CARDNO not between", value1, value2, "cardno");
            return (Criteria) this;
        }

        public Criteria andOpernameIsNull() {
            addCriterion("OPERNAME is null");
            return (Criteria) this;
        }

        public Criteria andOpernameIsNotNull() {
            addCriterion("OPERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andOpernameEqualTo(String value) {
            addCriterion("OPERNAME =", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotEqualTo(String value) {
            addCriterion("OPERNAME <>", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameGreaterThan(String value) {
            addCriterion("OPERNAME >", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameGreaterThanOrEqualTo(String value) {
            addCriterion("OPERNAME >=", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameLessThan(String value) {
            addCriterion("OPERNAME <", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameLessThanOrEqualTo(String value) {
            addCriterion("OPERNAME <=", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameLike(String value) {
            addCriterion("OPERNAME like", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotLike(String value) {
            addCriterion("OPERNAME not like", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameIn(List<String> values) {
            addCriterion("OPERNAME in", values, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotIn(List<String> values) {
            addCriterion("OPERNAME not in", values, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameBetween(String value1, String value2) {
            addCriterion("OPERNAME between", value1, value2, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotBetween(String value1, String value2) {
            addCriterion("OPERNAME not between", value1, value2, "opername");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("TEL is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("TEL is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("TEL =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("TEL <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("TEL >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("TEL >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("TEL <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("TEL <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("TEL like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("TEL not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("TEL in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("TEL not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("TEL between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("TEL not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("MOBILE =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("MOBILE <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("MOBILE >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("MOBILE <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("MOBILE <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("MOBILE like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("MOBILE not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("MOBILE in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("MOBILE not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("MOBILE between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("MOBILE not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andAddrIsNull() {
            addCriterion("ADDR is null");
            return (Criteria) this;
        }

        public Criteria andAddrIsNotNull() {
            addCriterion("ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andAddrEqualTo(String value) {
            addCriterion("ADDR =", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotEqualTo(String value) {
            addCriterion("ADDR <>", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrGreaterThan(String value) {
            addCriterion("ADDR >", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrGreaterThanOrEqualTo(String value) {
            addCriterion("ADDR >=", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrLessThan(String value) {
            addCriterion("ADDR <", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrLessThanOrEqualTo(String value) {
            addCriterion("ADDR <=", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrLike(String value) {
            addCriterion("ADDR like", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotLike(String value) {
            addCriterion("ADDR not like", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrIn(List<String> values) {
            addCriterion("ADDR in", values, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotIn(List<String> values) {
            addCriterion("ADDR not in", values, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrBetween(String value1, String value2) {
            addCriterion("ADDR between", value1, value2, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotBetween(String value1, String value2) {
            addCriterion("ADDR not between", value1, value2, "addr");
            return (Criteria) this;
        }

        public Criteria andZipcodeIsNull() {
            addCriterion("ZIPCODE is null");
            return (Criteria) this;
        }

        public Criteria andZipcodeIsNotNull() {
            addCriterion("ZIPCODE is not null");
            return (Criteria) this;
        }

        public Criteria andZipcodeEqualTo(String value) {
            addCriterion("ZIPCODE =", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotEqualTo(String value) {
            addCriterion("ZIPCODE <>", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeGreaterThan(String value) {
            addCriterion("ZIPCODE >", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeGreaterThanOrEqualTo(String value) {
            addCriterion("ZIPCODE >=", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeLessThan(String value) {
            addCriterion("ZIPCODE <", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeLessThanOrEqualTo(String value) {
            addCriterion("ZIPCODE <=", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeLike(String value) {
            addCriterion("ZIPCODE like", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotLike(String value) {
            addCriterion("ZIPCODE not like", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeIn(List<String> values) {
            addCriterion("ZIPCODE in", values, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotIn(List<String> values) {
            addCriterion("ZIPCODE not in", values, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeBetween(String value1, String value2) {
            addCriterion("ZIPCODE between", value1, value2, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotBetween(String value1, String value2) {
            addCriterion("ZIPCODE not between", value1, value2, "zipcode");
            return (Criteria) this;
        }

        public Criteria andOperpwdIsNull() {
            addCriterion("OPERPWD is null");
            return (Criteria) this;
        }

        public Criteria andOperpwdIsNotNull() {
            addCriterion("OPERPWD is not null");
            return (Criteria) this;
        }

        public Criteria andOperpwdEqualTo(String value) {
            addCriterion("OPERPWD =", value, "operpwd");
            return (Criteria) this;
        }

        public Criteria andOperpwdNotEqualTo(String value) {
            addCriterion("OPERPWD <>", value, "operpwd");
            return (Criteria) this;
        }

        public Criteria andOperpwdGreaterThan(String value) {
            addCriterion("OPERPWD >", value, "operpwd");
            return (Criteria) this;
        }

        public Criteria andOperpwdGreaterThanOrEqualTo(String value) {
            addCriterion("OPERPWD >=", value, "operpwd");
            return (Criteria) this;
        }

        public Criteria andOperpwdLessThan(String value) {
            addCriterion("OPERPWD <", value, "operpwd");
            return (Criteria) this;
        }

        public Criteria andOperpwdLessThanOrEqualTo(String value) {
            addCriterion("OPERPWD <=", value, "operpwd");
            return (Criteria) this;
        }

        public Criteria andOperpwdLike(String value) {
            addCriterion("OPERPWD like", value, "operpwd");
            return (Criteria) this;
        }

        public Criteria andOperpwdNotLike(String value) {
            addCriterion("OPERPWD not like", value, "operpwd");
            return (Criteria) this;
        }

        public Criteria andOperpwdIn(List<String> values) {
            addCriterion("OPERPWD in", values, "operpwd");
            return (Criteria) this;
        }

        public Criteria andOperpwdNotIn(List<String> values) {
            addCriterion("OPERPWD not in", values, "operpwd");
            return (Criteria) this;
        }

        public Criteria andOperpwdBetween(String value1, String value2) {
            addCriterion("OPERPWD between", value1, value2, "operpwd");
            return (Criteria) this;
        }

        public Criteria andOperpwdNotBetween(String value1, String value2) {
            addCriterion("OPERPWD not between", value1, value2, "operpwd");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andLasttransdateIsNull() {
            addCriterion("LASTTRANSDATE is null");
            return (Criteria) this;
        }

        public Criteria andLasttransdateIsNotNull() {
            addCriterion("LASTTRANSDATE is not null");
            return (Criteria) this;
        }

        public Criteria andLasttransdateEqualTo(String value) {
            addCriterion("LASTTRANSDATE =", value, "lasttransdate");
            return (Criteria) this;
        }

        public Criteria andLasttransdateNotEqualTo(String value) {
            addCriterion("LASTTRANSDATE <>", value, "lasttransdate");
            return (Criteria) this;
        }

        public Criteria andLasttransdateGreaterThan(String value) {
            addCriterion("LASTTRANSDATE >", value, "lasttransdate");
            return (Criteria) this;
        }

        public Criteria andLasttransdateGreaterThanOrEqualTo(String value) {
            addCriterion("LASTTRANSDATE >=", value, "lasttransdate");
            return (Criteria) this;
        }

        public Criteria andLasttransdateLessThan(String value) {
            addCriterion("LASTTRANSDATE <", value, "lasttransdate");
            return (Criteria) this;
        }

        public Criteria andLasttransdateLessThanOrEqualTo(String value) {
            addCriterion("LASTTRANSDATE <=", value, "lasttransdate");
            return (Criteria) this;
        }

        public Criteria andLasttransdateLike(String value) {
            addCriterion("LASTTRANSDATE like", value, "lasttransdate");
            return (Criteria) this;
        }

        public Criteria andLasttransdateNotLike(String value) {
            addCriterion("LASTTRANSDATE not like", value, "lasttransdate");
            return (Criteria) this;
        }

        public Criteria andLasttransdateIn(List<String> values) {
            addCriterion("LASTTRANSDATE in", values, "lasttransdate");
            return (Criteria) this;
        }

        public Criteria andLasttransdateNotIn(List<String> values) {
            addCriterion("LASTTRANSDATE not in", values, "lasttransdate");
            return (Criteria) this;
        }

        public Criteria andLasttransdateBetween(String value1, String value2) {
            addCriterion("LASTTRANSDATE between", value1, value2, "lasttransdate");
            return (Criteria) this;
        }

        public Criteria andLasttransdateNotBetween(String value1, String value2) {
            addCriterion("LASTTRANSDATE not between", value1, value2, "lasttransdate");
            return (Criteria) this;
        }

        public Criteria andMenusetIsNull() {
            addCriterion("MENUSET is null");
            return (Criteria) this;
        }

        public Criteria andMenusetIsNotNull() {
            addCriterion("MENUSET is not null");
            return (Criteria) this;
        }

        public Criteria andMenusetEqualTo(String value) {
            addCriterion("MENUSET =", value, "menuset");
            return (Criteria) this;
        }

        public Criteria andMenusetNotEqualTo(String value) {
            addCriterion("MENUSET <>", value, "menuset");
            return (Criteria) this;
        }

        public Criteria andMenusetGreaterThan(String value) {
            addCriterion("MENUSET >", value, "menuset");
            return (Criteria) this;
        }

        public Criteria andMenusetGreaterThanOrEqualTo(String value) {
            addCriterion("MENUSET >=", value, "menuset");
            return (Criteria) this;
        }

        public Criteria andMenusetLessThan(String value) {
            addCriterion("MENUSET <", value, "menuset");
            return (Criteria) this;
        }

        public Criteria andMenusetLessThanOrEqualTo(String value) {
            addCriterion("MENUSET <=", value, "menuset");
            return (Criteria) this;
        }

        public Criteria andMenusetLike(String value) {
            addCriterion("MENUSET like", value, "menuset");
            return (Criteria) this;
        }

        public Criteria andMenusetNotLike(String value) {
            addCriterion("MENUSET not like", value, "menuset");
            return (Criteria) this;
        }

        public Criteria andMenusetIn(List<String> values) {
            addCriterion("MENUSET in", values, "menuset");
            return (Criteria) this;
        }

        public Criteria andMenusetNotIn(List<String> values) {
            addCriterion("MENUSET not in", values, "menuset");
            return (Criteria) this;
        }

        public Criteria andMenusetBetween(String value1, String value2) {
            addCriterion("MENUSET between", value1, value2, "menuset");
            return (Criteria) this;
        }

        public Criteria andMenusetNotBetween(String value1, String value2) {
            addCriterion("MENUSET not between", value1, value2, "menuset");
            return (Criteria) this;
        }

        public Criteria andFuncsetIsNull() {
            addCriterion("FUNCSET is null");
            return (Criteria) this;
        }

        public Criteria andFuncsetIsNotNull() {
            addCriterion("FUNCSET is not null");
            return (Criteria) this;
        }

        public Criteria andFuncsetEqualTo(String value) {
            addCriterion("FUNCSET =", value, "funcset");
            return (Criteria) this;
        }

        public Criteria andFuncsetNotEqualTo(String value) {
            addCriterion("FUNCSET <>", value, "funcset");
            return (Criteria) this;
        }

        public Criteria andFuncsetGreaterThan(String value) {
            addCriterion("FUNCSET >", value, "funcset");
            return (Criteria) this;
        }

        public Criteria andFuncsetGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCSET >=", value, "funcset");
            return (Criteria) this;
        }

        public Criteria andFuncsetLessThan(String value) {
            addCriterion("FUNCSET <", value, "funcset");
            return (Criteria) this;
        }

        public Criteria andFuncsetLessThanOrEqualTo(String value) {
            addCriterion("FUNCSET <=", value, "funcset");
            return (Criteria) this;
        }

        public Criteria andFuncsetLike(String value) {
            addCriterion("FUNCSET like", value, "funcset");
            return (Criteria) this;
        }

        public Criteria andFuncsetNotLike(String value) {
            addCriterion("FUNCSET not like", value, "funcset");
            return (Criteria) this;
        }

        public Criteria andFuncsetIn(List<String> values) {
            addCriterion("FUNCSET in", values, "funcset");
            return (Criteria) this;
        }

        public Criteria andFuncsetNotIn(List<String> values) {
            addCriterion("FUNCSET not in", values, "funcset");
            return (Criteria) this;
        }

        public Criteria andFuncsetBetween(String value1, String value2) {
            addCriterion("FUNCSET between", value1, value2, "funcset");
            return (Criteria) this;
        }

        public Criteria andFuncsetNotBetween(String value1, String value2) {
            addCriterion("FUNCSET not between", value1, value2, "funcset");
            return (Criteria) this;
        }

        public Criteria andRightflagIsNull() {
            addCriterion("RIGHTFLAG is null");
            return (Criteria) this;
        }

        public Criteria andRightflagIsNotNull() {
            addCriterion("RIGHTFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andRightflagEqualTo(Short value) {
            addCriterion("RIGHTFLAG =", value, "rightflag");
            return (Criteria) this;
        }

        public Criteria andRightflagNotEqualTo(Short value) {
            addCriterion("RIGHTFLAG <>", value, "rightflag");
            return (Criteria) this;
        }

        public Criteria andRightflagGreaterThan(Short value) {
            addCriterion("RIGHTFLAG >", value, "rightflag");
            return (Criteria) this;
        }

        public Criteria andRightflagGreaterThanOrEqualTo(Short value) {
            addCriterion("RIGHTFLAG >=", value, "rightflag");
            return (Criteria) this;
        }

        public Criteria andRightflagLessThan(Short value) {
            addCriterion("RIGHTFLAG <", value, "rightflag");
            return (Criteria) this;
        }

        public Criteria andRightflagLessThanOrEqualTo(Short value) {
            addCriterion("RIGHTFLAG <=", value, "rightflag");
            return (Criteria) this;
        }

        public Criteria andRightflagIn(List<Short> values) {
            addCriterion("RIGHTFLAG in", values, "rightflag");
            return (Criteria) this;
        }

        public Criteria andRightflagNotIn(List<Short> values) {
            addCriterion("RIGHTFLAG not in", values, "rightflag");
            return (Criteria) this;
        }

        public Criteria andRightflagBetween(Short value1, Short value2) {
            addCriterion("RIGHTFLAG between", value1, value2, "rightflag");
            return (Criteria) this;
        }

        public Criteria andRightflagNotBetween(Short value1, Short value2) {
            addCriterion("RIGHTFLAG not between", value1, value2, "rightflag");
            return (Criteria) this;
        }

        public Criteria andSitelimitIsNull() {
            addCriterion("SITELIMIT is null");
            return (Criteria) this;
        }

        public Criteria andSitelimitIsNotNull() {
            addCriterion("SITELIMIT is not null");
            return (Criteria) this;
        }

        public Criteria andSitelimitEqualTo(String value) {
            addCriterion("SITELIMIT =", value, "sitelimit");
            return (Criteria) this;
        }

        public Criteria andSitelimitNotEqualTo(String value) {
            addCriterion("SITELIMIT <>", value, "sitelimit");
            return (Criteria) this;
        }

        public Criteria andSitelimitGreaterThan(String value) {
            addCriterion("SITELIMIT >", value, "sitelimit");
            return (Criteria) this;
        }

        public Criteria andSitelimitGreaterThanOrEqualTo(String value) {
            addCriterion("SITELIMIT >=", value, "sitelimit");
            return (Criteria) this;
        }

        public Criteria andSitelimitLessThan(String value) {
            addCriterion("SITELIMIT <", value, "sitelimit");
            return (Criteria) this;
        }

        public Criteria andSitelimitLessThanOrEqualTo(String value) {
            addCriterion("SITELIMIT <=", value, "sitelimit");
            return (Criteria) this;
        }

        public Criteria andSitelimitLike(String value) {
            addCriterion("SITELIMIT like", value, "sitelimit");
            return (Criteria) this;
        }

        public Criteria andSitelimitNotLike(String value) {
            addCriterion("SITELIMIT not like", value, "sitelimit");
            return (Criteria) this;
        }

        public Criteria andSitelimitIn(List<String> values) {
            addCriterion("SITELIMIT in", values, "sitelimit");
            return (Criteria) this;
        }

        public Criteria andSitelimitNotIn(List<String> values) {
            addCriterion("SITELIMIT not in", values, "sitelimit");
            return (Criteria) this;
        }

        public Criteria andSitelimitBetween(String value1, String value2) {
            addCriterion("SITELIMIT between", value1, value2, "sitelimit");
            return (Criteria) this;
        }

        public Criteria andSitelimitNotBetween(String value1, String value2) {
            addCriterion("SITELIMIT not between", value1, value2, "sitelimit");
            return (Criteria) this;
        }

        public Criteria andLoginflagIsNull() {
            addCriterion("LOGINFLAG is null");
            return (Criteria) this;
        }

        public Criteria andLoginflagIsNotNull() {
            addCriterion("LOGINFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andLoginflagEqualTo(String value) {
            addCriterion("LOGINFLAG =", value, "loginflag");
            return (Criteria) this;
        }

        public Criteria andLoginflagNotEqualTo(String value) {
            addCriterion("LOGINFLAG <>", value, "loginflag");
            return (Criteria) this;
        }

        public Criteria andLoginflagGreaterThan(String value) {
            addCriterion("LOGINFLAG >", value, "loginflag");
            return (Criteria) this;
        }

        public Criteria andLoginflagGreaterThanOrEqualTo(String value) {
            addCriterion("LOGINFLAG >=", value, "loginflag");
            return (Criteria) this;
        }

        public Criteria andLoginflagLessThan(String value) {
            addCriterion("LOGINFLAG <", value, "loginflag");
            return (Criteria) this;
        }

        public Criteria andLoginflagLessThanOrEqualTo(String value) {
            addCriterion("LOGINFLAG <=", value, "loginflag");
            return (Criteria) this;
        }

        public Criteria andLoginflagLike(String value) {
            addCriterion("LOGINFLAG like", value, "loginflag");
            return (Criteria) this;
        }

        public Criteria andLoginflagNotLike(String value) {
            addCriterion("LOGINFLAG not like", value, "loginflag");
            return (Criteria) this;
        }

        public Criteria andLoginflagIn(List<String> values) {
            addCriterion("LOGINFLAG in", values, "loginflag");
            return (Criteria) this;
        }

        public Criteria andLoginflagNotIn(List<String> values) {
            addCriterion("LOGINFLAG not in", values, "loginflag");
            return (Criteria) this;
        }

        public Criteria andLoginflagBetween(String value1, String value2) {
            addCriterion("LOGINFLAG between", value1, value2, "loginflag");
            return (Criteria) this;
        }

        public Criteria andLoginflagNotBetween(String value1, String value2) {
            addCriterion("LOGINFLAG not between", value1, value2, "loginflag");
            return (Criteria) this;
        }

        public Criteria andLoginsitenoIsNull() {
            addCriterion("LOGINSITENO is null");
            return (Criteria) this;
        }

        public Criteria andLoginsitenoIsNotNull() {
            addCriterion("LOGINSITENO is not null");
            return (Criteria) this;
        }

        public Criteria andLoginsitenoEqualTo(BigDecimal value) {
            addCriterion("LOGINSITENO =", value, "loginsiteno");
            return (Criteria) this;
        }

        public Criteria andLoginsitenoNotEqualTo(BigDecimal value) {
            addCriterion("LOGINSITENO <>", value, "loginsiteno");
            return (Criteria) this;
        }

        public Criteria andLoginsitenoGreaterThan(BigDecimal value) {
            addCriterion("LOGINSITENO >", value, "loginsiteno");
            return (Criteria) this;
        }

        public Criteria andLoginsitenoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LOGINSITENO >=", value, "loginsiteno");
            return (Criteria) this;
        }

        public Criteria andLoginsitenoLessThan(BigDecimal value) {
            addCriterion("LOGINSITENO <", value, "loginsiteno");
            return (Criteria) this;
        }

        public Criteria andLoginsitenoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LOGINSITENO <=", value, "loginsiteno");
            return (Criteria) this;
        }

        public Criteria andLoginsitenoIn(List<BigDecimal> values) {
            addCriterion("LOGINSITENO in", values, "loginsiteno");
            return (Criteria) this;
        }

        public Criteria andLoginsitenoNotIn(List<BigDecimal> values) {
            addCriterion("LOGINSITENO not in", values, "loginsiteno");
            return (Criteria) this;
        }

        public Criteria andLoginsitenoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOGINSITENO between", value1, value2, "loginsiteno");
            return (Criteria) this;
        }

        public Criteria andLoginsitenoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOGINSITENO not between", value1, value2, "loginsiteno");
            return (Criteria) this;
        }

        public Criteria andLogintimeIsNull() {
            addCriterion("LOGINTIME is null");
            return (Criteria) this;
        }

        public Criteria andLogintimeIsNotNull() {
            addCriterion("LOGINTIME is not null");
            return (Criteria) this;
        }

        public Criteria andLogintimeEqualTo(String value) {
            addCriterion("LOGINTIME =", value, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeNotEqualTo(String value) {
            addCriterion("LOGINTIME <>", value, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeGreaterThan(String value) {
            addCriterion("LOGINTIME >", value, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeGreaterThanOrEqualTo(String value) {
            addCriterion("LOGINTIME >=", value, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeLessThan(String value) {
            addCriterion("LOGINTIME <", value, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeLessThanOrEqualTo(String value) {
            addCriterion("LOGINTIME <=", value, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeLike(String value) {
            addCriterion("LOGINTIME like", value, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeNotLike(String value) {
            addCriterion("LOGINTIME not like", value, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeIn(List<String> values) {
            addCriterion("LOGINTIME in", values, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeNotIn(List<String> values) {
            addCriterion("LOGINTIME not in", values, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeBetween(String value1, String value2) {
            addCriterion("LOGINTIME between", value1, value2, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeNotBetween(String value1, String value2) {
            addCriterion("LOGINTIME not between", value1, value2, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogouttimeIsNull() {
            addCriterion("LOGOUTTIME is null");
            return (Criteria) this;
        }

        public Criteria andLogouttimeIsNotNull() {
            addCriterion("LOGOUTTIME is not null");
            return (Criteria) this;
        }

        public Criteria andLogouttimeEqualTo(String value) {
            addCriterion("LOGOUTTIME =", value, "logouttime");
            return (Criteria) this;
        }

        public Criteria andLogouttimeNotEqualTo(String value) {
            addCriterion("LOGOUTTIME <>", value, "logouttime");
            return (Criteria) this;
        }

        public Criteria andLogouttimeGreaterThan(String value) {
            addCriterion("LOGOUTTIME >", value, "logouttime");
            return (Criteria) this;
        }

        public Criteria andLogouttimeGreaterThanOrEqualTo(String value) {
            addCriterion("LOGOUTTIME >=", value, "logouttime");
            return (Criteria) this;
        }

        public Criteria andLogouttimeLessThan(String value) {
            addCriterion("LOGOUTTIME <", value, "logouttime");
            return (Criteria) this;
        }

        public Criteria andLogouttimeLessThanOrEqualTo(String value) {
            addCriterion("LOGOUTTIME <=", value, "logouttime");
            return (Criteria) this;
        }

        public Criteria andLogouttimeLike(String value) {
            addCriterion("LOGOUTTIME like", value, "logouttime");
            return (Criteria) this;
        }

        public Criteria andLogouttimeNotLike(String value) {
            addCriterion("LOGOUTTIME not like", value, "logouttime");
            return (Criteria) this;
        }

        public Criteria andLogouttimeIn(List<String> values) {
            addCriterion("LOGOUTTIME in", values, "logouttime");
            return (Criteria) this;
        }

        public Criteria andLogouttimeNotIn(List<String> values) {
            addCriterion("LOGOUTTIME not in", values, "logouttime");
            return (Criteria) this;
        }

        public Criteria andLogouttimeBetween(String value1, String value2) {
            addCriterion("LOGOUTTIME between", value1, value2, "logouttime");
            return (Criteria) this;
        }

        public Criteria andLogouttimeNotBetween(String value1, String value2) {
            addCriterion("LOGOUTTIME not between", value1, value2, "logouttime");
            return (Criteria) this;
        }

        public Criteria andFailnumberIsNull() {
            addCriterion("FAILNUMBER is null");
            return (Criteria) this;
        }

        public Criteria andFailnumberIsNotNull() {
            addCriterion("FAILNUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andFailnumberEqualTo(BigDecimal value) {
            addCriterion("FAILNUMBER =", value, "failnumber");
            return (Criteria) this;
        }

        public Criteria andFailnumberNotEqualTo(BigDecimal value) {
            addCriterion("FAILNUMBER <>", value, "failnumber");
            return (Criteria) this;
        }

        public Criteria andFailnumberGreaterThan(BigDecimal value) {
            addCriterion("FAILNUMBER >", value, "failnumber");
            return (Criteria) this;
        }

        public Criteria andFailnumberGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FAILNUMBER >=", value, "failnumber");
            return (Criteria) this;
        }

        public Criteria andFailnumberLessThan(BigDecimal value) {
            addCriterion("FAILNUMBER <", value, "failnumber");
            return (Criteria) this;
        }

        public Criteria andFailnumberLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FAILNUMBER <=", value, "failnumber");
            return (Criteria) this;
        }

        public Criteria andFailnumberIn(List<BigDecimal> values) {
            addCriterion("FAILNUMBER in", values, "failnumber");
            return (Criteria) this;
        }

        public Criteria andFailnumberNotIn(List<BigDecimal> values) {
            addCriterion("FAILNUMBER not in", values, "failnumber");
            return (Criteria) this;
        }

        public Criteria andFailnumberBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FAILNUMBER between", value1, value2, "failnumber");
            return (Criteria) this;
        }

        public Criteria andFailnumberNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FAILNUMBER not between", value1, value2, "failnumber");
            return (Criteria) this;
        }

        public Criteria andOpendateIsNull() {
            addCriterion("OPENDATE is null");
            return (Criteria) this;
        }

        public Criteria andOpendateIsNotNull() {
            addCriterion("OPENDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOpendateEqualTo(String value) {
            addCriterion("OPENDATE =", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateNotEqualTo(String value) {
            addCriterion("OPENDATE <>", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateGreaterThan(String value) {
            addCriterion("OPENDATE >", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateGreaterThanOrEqualTo(String value) {
            addCriterion("OPENDATE >=", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateLessThan(String value) {
            addCriterion("OPENDATE <", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateLessThanOrEqualTo(String value) {
            addCriterion("OPENDATE <=", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateLike(String value) {
            addCriterion("OPENDATE like", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateNotLike(String value) {
            addCriterion("OPENDATE not like", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateIn(List<String> values) {
            addCriterion("OPENDATE in", values, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateNotIn(List<String> values) {
            addCriterion("OPENDATE not in", values, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateBetween(String value1, String value2) {
            addCriterion("OPENDATE between", value1, value2, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateNotBetween(String value1, String value2) {
            addCriterion("OPENDATE not between", value1, value2, "opendate");
            return (Criteria) this;
        }

        public Criteria andClosedateIsNull() {
            addCriterion("CLOSEDATE is null");
            return (Criteria) this;
        }

        public Criteria andClosedateIsNotNull() {
            addCriterion("CLOSEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andClosedateEqualTo(String value) {
            addCriterion("CLOSEDATE =", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateNotEqualTo(String value) {
            addCriterion("CLOSEDATE <>", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateGreaterThan(String value) {
            addCriterion("CLOSEDATE >", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateGreaterThanOrEqualTo(String value) {
            addCriterion("CLOSEDATE >=", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateLessThan(String value) {
            addCriterion("CLOSEDATE <", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateLessThanOrEqualTo(String value) {
            addCriterion("CLOSEDATE <=", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateLike(String value) {
            addCriterion("CLOSEDATE like", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateNotLike(String value) {
            addCriterion("CLOSEDATE not like", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateIn(List<String> values) {
            addCriterion("CLOSEDATE in", values, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateNotIn(List<String> values) {
            addCriterion("CLOSEDATE not in", values, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateBetween(String value1, String value2) {
            addCriterion("CLOSEDATE between", value1, value2, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateNotBetween(String value1, String value2) {
            addCriterion("CLOSEDATE not between", value1, value2, "closedate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_OPERATOR
     *
     * @mbggenerated do_not_delete_during_merge Fri Dec 30 09:54:41 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}