package com.sungard.smartcard.bccsvr.modules.operator.domain;

import java.math.BigDecimal;

import com.sungard.smartcard.annotation.TransfersElement;
import com.sungard.smartcard.annotation.TransfersNode;
import com.sungard.smartcard.annotation.TransfersNodeOut;
import com.sungard.smartcard.annotation.TransfersNodeType;

@TransfersElement
public class Operator {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.OPERCODE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    @TransfersNodeOut(value = TransfersNodeType.scust_no, desc = "操作人账号")
    private String opercode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.OPERTYPE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String opertype;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.BRANCHNO
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private BigDecimal branchno;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.CARDNO
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private BigDecimal cardno;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.OPERNAME
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    @TransfersNodeOut(value = TransfersNodeType.sname, desc = "操作人员名")
    private String opername;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.TEL
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.MOBILE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.EMAIL
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    @TransfersNodeOut(value = TransfersNodeType.semail, desc = "邮件")
    private String email;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.ADDR
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.ZIPCODE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.OPERPWD
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String operpwd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.STATUS
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.LASTTRANSDATE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String lasttransdate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.MENUSET
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String menuset;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.FUNCSET
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String funcset;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.RIGHTFLAG
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private Short rightflag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.SITELIMIT
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String sitelimit;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.LOGINFLAG
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String loginflag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.LOGINSITENO
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private BigDecimal loginsiteno;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.LOGINTIME
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String logintime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.LOGOUTTIME
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String logouttime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.FAILNUMBER
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private BigDecimal failnumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.OPENDATE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String opendate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OPERATOR.CLOSEDATE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    private String closedate;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.OPERCODE
     * 
     * @return the value of T_OPERATOR.OPERCODE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    @TransfersNode(name = "scust_no")
    public String getOpercode() {
        return opercode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.OPERCODE
     * 
     * @param opercode
     *            the value for T_OPERATOR.OPERCODE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setOpercode(String opercode) {
        this.opercode = opercode == null ? null : opercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.OPERTYPE
     * 
     * @return the value of T_OPERATOR.OPERTYPE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    @TransfersNode(name = "sstatus2")
    public String getOpertype() {
        return opertype;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.OPERTYPE
     * 
     * @param opertype
     *            the value for T_OPERATOR.OPERTYPE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setOpertype(String opertype) {
        this.opertype = opertype == null ? null : opertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.BRANCHNO
     * 
     * @return the value of T_OPERATOR.BRANCHNO
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public BigDecimal getBranchno() {
        return branchno;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.BRANCHNO
     * 
     * @param branchno
     *            the value for T_OPERATOR.BRANCHNO
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setBranchno(BigDecimal branchno) {
        this.branchno = branchno;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.CARDNO
     * 
     * @return the value of T_OPERATOR.CARDNO
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public BigDecimal getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.CARDNO
     * 
     * @param cardno
     *            the value for T_OPERATOR.CARDNO
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setCardno(BigDecimal cardno) {
        this.cardno = cardno;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.OPERNAME
     * 
     * @return the value of T_OPERATOR.OPERNAME
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    @TransfersNode(name = "sname")
    public String getOpername() {
        return opername;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.OPERNAME
     * 
     * @param opername
     *            the value for T_OPERATOR.OPERNAME
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setOpername(String opername) {
        this.opername = opername == null ? null : opername.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.TEL
     * 
     * @return the value of T_OPERATOR.TEL
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.TEL
     * 
     * @param tel
     *            the value for T_OPERATOR.TEL
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.MOBILE
     * 
     * @return the value of T_OPERATOR.MOBILE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    @TransfersNode(name = "sphone2")
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.MOBILE
     * 
     * @param mobile
     *            the value for T_OPERATOR.MOBILE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.EMAIL
     * 
     * @return the value of T_OPERATOR.EMAIL
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    @TransfersNode(name = "genliang")
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.EMAIL
     * 
     * @param email
     *            the value for T_OPERATOR.EMAIL
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    @TransfersNode(name = "jian22g")
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.ADDR
     * 
     * @return the value of T_OPERATOR.ADDR
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.ADDR
     * 
     * @param addr
     *            the value for T_OPERATOR.ADDR
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.ZIPCODE
     * 
     * @return the value of T_OPERATOR.ZIPCODE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.ZIPCODE
     * 
     * @param zipcode
     *            the value for T_OPERATOR.ZIPCODE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.OPERPWD
     * 
     * @return the value of T_OPERATOR.OPERPWD
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public String getOperpwd() {
        return operpwd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.OPERPWD
     * 
     * @param operpwd
     *            the value for T_OPERATOR.OPERPWD
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setOperpwd(String operpwd) {
        this.operpwd = operpwd == null ? null : operpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.STATUS
     * 
     * @return the value of T_OPERATOR.STATUS
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.STATUS
     * 
     * @param status
     *            the value for T_OPERATOR.STATUS
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.LASTTRANSDATE
     * 
     * @return the value of T_OPERATOR.LASTTRANSDATE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public String getLasttransdate() {
        return lasttransdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.LASTTRANSDATE
     * 
     * @param lasttransdate
     *            the value for T_OPERATOR.LASTTRANSDATE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setLasttransdate(String lasttransdate) {
        this.lasttransdate = lasttransdate == null ? null : lasttransdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.MENUSET
     * 
     * @return the value of T_OPERATOR.MENUSET
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    @TransfersNode(name = "vsvarstr0")
    public String getMenuset() {
        return menuset;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.MENUSET
     * 
     * @param menuset
     *            the value for T_OPERATOR.MENUSET
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setMenuset(String menuset) {
        this.menuset = menuset == null ? null : menuset.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.FUNCSET
     * 
     * @return the value of T_OPERATOR.FUNCSET
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public String getFuncset() {
        return funcset;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.FUNCSET
     * 
     * @param funcset
     *            the value for T_OPERATOR.FUNCSET
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setFuncset(String funcset) {
        this.funcset = funcset == null ? null : funcset.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.RIGHTFLAG
     * 
     * @return the value of T_OPERATOR.RIGHTFLAG
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public Short getRightflag() {
        return rightflag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.RIGHTFLAG
     * 
     * @param rightflag
     *            the value for T_OPERATOR.RIGHTFLAG
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setRightflag(Short rightflag) {
        this.rightflag = rightflag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.SITELIMIT
     * 
     * @return the value of T_OPERATOR.SITELIMIT
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public String getSitelimit() {
        return sitelimit;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.SITELIMIT
     * 
     * @param sitelimit
     *            the value for T_OPERATOR.SITELIMIT
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setSitelimit(String sitelimit) {
        this.sitelimit = sitelimit == null ? null : sitelimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.LOGINFLAG
     * 
     * @return the value of T_OPERATOR.LOGINFLAG
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public String getLoginflag() {
        return loginflag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.LOGINFLAG
     * 
     * @param loginflag
     *            the value for T_OPERATOR.LOGINFLAG
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setLoginflag(String loginflag) {
        this.loginflag = loginflag == null ? null : loginflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.LOGINSITENO
     * 
     * @return the value of T_OPERATOR.LOGINSITENO
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public BigDecimal getLoginsiteno() {
        return loginsiteno;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.LOGINSITENO
     * 
     * @param loginsiteno
     *            the value for T_OPERATOR.LOGINSITENO
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setLoginsiteno(BigDecimal loginsiteno) {
        this.loginsiteno = loginsiteno;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.LOGINTIME
     * 
     * @return the value of T_OPERATOR.LOGINTIME
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public String getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.LOGINTIME
     * 
     * @param logintime
     *            the value for T_OPERATOR.LOGINTIME
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setLogintime(String logintime) {
        this.logintime = logintime == null ? null : logintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.LOGOUTTIME
     * 
     * @return the value of T_OPERATOR.LOGOUTTIME
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public String getLogouttime() {
        return logouttime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.LOGOUTTIME
     * 
     * @param logouttime
     *            the value for T_OPERATOR.LOGOUTTIME
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setLogouttime(String logouttime) {
        this.logouttime = logouttime == null ? null : logouttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.FAILNUMBER
     * 
     * @return the value of T_OPERATOR.FAILNUMBER
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public BigDecimal getFailnumber() {
        return failnumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.FAILNUMBER
     * 
     * @param failnumber
     *            the value for T_OPERATOR.FAILNUMBER
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setFailnumber(BigDecimal failnumber) {
        this.failnumber = failnumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.OPENDATE
     * 
     * @return the value of T_OPERATOR.OPENDATE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public String getOpendate() {
        return opendate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.OPENDATE
     * 
     * @param opendate
     *            the value for T_OPERATOR.OPENDATE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setOpendate(String opendate) {
        this.opendate = opendate == null ? null : opendate.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OPERATOR.CLOSEDATE
     * 
     * @return the value of T_OPERATOR.CLOSEDATE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public String getClosedate() {
        return closedate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OPERATOR.CLOSEDATE
     * 
     * @param closedate
     *            the value for T_OPERATOR.CLOSEDATE
     * 
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    public void setClosedate(String closedate) {
        this.closedate = closedate == null ? null : closedate.trim();
    }
}