package com.sungard.smartcard.bccsvr.modules.operator.domain;

import com.sungard.smartcard.annotation.TransfersElement;
import com.sungard.smartcard.annotation.TransfersNodeOut;
import com.sungard.smartcard.annotation.TransfersNodeType;

import java.io.Serializable;

@TransfersElement
public class Transdtl extends TransdtlKey implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.ACCTIME
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    @TransfersNodeOut(value = TransfersNodeType.sname, desc = "")
    private String acctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.TRANSDATE
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    @TransfersNodeOut(value = TransfersNodeType.saddr, desc = "")
    private String transdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.TRANSTIME
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    @TransfersNodeOut(value = TransfersNodeType.saddr2, desc = "")
    private String transtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.REFNO
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    @TransfersNodeOut(value = TransfersNodeType.lvol0, desc = "")
    private Long refno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.TRANSCODE
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    @TransfersNodeOut(value = TransfersNodeType.damt0, desc = "")
    private Double transcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.CUSTID
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    @TransfersNodeOut(value = TransfersNodeType.damt1, desc = "")
    private Double custid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.CUSTNAME
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    @TransfersNodeOut(value = TransfersNodeType.sbank_code2, desc = "")
    private String custname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.STUEMPNO
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    @TransfersNodeOut(value = TransfersNodeType.sbank_pwd, desc = "")
    private String stuempno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.SHOWCARDNO
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Long showcardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.CARDNO
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Double cardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.PURSENO
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Double purseno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.TRANSFLAG
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Short transflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.CARDCNT
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Double cardcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.CARDBEFBAL
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Double cardbefbal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.CARDAFTBAL
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Double cardaftbal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.AMOUNT
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.ADDAMT
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Double addamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.MANAGEFEE
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Double managefee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.PAYTYPE
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Double paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.VOUCHERNO
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private String voucherno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.OPERCODE
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private String opercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.SYSID
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Double sysid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.DEVPHYID
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private String devphyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.DEVSEQNO
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Double devseqno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.EXTTYPE
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Double exttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.EXTDATA
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private String extdata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.COLDATE
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private String coldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.COLTIME
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private String coltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.OFFLINEFLAG
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Short offlineflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.REVFLAG
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private String revflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.STATUS
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.ERRCODE
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private Double errcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSDTL.REMARK
     *
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.ACCTIME
     *
     * @return the value of T_TRANSDTL.ACCTIME
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public String getAcctime() {
        return acctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.ACCTIME
     *
     * @param acctime the value for T_TRANSDTL.ACCTIME
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setAcctime(String acctime) {
        this.acctime = acctime == null ? null : acctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.TRANSDATE
     *
     * @return the value of T_TRANSDTL.TRANSDATE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public String getTransdate() {
        return transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.TRANSDATE
     *
     * @param transdate the value for T_TRANSDTL.TRANSDATE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setTransdate(String transdate) {
        this.transdate = transdate == null ? null : transdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.TRANSTIME
     *
     * @return the value of T_TRANSDTL.TRANSTIME
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public String getTranstime() {
        return transtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.TRANSTIME
     *
     * @param transtime the value for T_TRANSDTL.TRANSTIME
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setTranstime(String transtime) {
        this.transtime = transtime == null ? null : transtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.REFNO
     *
     * @return the value of T_TRANSDTL.REFNO
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Long getRefno() {
        return refno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.REFNO
     *
     * @param refno the value for T_TRANSDTL.REFNO
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setRefno(Long refno) {
        this.refno = refno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.TRANSCODE
     *
     * @return the value of T_TRANSDTL.TRANSCODE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Double getTranscode() {
        return transcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.TRANSCODE
     *
     * @param transcode the value for T_TRANSDTL.TRANSCODE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setTranscode(Double transcode) {
        this.transcode = transcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.CUSTID
     *
     * @return the value of T_TRANSDTL.CUSTID
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Double getCustid() {
        return custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.CUSTID
     *
     * @param custid the value for T_TRANSDTL.CUSTID
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setCustid(Double custid) {
        this.custid = custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.CUSTNAME
     *
     * @return the value of T_TRANSDTL.CUSTNAME
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.CUSTNAME
     *
     * @param custname the value for T_TRANSDTL.CUSTNAME
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.STUEMPNO
     *
     * @return the value of T_TRANSDTL.STUEMPNO
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public String getStuempno() {
        return stuempno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.STUEMPNO
     *
     * @param stuempno the value for T_TRANSDTL.STUEMPNO
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setStuempno(String stuempno) {
        this.stuempno = stuempno == null ? null : stuempno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.SHOWCARDNO
     *
     * @return the value of T_TRANSDTL.SHOWCARDNO
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Long getShowcardno() {
        return showcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.SHOWCARDNO
     *
     * @param showcardno the value for T_TRANSDTL.SHOWCARDNO
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setShowcardno(Long showcardno) {
        this.showcardno = showcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.CARDNO
     *
     * @return the value of T_TRANSDTL.CARDNO
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Double getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.CARDNO
     *
     * @param cardno the value for T_TRANSDTL.CARDNO
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setCardno(Double cardno) {
        this.cardno = cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.PURSENO
     *
     * @return the value of T_TRANSDTL.PURSENO
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Double getPurseno() {
        return purseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.PURSENO
     *
     * @param purseno the value for T_TRANSDTL.PURSENO
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setPurseno(Double purseno) {
        this.purseno = purseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.TRANSFLAG
     *
     * @return the value of T_TRANSDTL.TRANSFLAG
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Short getTransflag() {
        return transflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.TRANSFLAG
     *
     * @param transflag the value for T_TRANSDTL.TRANSFLAG
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setTransflag(Short transflag) {
        this.transflag = transflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.CARDCNT
     *
     * @return the value of T_TRANSDTL.CARDCNT
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Double getCardcnt() {
        return cardcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.CARDCNT
     *
     * @param cardcnt the value for T_TRANSDTL.CARDCNT
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setCardcnt(Double cardcnt) {
        this.cardcnt = cardcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.CARDBEFBAL
     *
     * @return the value of T_TRANSDTL.CARDBEFBAL
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Double getCardbefbal() {
        return cardbefbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.CARDBEFBAL
     *
     * @param cardbefbal the value for T_TRANSDTL.CARDBEFBAL
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setCardbefbal(Double cardbefbal) {
        this.cardbefbal = cardbefbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.CARDAFTBAL
     *
     * @return the value of T_TRANSDTL.CARDAFTBAL
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Double getCardaftbal() {
        return cardaftbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.CARDAFTBAL
     *
     * @param cardaftbal the value for T_TRANSDTL.CARDAFTBAL
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setCardaftbal(Double cardaftbal) {
        this.cardaftbal = cardaftbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.AMOUNT
     *
     * @return the value of T_TRANSDTL.AMOUNT
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.AMOUNT
     *
     * @param amount the value for T_TRANSDTL.AMOUNT
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.ADDAMT
     *
     * @return the value of T_TRANSDTL.ADDAMT
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Double getAddamt() {
        return addamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.ADDAMT
     *
     * @param addamt the value for T_TRANSDTL.ADDAMT
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setAddamt(Double addamt) {
        this.addamt = addamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.MANAGEFEE
     *
     * @return the value of T_TRANSDTL.MANAGEFEE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Double getManagefee() {
        return managefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.MANAGEFEE
     *
     * @param managefee the value for T_TRANSDTL.MANAGEFEE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setManagefee(Double managefee) {
        this.managefee = managefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.PAYTYPE
     *
     * @return the value of T_TRANSDTL.PAYTYPE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Double getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.PAYTYPE
     *
     * @param paytype the value for T_TRANSDTL.PAYTYPE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setPaytype(Double paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.VOUCHERNO
     *
     * @return the value of T_TRANSDTL.VOUCHERNO
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public String getVoucherno() {
        return voucherno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.VOUCHERNO
     *
     * @param voucherno the value for T_TRANSDTL.VOUCHERNO
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setVoucherno(String voucherno) {
        this.voucherno = voucherno == null ? null : voucherno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.OPERCODE
     *
     * @return the value of T_TRANSDTL.OPERCODE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public String getOpercode() {
        return opercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.OPERCODE
     *
     * @param opercode the value for T_TRANSDTL.OPERCODE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setOpercode(String opercode) {
        this.opercode = opercode == null ? null : opercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.SYSID
     *
     * @return the value of T_TRANSDTL.SYSID
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Double getSysid() {
        return sysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.SYSID
     *
     * @param sysid the value for T_TRANSDTL.SYSID
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setSysid(Double sysid) {
        this.sysid = sysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.DEVPHYID
     *
     * @return the value of T_TRANSDTL.DEVPHYID
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public String getDevphyid() {
        return devphyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.DEVPHYID
     *
     * @param devphyid the value for T_TRANSDTL.DEVPHYID
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setDevphyid(String devphyid) {
        this.devphyid = devphyid == null ? null : devphyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.DEVSEQNO
     *
     * @return the value of T_TRANSDTL.DEVSEQNO
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Double getDevseqno() {
        return devseqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.DEVSEQNO
     *
     * @param devseqno the value for T_TRANSDTL.DEVSEQNO
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setDevseqno(Double devseqno) {
        this.devseqno = devseqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.EXTTYPE
     *
     * @return the value of T_TRANSDTL.EXTTYPE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Double getExttype() {
        return exttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.EXTTYPE
     *
     * @param exttype the value for T_TRANSDTL.EXTTYPE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setExttype(Double exttype) {
        this.exttype = exttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.EXTDATA
     *
     * @return the value of T_TRANSDTL.EXTDATA
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public String getExtdata() {
        return extdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.EXTDATA
     *
     * @param extdata the value for T_TRANSDTL.EXTDATA
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setExtdata(String extdata) {
        this.extdata = extdata == null ? null : extdata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.COLDATE
     *
     * @return the value of T_TRANSDTL.COLDATE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public String getColdate() {
        return coldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.COLDATE
     *
     * @param coldate the value for T_TRANSDTL.COLDATE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setColdate(String coldate) {
        this.coldate = coldate == null ? null : coldate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.COLTIME
     *
     * @return the value of T_TRANSDTL.COLTIME
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public String getColtime() {
        return coltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.COLTIME
     *
     * @param coltime the value for T_TRANSDTL.COLTIME
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setColtime(String coltime) {
        this.coltime = coltime == null ? null : coltime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.OFFLINEFLAG
     *
     * @return the value of T_TRANSDTL.OFFLINEFLAG
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Short getOfflineflag() {
        return offlineflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.OFFLINEFLAG
     *
     * @param offlineflag the value for T_TRANSDTL.OFFLINEFLAG
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setOfflineflag(Short offlineflag) {
        this.offlineflag = offlineflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.REVFLAG
     *
     * @return the value of T_TRANSDTL.REVFLAG
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public String getRevflag() {
        return revflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.REVFLAG
     *
     * @param revflag the value for T_TRANSDTL.REVFLAG
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setRevflag(String revflag) {
        this.revflag = revflag == null ? null : revflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.STATUS
     *
     * @return the value of T_TRANSDTL.STATUS
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.STATUS
     *
     * @param status the value for T_TRANSDTL.STATUS
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.ERRCODE
     *
     * @return the value of T_TRANSDTL.ERRCODE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public Double getErrcode() {
        return errcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.ERRCODE
     *
     * @param errcode the value for T_TRANSDTL.ERRCODE
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setErrcode(Double errcode) {
        this.errcode = errcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSDTL.REMARK
     *
     * @return the value of T_TRANSDTL.REMARK
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSDTL.REMARK
     *
     * @param remark the value for T_TRANSDTL.REMARK
     * @mbggenerated Wed Jan 04 11:34:58 CST 2012
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}