package org.king.schedulemanage.domain;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * AbstractCollegeschedulemodel generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractCollegeschedulemodel extends
		org.king.framework.domain.BaseObject implements java.io.Serializable {

	// Fields

	private String scheduleId;

	private String collegeId;

	private String fromdate;

	private String fromtime;

	private String todate;

	private String totime;

	private String positon;

	private String object;

	private String mission;

	private String remark;

	// Constructors

	/** default constructor */
	public AbstractCollegeschedulemodel() {
	}

	/** full constructor */
	public AbstractCollegeschedulemodel(String collegeId, String fromdate,
			String fromtime, String todate, String totime, String positon,
			String object, String mission, String remark) {
		this.collegeId = collegeId;
		this.fromdate = fromdate;
		this.fromtime = fromtime;
		this.todate = todate;
		this.totime = totime;
		this.positon = positon;
		this.object = object;
		this.mission = mission;
		this.remark = remark;
	}

	// Property accessors

	public String getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(String scheduleId) {
		this.scheduleId = scheduleId;
	}

	public String getCollegeId() {
		return this.collegeId;
	}

	public void setCollegeId(String collegeId) {
		this.collegeId = collegeId;
	}

	public String getFromdate() {
		return this.fromdate;
	}

	public void setFromdate(String fromdate) {
		this.fromdate = fromdate;
	}

	public String getFromtime() {
		return this.fromtime;
	}

	public void setFromtime(String fromtime) {
		this.fromtime = fromtime;
	}

	public String getTodate() {
		return this.todate;
	}

	public void setTodate(String todate) {
		this.todate = todate;
	}

	public String getTotime() {
		return this.totime;
	}

	public void setTotime(String totime) {
		this.totime = totime;
	}

	public String getPositon() {
		return this.positon;
	}

	public void setPositon(String positon) {
		this.positon = positon;
	}

	public String getObject() {
		return this.object;
	}

	public void setObject(String object) {
		this.object = object;
	}

	public String getMission() {
		return this.mission;
	}

	public void setMission(String mission) {
		this.mission = mission;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof AbstractCollegeschedulemodel)) {
			return false;
		}
		AbstractCollegeschedulemodel rhs = (AbstractCollegeschedulemodel) object;
		return new EqualsBuilder().append(this.object, rhs.object).append(
				this.todate, rhs.todate).append(this.collegeId, rhs.collegeId)
				.append(this.totime, rhs.totime).append(this.fromtime,
						rhs.fromtime).append(this.fromdate, rhs.fromdate)
				.append(this.scheduleId, rhs.scheduleId).append(this.positon,
						rhs.positon).append(this.remark, rhs.remark).append(
						this.mission, rhs.mission).isEquals();
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(914633707, -279005901).append(this.object)
				.append(this.todate).append(this.collegeId).append(this.totime)
				.append(this.fromtime).append(this.fromdate).append(
						this.scheduleId).append(this.positon).append(
						this.remark).append(this.mission).toHashCode();
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this).append("object", this.object).append(
				"todate", this.todate).append("fromtime", this.fromtime)
				.append("totime", this.totime).append("mission", this.mission)
				.append("collegeId", this.collegeId).append("scheduleId",
						this.scheduleId).append("fromdate", this.fromdate)
				.append("remark", this.remark).append("positon", this.positon)
				.toString();
	}

}