package org.king.schedulemanage.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * Collegeschedulemodel generated by MyEclipse - Hibernate Tools
 */
public class Collegeschedulemodel extends AbstractCollegeschedulemodel implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Collegeschedulemodel() {
    }

    
    /** full constructor */
    public Collegeschedulemodel(String collegeId, String fromdate, String fromtime, String todate, String totime, String positon, String object, String mission, String remark) {
        super(collegeId, fromdate, fromtime, todate, totime, positon, object, mission, remark);        
    }
   
}
