package com.sungard.smartcard.bccsvr.modules.user.dao;

import com.sungard.smartcard.bccsvr.modules.user.domain.Authority;
import com.sungard.smartcard.bccsvr.modules.user.domain.AuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCT_AUTHORITY
     *
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    int countByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCT_AUTHORITY
     *
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    int deleteByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCT_AUTHORITY
     *
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCT_AUTHORITY
     *
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    int insert(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCT_AUTHORITY
     *
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    int insertSelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCT_AUTHORITY
     *
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    List<Authority> selectByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCT_AUTHORITY
     *
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    Authority selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCT_AUTHORITY
     *
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    int updateByExampleSelective(@Param("record") Authority record, @Param("example") AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCT_AUTHORITY
     *
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    int updateByExample(@Param("record") Authority record, @Param("example") AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCT_AUTHORITY
     *
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    int updateByPrimaryKeySelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCT_AUTHORITY
     *
     * @mbggenerated Fri Dec 30 01:41:20 CST 2011
     */
    int updateByPrimaryKey(Authority record);
}