package org.king.dormitorymanage.domain;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;



/**
 * AbstractDormitorymodel generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractDormitorymodel extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String dormitoryId;
     private double fee;
     private String location;
     private String dormitory;
     private String roomNumber;
     private int accomodation;
     private String classId;
     private String gender;
     private String telphone;
     private String area;
     private String level;
     private String unit;
     private String curDormDept;
     private String ifDistribute;
     private int distributeNum;
     private String memo1;
     private String memo2;
     private int emptyNum;
     private String direction;

    // Constructors

    /** default constructor */
    public AbstractDormitorymodel() {
    }

    
    /** full constructor */
    public AbstractDormitorymodel(double fee, String location, String dormitory, String roomNumber, int accomodation, String classId, String gender, String telphone,String area,String level,String unit,String curDormDept,String ifDistribute,int distributeNum,String memo1,String memo2,int emptyNum,String direction) {
        this.fee = fee;
        this.location = location;
        this.dormitory = dormitory;
        this.roomNumber = roomNumber;
        this.accomodation = accomodation;
        this.classId = classId;
        this.gender = gender;
        this.telphone = telphone;
        this.area=area;
        this.level=level;
        this.unit=unit;
        this.curDormDept=curDormDept;
        this.ifDistribute=ifDistribute;
        this.distributeNum=distributeNum;
        this.memo1=memo1;
        this.memo2=memo2;
        this.emptyNum=emptyNum;
        this.direction=direction;
    }

   
    // Property accessors

    public String getDormitoryId() {
        return this.dormitoryId;
    }
    
    public void setDormitoryId(String dormitoryId) {
        this.dormitoryId = dormitoryId;
    }

    public double getFee() {
        return this.fee;
    }
    
    public void setFee(double fee) {
        this.fee = fee;
    }

    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    public String getDormitory() {
        return this.dormitory;
    }
    
    public void setDormitory(String dormitory) {
        this.dormitory = dormitory;
    }

    public String getRoomNumber() {
        return this.roomNumber;
    }
    
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber;
    }

    public int getAccomodation() {
        return this.accomodation;
    }
    
    public void setAccomodation(int accomodation) {
        this.accomodation = accomodation;
    }

    public String getClassId() {
        return this.classId;
    }
    
    public void setClassId(String classId) {
        this.classId = classId;
    }

    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
   
    public String getTelphone() {
        return this.telphone;
    }
    
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }
    
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    
    public String getCurDormDept() {
        return this.curDormDept;
    }
    
    public void setCurDormDept(String curDormDept) {
        this.curDormDept = curDormDept;
    }
    
    public String getIfDistribute() {
        return this.ifDistribute;
    }
    
    public void setIfDistribute(String ifDistribute) {
        this.ifDistribute = ifDistribute;
    }
    
    public int getDistributeNum() {
        return this.distributeNum;
    }
    
    public void setDistributeNum(int distributeNum) {
        this.distributeNum = distributeNum;
    }
    
    public String getMemo1() {
        return this.memo1;
    }
    
    public void setMemo1(String memo1) {
        this.memo1 = memo1;
    }
    
    public String getMemo2() {
        return this.memo2;
    }
    
    public void setMemo2(String memo2) {
        this.memo2 = memo2;
    }
    
    public int getEmptyNum() {
        return this.emptyNum;
    }
    
    public void setEmptyNum(int emptyNum) {
        this.emptyNum = emptyNum;
    }
    
    public String getDirection() {
        return this.direction;
    }
    
    public void setDirection(String direction) {
        this.direction = direction;
    }

	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof AbstractDormitorymodel)) {
			return false;
		}
		AbstractDormitorymodel rhs = (AbstractDormitorymodel) object;
		return new EqualsBuilder().append(this.gender, rhs.gender).append(
				this.fee, rhs.fee).append(this.dormitoryId, rhs.dormitoryId)
				.append(this.classId, rhs.classId).append(this.roomNumber,
						rhs.roomNumber).append(this.dormitory, rhs.dormitory)
				.append(this.telphone, rhs.telphone).append(this.accomodation,
						rhs.accomodation).append(this.location, rhs.location)
				.isEquals();
	}


	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(-2053312441, 665322171).append(this.gender)
				.append(this.fee).append(this.dormitoryId).append(this.classId)
				.append(this.roomNumber).append(this.dormitory).append(
						this.telphone).append(this.accomodation).append(
						this.location).toHashCode();
	}


	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
				.append("gender", this.gender).append("fee", this.fee).append(
						"dormitoryId", this.dormitoryId).append("classId",
						this.classId).append("roomNumber", this.roomNumber)
				.append("dormitory", this.dormitory).append("telphone",
						this.telphone)
				.append("accomodation", this.accomodation).append("location",
						this.location).toString();
	}
   








}