package org.king.dormitorymanage.domain;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;



/**
 * AbstractDormStuView generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractDormStuView extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private DormStuViewId id;


    // Constructors

    /** default constructor */
    public AbstractDormStuView() {
    }

    

   
    // Property accessors

    public DormStuViewId getId() {
        return this.id;
    }
    
    public void setId(DormStuViewId id) {
        this.id = id;
    }




	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof AbstractDormStuView)) {
			return false;
		}
		AbstractDormStuView rhs = (AbstractDormStuView) object;
		return new EqualsBuilder().append(this.id, rhs.id).isEquals();
	}




	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(-1528801549, -1517410675).append(this.id)
				.toHashCode();
	}




	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
				.append("id", this.id).toString();
	}
   








}