package org.king.dormitorymanage.domain;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;



/**
 * AbstractAccomodationInfo generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractAccomodationInfo extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private AccomodationInfoId id;


    // Constructors

    /** default constructor */
    public AbstractAccomodationInfo() {
    }

    

   
    // Property accessors

    public AccomodationInfoId getId() {
        return this.id;
    }
    
    public void setId(AccomodationInfoId id) {
        this.id = id;
    }




	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof AbstractAccomodationInfo)) {
			return false;
		}
		AbstractAccomodationInfo rhs = (AbstractAccomodationInfo) object;
		return new EqualsBuilder().append(this.id, rhs.id).isEquals();
	}




	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(-1917580249, 464195715).append(this.id)
				.toHashCode();
	}




	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
				.append("id", this.id).toString();
	}
   








}