package org.king.dormitorymanage.domain;



/**
 * AbstractDormExactStuView generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractDormExactStuView extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private DormExactStuViewId id;


    // Constructors

    /** default constructor */
    public AbstractDormExactStuView() {
    }

    
    /** full constructor */
    public AbstractDormExactStuView(DormExactStuViewId id) {
        this.id = id;
    }

   
    // Property accessors

    public DormExactStuViewId getId() {
        return this.id;
    }
    
    public void setId(DormExactStuViewId id) {
        this.id = id;
    }


	public boolean equals(Object arg0) {
		// TODO Auto-generated method stub
		return false;
	}


	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}


	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}
   








}