package org.king.dormitorymanage.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * DormInfoView generated by MyEclipse - Hibernate Tools
 */
public class DormInfoView extends AbstractDormInfoView implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public DormInfoView() {
    }

    
   
}
