;For SH1/SH2 By S.K Dec.12,1995
input	ATD_OUTD.obj
input	ATD_TN.obj
input	ATD_D2T.obj
input	ATD_LC.obj
input	ATD_AFTN.obj
input	ATD_DSE.obj
input	ATD_MAIN.obj
input	ATD_FREQ.obj
input	ATD_DT.obj
input	ATDFLTOF.obj
input	ATD_LCOF.obj
input	ATDRELAY.obj
input	ATD_CNG.obj
input	ATD_STOP.obj
input	ATDMCRYT.obj
;
output	ATD.lnk
form	r
debug
;print	atd.lst	;T.Nose 1996/10/02	/*  By O.Kimoto 1997/10/11 */

exit
