;For SH7043 Poplar/AnzuL
input	cdc_mscr.obj
input	cdc_cdcr.obj
input	cdc_cmd.obj
input	cdc_cntl.obj
input	cdc_dmcr.obj
input	cdc_dtcr.obj
input	cdc_init.obj
input	cdc_main.obj
input	cdc_parm.obj
input	cdc_stup.obj
input	cdc_stir.obj
input	cdc_sub.obj
input	cdc_ctx.obj
input	cdc_modr.obj
input	cdc_hdmr.obj
input	cdc_tbl.obj
input	cdc_int.obj
;
output  CDC.lnk
form    r
debug
;print	cdc.lst	/*  By O.Kimoto 1997/10/11 */

exit
