input	FCM_TCMP.obj
input	FCM_RCMP.obj
input	FCM_PCMP.obj
input	FCM_TCKS.obj
input	FCM_RCKS.obj
input	FCMFIF1.obj
input	FCMFIF2.obj
input	FCMIDCHK.obj
input	FCMFRMS.obj
input	FCMMKCTC.obj
input	FCMDIS.obj
input	FCMNSF.obj
input	FCMDCS.obj
input	FCMNSS.obj
input	FCMDTC.obj
input	FCMNSC.obj
;
output  FCM_COMP.lnk
form    r
debug
;print	fcm_comp.lst	;T.Nose 1996/10/02	/*  By O.Kimoto 1997/10/11 */

exit
