input	SREG.obj
input	GA_REG.obj
input	CPU_REG.obj
input	INI_GA.obj
input	INT_GA.obj
input	KEY_SCN.obj
input	LCD.obj
input	HINOENTY.obj
input	HINO_BUZ.obj
input	DUMMY.obj
input	GA_BUF.obj
input	CHK_MPR.obj
input	PAGE_MEM.obj
input	iu_cdc.obj
input	scdc_dat.obj
input	rt_copy.obj
input	sci_ctrl.obj
input	sci_irpt.obj
input	sci_dat.obj
;
output  IU_DATA.lnk

form    r
debug

;print data.lst	/*  By O.Kimoto 1997/10/11 */
print iu_data.lst
exit
