;For SH7043 KEISATSU
input	data.lnk
input	shdata2.lnk
input	table.lnk
input	shtable2.lnk
input	ini2.lnk
input	int2.lnk
input	mon2.lnk		;ƒfƒoƒbƒO‚Ìˆ×Aã‚É‚Á‚Ä‚¢‚«‚Ü‚·B by O.Kimoto 1998/09/09
input	man.lnk
input	dma.lnk
input	mem.lnk
input	cdc.lnk
input	scn_hino.lnk
;input	scn.lnk		;/* ‚g‚h‚m‚n‚j‚h‚Íê—p By O.Kimoto 1998/09/14 */
input	print.lnk	;/* ‚g‚h‚m‚n‚j‚h‚Íê—p By O.Kimoto 1998/09/14 */
;input	dpr.lnk
input	mdm.lnk
input	s1.lnk		;S1 Œx@FAX 05/06/08 Î‹´³˜a
input	atd.lnk
input	opr.lnk
input	scd2.lnk
input	fcm.lnk
input	fcm_comp.lnk
input	fcm_v34.lnk
;input	opr.lnk	ƒfƒoƒbƒO‚Ì‚½‚ßã‚Éã‚°‚Ü‚· by K.Watanabe 1998/04/28
input	lst.lnk
input	cmn.lnk
;input	scn.lnk ƒfƒoƒbƒO‚Ì‚½‚ßã‚Éã‚°‚Ü‚· T.Nose
;input	idp.lnk		;/* ‚g‚h‚m‚n‚j‚h‚Í•s—v By O.Kimoto 1998/09/14 */
input	ncu.lnk
;input	mdm.lnk  ƒfƒoƒbƒO‚Ì‚½‚ßã‚É‚Á‚Ä‚¢‚«‚Ü‚· Œ´“c '98/03/20
;input	atd.lnk
;input	rot.lnk
input	multi.lnk
;input	cl1.lnk
;input	pat.lnk
;input	mon.lnk	ƒfƒoƒbƒO‚Ìˆ×Aã‚É‚Á‚Ä‚¢‚«‚Ü‚·BBy O.Kimoto 1998/09/09
input	lstword.lnk
input	oprword.lnk
input	flash.lnk
input	iu_data.lnk
input	nd.lnk
input	\src\memsw\sh\msw.lnk
;library \src\atlanta\sh7043\lib\shclib.lib
;library \src\atlanta\sh7043\lib_alr\shclib.lib
library \src\cpu\sh7043_a\lib_alr\shclib.lib
;
output	keisatsu.lnk
form	r
debug

print keisatsu.lst	;/*  By O.Kimoto 1997/10/11 */
exit
