input	man_init.obj
input	man_main.obj
input	man_msge.obj
input	man_scnm.obj
input	man_prtm.obj
input	man_oprm.obj
input	man_comm.obj
input	man_optm.obj
input	man_idle.obj
input	man_timr.obj
input	man_sens.obj
input	man_exec.obj
input	man_sub.obj
input	man_buzr.obj
input	man_led.obj
input	man_mult.obj
input	man_dmy.obj
;
output  MAN.lnk
form    r
debug
;print	man.lst	/*  By O.Kimoto 1997/10/11 */

exit
