input	mdm.obj
input	mdm_cmd.obj
input	mdm_crc.obj
input	mdm_dsp.obj
input	mdm_dtmf.obj
input	mdm_ecm.obj
input	mdm_fact.obj
input	mdm_fltr.obj
input	mdm_fsk.obj
input	mdm_func.obj
input	mdm_g3.obj
input	mdm_int.obj
input	mdm_io.obj
;input	mdm_nd.obj		;/* ND_336.MK‚É‚ ‚è‚Ü‚·BBy T.Takagi 2001/12/21 T.Takagi */
;input	mdm_nddt.obj
input	mdm_sub.obj
;input	mdm_sub2.obj
input	mdm_tcf.obj
input	mdm_tone.obj
;input	mdm_v23.obj
input	mdm_v8.obj
input	mdmrxpix.obj
input	mdmtxpix.obj
input	mdm_data.obj
input	mdm_ebuf.obj
input	mdm_tbl.obj
input	mdm_tblc.obj
input	mdmertbl.obj	;/* MDM_ORNG‚ÉˆÚ“®‚µ‚Ü‚µ‚½BBy O.Kimoto 1997/09/04 */
input	mdm_mldy.obj
;
output  MDM.lnk
form    r
debug

print mdm.lst		;/*  By O.Kimoto 1997/10/11 */
exit
