#ifndef MNT_SW_H
	#define	MNT_SW_H	1

#include "\src\atlanta\define\mntsw_a.h"
#include "\src\atlanta\define\mntsw_b.h"
#include "\src\atlanta\define\mntsw_c.h"
#include "\src\atlanta\define\mntsw_d.h"
#include "\src\atlanta\define\mntsw_e.h"
#include "\src\atlanta\define\mntsw_f.h"
#include "\src\atlanta\define\mntsw_g.h"
#include "\src\atlanta\define\mntsw_h.h"
#include "\src\atlanta\define\mntsw_i.h"
#include "\src\atlanta\define\mntsw_j.h"

#endif
