/*	By Y.Suzuki 1996/10/16	*/
/* Original File : jun\usr2:\src\ichou\define\std.h */
#ifndef std_h
    #define std_h

/***********************************************************************
*          BY:   M.Kotani
*        DATE:   Nov.8,1993
*        TYPE:   DEFINE
* VAR TO HOLD:   N/A
* DESCRIPTION:   ïWèÄíËã`
************************************************************************/
#define		TRUE	1
#define		FALSE	0

#define		OK		1
#define		NG		0
#define		ERROR	-1

#define		YES		1
#define		NO		0

#define		NULL	0x00
#define		CR		0x0D

#endif
