/*-------------------------------------------------------------*/
/* ƒŠƒ‚[ƒg‚e‚`‚wæ‚èo‚µ—pŒ´e’~Ïor‚s‚`‚c—p—pŒ˜^‰¹          */
/*         unsigned char SYS_RemoteFaxTAD_DataRecFlag          */
/*  \src\rice\define\fcm_def.h‚©‚çˆÚ“®B 1994/03/22. by eguchi */
/* 1994/01/27 ‘º“c                                             */
/*-------------------------------------------------------------*/
#define		REMOTE_FAX_DATA			0x01		/*ƒŠƒ‚[ƒg‚e‚`‚w—pŒ´e */
#define		REMOTE_TAD_DATA			0x02		/*‚s‚`‚c—pŒ˜^‰¹ */
#define		REMOTE_FAX_TAD_DATA		0x03		/*—¼•û */
