/*	By M.Kotani 1996/10/29	*/
/*********************************************
 *　SYS_DAY.H
 *　夏時間自動切り替え用
 *　変数：SYS_CurrentSummerTimeStatus
 *  1996/05/21 Eguchi
 *********************************************/
#ifndef SYS_DAY_H
	#define	SYS_DAY_H	1

#define		SYS_BEFORE_SUMMER_TIME	1	/* 夏時間前（年始から夏時間に切り替わるまでの間の時間) */
#define		SYS_DURING_SUMMER_TIME	2	/* 夏時間中 */
#define		SYS_AFTER_SUMMER_TIME	3	/* 夏時間後（夏時間から戻ってから年末までの間の時間） */

#endif

