#ifndef UNI_SW_H
	#define	UNI_SW_H	1

#include "\src\atlanta\define\unisw_a.h"
#include "\src\atlanta\define\unisw_b.h"
#include "\src\atlanta\define\unisw_c.h"
#include "\src\atlanta\define\unisw_d.h"
#include "\src\atlanta\define\unisw_e.h"
#include "\src\atlanta\define\unisw_f.h"
#include "\src\atlanta\define\unisw_g.h"
#include "\src\atlanta\define\unisw_h.h"
#include "\src\atlanta\define\unisw_i.h"
#include "\src\atlanta\define\unisw_j.h"

#endif
