#ifndef  __T_account_H_
#define  __T_account_H_
typedef struct 
{
		char	account_id[16+1];
		int	act_type;
		int	customer_id;
		char	cut_name[60+1];
		int	cut_type;
		char	stuemp_no[20+1];
		int	card_id;
		int	purse_id;
		int	card_type;
		char	subno[20+1];
		char	password[32+1];
		int	current_state;
		char	isautotra[1+1];
		double	last_bala;
		double	last_freebala;
		double	last_frozebala;
		double	cur_bala;
		double	cur_freebala;
		double	cur_frozebala;
		double	out_bala;
		double	in_bala;
		int	out_count;
		int	in_count;
		double	card_balance;
		int	nobala_num;
		int	consume_count;
		char	open_date[10+1];
		char	open_time[8+1];
		char	close_date[10+1];
		char	close_time[8+1];
		char	reserve_1[20+1];
		char	reserve_2[20+1];
		char	reserve_3[20+1];
		char	comments[150+1];
		int	subsidy_no;
}T_t_aif_account;
int DB_t_aif_account_add(T_t_aif_account *pt_aif_account);
int DB_t_aif_account_del_by_account_id(char *v_account_id);
int DB_t_aif_account_read_by_account_id(char *v_account_id,T_t_aif_account *pt_aif_account);
int DB_t_aif_account_read_by_account_id_and_act_type(char *v_account_id,int v_act_type,T_t_aif_account *pt_aif_account);
int DB_t_aif_account_read_by_customer_id_and_act_type(int v_customer_id,int v_act_type,T_t_aif_account *pt_aif_account);
int DB_t_aif_account_read_by_card_id_and_purse_id(int v_card_id,int v_purse_id,T_t_aif_account *pt_aif_account);
int DB_t_aif_account_read_lock_by_cur_and_account_id(char *v_account_id,T_t_aif_account *pt_aif_account);
int DB_t_aif_account_update_by_account_id(char *v_account_id,T_t_aif_account *pt_aif_account);
int DB_t_aif_account_update_lock_by_cur(T_t_aif_account *pt_aif_account);
int DB_t_aif_account_free_lock_cur();
int DB_t_aif_account_open_select_by_cur1();
int DB_t_aif_account_fetch_select_by_cur1(T_t_aif_account *pt_aif_account);
int DB_t_aif_account_close_select_by_cur1();
int DB_t_aif_account_open_select_for_update_by_cur2();
int DB_t_aif_account_fetch_select_by_cur2(T_t_aif_account *pt_aif_account);
int DB_t_aif_account_update_lock_by_cur2(T_t_aif_account *pt_aif_account);
int DB_t_aif_account_close_select_by_cur2();
int DB_t_aif_account_open_select_by_cur3_and_act_type(int v_act_type);
int DB_t_aif_account_fetch_select_by_cur3(T_t_aif_account *pt_aif_account);
int DB_t_aif_account_close_select_by_cur3();
int DB_t_aif_account_read_lock_by_cur4_and_card_id_and_purse_id(int v_card_id,int v_purse_id,T_t_aif_account *pt_aif_account);
int DB_t_aif_account_update_lock_by_cur4(T_t_aif_account *pt_aif_account);
int DB_t_aif_account_free_lock_cur4();
int DB_t_aif_account_read_lock_by_c5_and_customer_id_and_act_type(int v_customer_id,int v_act_type,T_t_aif_account *pt_aif_account);
int DB_t_aif_account_update_lock_by_c5(T_t_aif_account *pt_aif_account);
int DB_t_aif_account_free_lock_c5();
int DB_t_aif_account_open_select_by_cur6_and_act_type_and_current_state(int v_act_type,int v_current_state);
int DB_t_aif_account_fetch_select_by_cur6(T_t_aif_account *pt_aif_account);
int DB_t_aif_account_close_select_by_cur6();
int DB_t_aif_account_read_lock_by_c0_and_card_id_and_purse_id(int v_card_id,int v_purse_id,T_t_aif_account *pt_aif_account);
int DB_t_aif_account_update_lock_by_c0(T_t_aif_account *pt_aif_account);
int DB_t_aif_account_free_lock_c0();
#endif
