package org.king.yangong.dormitorymanage.domain;



/**
 * Abstractcollegedormss generated by MyEclipse - Hibernate Tools
 */

public abstract class Abstractcollegedormss implements java.io.Serializable {


    // Fields    

     private collegedormssId id;


    // Constructors

    /** default constructor */
    public Abstractcollegedormss() {
    }

    
    /** full constructor */
    public Abstractcollegedormss(collegedormssId id) {
        this.id = id;
    }

   
    // Property accessors

    public collegedormssId getId() {
        return this.id;
    }
    
    public void setId(collegedormssId id) {
        this.id = id;
    }
   








}