package org.king.yangong.dormitorymanage.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * collegedormss generated by MyEclipse - Hibernate Tools
 */
public class collegedormss extends Abstractcollegedormss implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public collegedormss() {
    }

    
    /** full constructor */
    public collegedormss(collegedormssId id) {
        super(id);        
    }
   
}
