package org.king.yangong.dormitorymanage.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * DormStuViewYgId generated by MyEclipse - Hibernate Tools
 */
public class DormStuViewYgId extends AbstractDormStuViewYgId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public DormStuViewYgId() {
    }

	/** minimal constructor */
    public DormStuViewYgId(Integer incount) {
        super(incount);        
    }

	public DormStuViewYgId(String area, String location, String dormitory, Integer incount, String curdormdept) {
		super(area, location, dormitory, incount, curdormdept);
		// TODO 自动生成构造函数存根
	}
    

   
}
