package org.king.yangong.dormitorymanage.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * YxGraduate generated by MyEclipse - Hibernate Tools
 */
public class YxGraduate extends AbstractYxGraduate implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public YxGraduate() {
    }

    
    /** full constructor */
    public YxGraduate(String graduateNo, String graduateName, String sex, String enrollYear, String enrollMonth, String nation, String nationality, String birthday, String curGrade, String curCollegeDepartment,String IFPAYDORMFEE, String speciality, String cultureMode, String studentType, String matriculateType, String curDepartment, String curCollege, String adminCollege, double lengthofschool, String graduateType, String distriction, String requestAvailable, String residentNeed, String dormitoryId, String updateTime, String updateDate,String memo,String registerTime) {
        super(graduateNo, graduateName, sex, enrollYear, enrollMonth, nation, nationality, birthday, curGrade, curCollegeDepartment,IFPAYDORMFEE , speciality, cultureMode, studentType, matriculateType, curDepartment, curCollege, adminCollege, lengthofschool, graduateType, distriction, requestAvailable, residentNeed, dormitoryId, updateTime, updateDate,memo,registerTime);        
    }
   
}
