ALTER TABLE YKT_CUR.T_SUBSYSPARAMS
 ADD (BCC_DRTP_IP   VARCHAR2(20));

ALTER TABLE YKT_CUR.T_SUBSYSPARAMS
 ADD (BCC_DRTP_PORT  INTEGER);

ALTER TABLE YKT_CUR.T_SUBSYSPARAMS
 ADD (BCC_MAIN_FUNC  INTEGER);

ALTER TABLE YKT_CUR.T_SUBSYSPARAMS
 ADD (BCC_DRTP_NO  INTEGER);

 ALTER TABLE YKT_CUR.T_SUBSYSPARAMS
 ADD (BCC_INTERVAL  INTEGER);