CREATE TABLE YKT_CUR.T_KEYS
(
KEYID INTEGER NOT NULL,
KEYVALUE VARCHAR(64),
SUMMARY VARCHAR(200),
PRIMARY KEY (KEYID)
);

CREATE TABLE YKT_CUR.T_DEVICEPSAM
(
CARDPHYID VARCHAR(10) NOT NULL,
OPENDATE VARCHAR(8) NOT NULL,
OPENTIME VARCHAR(6) NOT NULL,
CLOSEDATE VARCHAR(8),
CLOSETIME VARCHAR(6),
DEVICENO INTEGER,
STATUS CHAR(1),
PRIMARY KEY (CARDPHYID,OPENDATE,OPENTIME)
);