CREATE TABLE YKT_CUR.T_DOORDOWNLOAD 
(
ID			INTEGER NOT NULL,
CARDVERNO	VARCHAR(12),
CUSTID		INTEGER	NOT NULL,
CTRLID		INTEGER	NOT NULL,
SYSID		INTEGER	NOT NULL,
CARDNO		INTEGER	NOT NULL,
CARDPHYID	VARCHAR(8)	NOT NULL,
RIGHTBIT	VARCHAR(255),
CARDSEQNO	INTEGER NOT NULL ,
WEEKID		INTEGER NOT NULL,
WEEKSEQNO	INTEGER NOT NULL,
HOLIDAYID	INTEGER NOT NULL,
HOLIDAYSEQNO	INTEGER NOT NULL,
CREATETIME	VARCHAR(14) NOT NULL,
SUCCTIME	VARCHAR(14) ,
STATUS		INTEGER NOT NULL,
ADDDELFLAG	NUMBER(1) NOT NULL,
DOORCOUNT   INTEGER,
PRIMARY KEY (ID)
);

CREATE INDEX IDX_DOORDL ON YKT_CUR.T_DOORDOWNLOAD (CARDVERNO,CTRLID);

CREATE SEQUENCE YKT_CUR.S_T_DOORDOWNLOAD
START WITH 0
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;


INSERT INTO YKT_CUR.T_DICTIONARY (DICTTYPE,DICTTYPENAME,DICTVAL,DICTCAPTION)
VALUES (8,'子系统类型','9','门禁认证类');


CREATE TABLE YKT_CUR.T_DOORCARD
(
  DEVICEID    INTEGER,
  CUSTID      INTEGER,
  CARDNO      INTEGER,
  CARDPHYID   VARCHAR2(8)                       NOT NULL,
  CARDVERNO   VARCHAR2(12),
  STATUS      NUMBER(1)                      DEFAULT 0                     NOT NULL,
  INSERTDATE  VARCHAR2(14)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE YKT_CUR.T_DOORCARD ADD (
  CONSTRAINT T_DOORCARD_PK
 PRIMARY KEY
 (DEVICEID, CARDNO));