-- 20110520 新开普的卡定义中缺少的字段存于此表，模拟卡上数据，以支持现有业务流程
CREATE TABLE T_NEWCAPEC_CARD
(
  CARDPHYNO  VARCHAR2(16) NOT NULL,
  APPTYPE    INTEGER,
  FEETYPE    INTEGER,
  CUSTTYPE   INTEGER,
  CUSTID     INTEGER,
  IDTYPE     INTEGER,
  DPSCNT     INTEGER,
  TRANSDATE  INTEGER,
  DAYMAXAMT  INTEGER,
  PUBLISHID  INTEGER,
  SHOWCARDNO INTEGER,
  SUBSIDYNO  INTEGER,
  CARDSTRUCT INTEGER,
  SCHOOLCODE INTEGER
)
TABLESPACE TS_YKT_CUR
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE T_NEWCAPEC_CARD
  ADD CONSTRAINT PK_T_NEWCAPEC_CARD PRIMARY KEY (CARDPHYNO)
  USING INDEX 
  TABLESPACE TS_YKT_CUR
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
