package org.king.check.domain;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

// Generated by MyEclipse - Hibernate Tools



/**
 * TMakereportrecord generated by MyEclipse - Hibernate Tools
 */
public class TMakereportrecord extends AbstractTMakereportrecord implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TMakereportrecord() {
    }

	/** minimal constructor */
    public TMakereportrecord(TMakereportrecordId id) {
        super(id);        
    }
    
    /** full constructor */
    public TMakereportrecord(TMakereportrecordId id, String reportDate, String status) {
        super(id, reportDate, status);        
    }
	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof Toperlimit)) {
			return false;
		}
		Toperlimit rhs = (Toperlimit) object;
		return new EqualsBuilder().isEquals();
	}


	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(-554732475, -351884267).toHashCode();
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this).append("id", this.getId()).append(
				"status", this.getStatus()).append("reportDate",
				this.getReportDate()).toString();
	}
   
}
