/************************************************************************
*	System		: POPLAR
*	File Name	: ALR_DATA.H
*	Author		: Y.Suzuki
*	Date		: 1998/3/9
*	Description	: These parameters are used by Aliroo's module.
*
*	Maintenance	:
*
*	Copyright (C) 1996 Murata Machienry,Ltd. All rights reserved.
*************************************************************************/
#include "\src\atlanta\define\product.h"

/* initialized data section name is DALR2 */
extern DWORD AlrTempData;

/* non-initialized data section name is BALR2 */
extern DWORD AlrTempData2;
