-- Start of generated script for 10.253.42.204-db2inst1-WLGL (db2inst1)
--  Jan-13-2011 at 13:26:04

CREATE TABLE SCHOOLREP.WL_NOTIFY_SEND
 (ID          VARCHAR(32)     NOT NULL,
  ADDRESS     VARCHAR(100),
  TITLE       VARCHAR(100),
  CONTENT     VARCHAR(500),
  PERSONNAME  VARCHAR(50),
  NOTIFY_TYPE VARCHAR(20),
  NOTIFY_TIME TIMESTAMP,
  RECORD_ID   VARCHAR(32),
  IS_VALID    CHARACTER(1),
  CREATE_TIME TIMESTAMP
 )
  DATA CAPTURE NONE;

#SYNC 10;

ALTER TABLE SCHOOLREP.WL_NOTIFY_SEND
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

#SYNC 20;

COMMENT ON SCHOOLREP.WL_NOTIFY_SEND
 (ADDRESS IS '邮件地址或手机号码',
  TITLE IS '标题',
  CONTENT IS '内容',
  PERSONNAME IS '收信人姓名',
  NOTIFY_TYPE IS '通知类型(邮件email；短信mobilemsg；)',
  NOTIFY_TIME IS '成功通知时间',
  RECORD_ID IS '相关记录id',
  IS_VALID IS '是否有效',
  CREATE_TIME IS '创建时间'
 );

#SYNC 30;

ALTER TABLE SCHOOLREP.WL_NOTIFY_SEND
  ADD PRIMARY KEY
   (ID
   );

#SYNC 40;

RUNSTATS ON TABLE SCHOOLREP.WL_NOTIFY_SEND
  AND INDEXES ALL 
  SHRLEVEL REFERENCE;

#SYNC 50;



-- End of generated script for 10.253.42.204-db2inst1-WLGL (db2inst1)