-- Start of generated script for 10.253.42.204-db2inst1-WLGL (db2inst1)
--  Jan-12-2011 at 10:23:36

CREATE TABLE SCHOOLREP.WL_OTHER_CONFIG
 (ID                 VARCHAR(32)     NOT NULL,
  DEPT_ID            VARCHAR(32)     NOT NULL,
  APPLY_NAME         VARCHAR(200)    NOT NULL,
  MEMO               VARCHAR(500),
  UPDATOR_ID         VARCHAR(32),
  UPDATE_TIME        TIMESTAMP,
  NOTIFY_TYPE        VARCHAR(20),
  NOTIFY_PERSON_IDS  VARCHAR(200)
 )
  DATA CAPTURE NONE;

#SYNC 10;

ALTER TABLE SCHOOLREP.WL_OTHER_CONFIG
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

#SYNC 20;

COMMENT ON SCHOOLREP.WL_OTHER_CONFIG
 (NOTIFY_TYPE IS '通知类型(邮件email；短信mobilemsg；)',
  NOTIFY_PERSON_IDS IS '通知人员，可以多个'
 );

#SYNC 30;

ALTER TABLE SCHOOLREP.WL_OTHER_CONFIG
  ADD PRIMARY KEY
   (ID
   );

#SYNC 40;

RUNSTATS ON TABLE SCHOOLREP.WL_OTHER_CONFIG
  AND INDEXES ALL 
  SHRLEVEL REFERENCE;

#SYNC 50;



-- End of generated script for 10.253.42.204-db2inst1-WLGL (db2inst1)