#ifndef MEM_SW_H
	#define	MEM_SW_H	1
#include "\src\memsw\define\mem_sw_a.h"
#include "\src\memsw\define\mem_sw_b.h"
#include "\src\memsw\define\mem_sw_c.h"
#include "\src\memsw\define\mem_sw_d.h"
#include "\src\memsw\define\mem_sw_e.h"
#include "\src\memsw\define\mem_sw_f.h"
#include "\src\memsw\define\mem_sw_g.h"
#include "\src\memsw\define\mem_sw_h.h"
#include "\src\memsw\define\mem_sw_j.h"
#endif
