/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Oct 26 18:47:12 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.kingstargroup.advquery.storelimit;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the T_LEADQUERY_STORELIMIT
 * table.  This object should only be instantiated for use with instances 
 * of the TLeadqueryStorelimit class.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized 
 * by MyEclipse Hibernate tool integration.
 */
public class TLeadqueryStorelimitKey
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private volatile int hashValue = 0;

    /** The value of the OPER_CODE component of this composite id. */
    private java.lang.String operCode;

    /** The value of the STORE_CODE component of this composite id. */
    private java.lang.String storeCode;

    /**
     * Simple constructor of TLeadqueryStorelimitKey instances.
     */
    public TLeadqueryStorelimitKey()
    {
    }

    /**
     * Returns the value of the operCode property.
     * @return java.lang.String
     */
    public java.lang.String getOperCode()
    {
        return operCode;
    }

    /**
     * Sets the value of the operCode property.
     * @param operCode
     */
    public void setOperCode(java.lang.String operCode)
    {
        hashValue = 0;
        this.operCode = operCode;
    }

    /**
     * Returns the value of the storeCode property.
     * @return java.lang.String
     */
    public java.lang.String getStoreCode()
    {
        return storeCode;
    }

    /**
     * Sets the value of the storeCode property.
     * @param storeCode
     */
    public void setStoreCode(java.lang.String storeCode)
    {
        hashValue = 0;
        this.storeCode = storeCode;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the id components.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof TLeadqueryStorelimitKey))
            return false;
        TLeadqueryStorelimitKey that = (TLeadqueryStorelimitKey) rhs;
        if (this.getOperCode() == null || that.getOperCode() == null)
        {
            return false;
        }
        if (! this.getOperCode().equals(that.getOperCode()))
        {
            return false;
        }
        if (this.getStoreCode() == null || that.getStoreCode() == null)
        {
            return false;
        }
        if (! this.getStoreCode().equals(that.getStoreCode()))
        {
            return false;
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int operCodeValue = this.getOperCode() == null ? 0 : this.getOperCode().hashCode();
            result = result * 37 + operCodeValue;
            int storeCodeValue = this.getStoreCode() == null ? 0 : this.getStoreCode().hashCode();
            result = result * 37 + storeCodeValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
