/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Mar 30 09:59:07 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.kingstargroup.conference.hibernate.form;

import java.io.Serializable;

/**
 * A class that represents a row in the T_INFORM_LIST table. 
 * You can customize the behavior of this class by editing the class, {@link TInformList()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractTInformList 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The simple primary key value. */
    private TInformListKey id;

    /** The value of the simple informDate property. */
    private java.lang.String informDate;

    /** The value of the simple informTime property. */
    private java.lang.String informTime;

    /** The value of the simple informSign property. */
    private java.lang.String informSign;

    /**
     * Simple constructor of AbstractTInformList instances.
     */
    public AbstractTInformList()
    {
    }

    /**
     * Constructor of AbstractTInformList instances given a composite primary key.
     * @param id
     */
    public AbstractTInformList(TInformListKey id)
    {
        this.setId(id);
    }

    /**
     * Return the composite id instance that identifies this object.
     * @return TInformListKey
     */
    public TInformListKey getId()
    {
        return this.id;
    }

    /**
     * Set the composite id instance that identifies this object.
     * @param id
     */
    public void setId(TInformListKey id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the INFORM_DATE column.
     * @return java.lang.String
     */
    public java.lang.String getInformDate()
    {
        return this.informDate;
    }

    /**
     * Set the value of the INFORM_DATE column.
     * @param informDate
     */
    public void setInformDate(java.lang.String informDate)
    {
        this.informDate = informDate;
    }

    /**
     * Return the value of the INFORM_TIME column.
     * @return java.lang.String
     */
    public java.lang.String getInformTime()
    {
        return this.informTime;
    }

    /**
     * Set the value of the INFORM_TIME column.
     * @param informTime
     */
    public void setInformTime(java.lang.String informTime)
    {
        this.informTime = informTime;
    }

    /**
     * Return the value of the INFORM_SIGN column.
     * @return java.lang.String
     */
    public java.lang.String getInformSign()
    {
        return this.informSign;
    }

    /**
     * Set the value of the INFORM_SIGN column.
     * @param informSign
     */
    public void setInformSign(java.lang.String informSign)
    {
        this.informSign = informSign;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof TInformList))
            return false;
        TInformList that = (TInformList) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            if (this.getId() == null)
            {
                result = super.hashCode();
            }
            else
            {
                result = this.getId().hashCode();
            }
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
