INSERT INTO YKT_CUR.T_DICTIONARY(DICTTYPE,DICTTYPENAME,DICTVAL,DICTCAPTION) VALUES(14,'商户类型','3','电子支付商户');
INSERT INTO YKT_CUR.T_DICTIONARY(DICTTYPE,DICTTYPENAME,DICTVAL,DICTCAPTION) VALUES(24,'结算商户类型','3','电子支付商户');

insert into YKT_CUR.T_ERRCODE(ERRCODE,ERRMSG) values('600031','参数不合法');
insert into YKT_CUR.T_ERRCODE(ERRCODE,ERRMSG) values('600032','认证失败');
insert into YKT_CUR.T_ERRCODE(ERRCODE,ERRMSG) values('600033','账户锁定');
insert into YKT_CUR.T_ERRCODE(ERRCODE,ERRMSG) values('600034','账户止付');
insert into YKT_CUR.T_ERRCODE(ERRCODE,ERRMSG) values('600035','账户未激活');
insert into YKT_CUR.T_ERRCODE(ERRCODE,ERRMSG) values('600036','账户已注销');
insert into YKT_CUR.T_ERRCODE(ERRCODE,ERRMSG) values('600037','账户异常');
insert into YKT_CUR.T_ERRCODE(ERRCODE,ERRMSG) values('600038','账户余额不足');
insert into YKT_CUR.T_ERRCODE(ERRCODE,ERRMSG) values('600039','后台处理失败');
insert into YKT_CUR.T_ERRCODE(ERRCODE,ERRMSG) values('600041','重复提交');

insert into YKT_CUR.T_CFGTRANS(FEETYPE, TRANSCODE, TRANSTYPE, RATETYPE, RATEAMT, REMARK) values (999, 6230, 253, 0, null, '');
insert into YKT_CUR.T_CFGSPLIT(TRANSTYPE, FUNDTYPE, OFFLINEFLAG, USECARDFLAG, CALCCARDBAL, DRACCFLAG, DRSUBJNO, DRACCNO, CRACCFLAG, CRSUBJNO, CRACCNO, SUMMARY) values (253, 0, 0, 0, 0, 'I', '2003', '', 'I', '2004', '', '电子钱包支付');