package org.king.check.domain;
// Generated by MyEclipse - Hibernate Tools

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;



/**
 * TChecktype generated by MyEclipse - Hibernate Tools
 */
public class TChecktype extends AbstractTChecktype implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TChecktype() {
    }

    
    /** full constructor */
    public TChecktype(String typeName) {
        super(typeName);        
    }


	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof TChecktype)) {
			return false;
		}
		TChecktype rhs = (TChecktype) object;
		return new EqualsBuilder().isEquals();
	}


	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(-897797577, 982444753).toHashCode();
	}


	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this).append("typeName", this.getTypeName())
				.append("typeId", this.getTypeId()).toString();
	}
   
}
