package org.king.security.domain;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import java.util.ArrayList;
import java.util.List;


/**
 * AbstractMenu generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractMenu extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    
    private String code;
    private String id;
    private String pid;
    private String name;
    private String url;
    private String title;
    private String target;
    private String icon;
    private String iconopen;
    private String opened;
    private List<Menu> children = new ArrayList<Menu>();

    private Integer sortFlag = new Integer(0);

    // Constructors

    /**
     * default constructor
     */
    public AbstractMenu() {
    }

    /**
     * minimal constructor
     */
    public AbstractMenu(String pid, String name) {
        this.pid = pid;
        this.name = name;
    }

    protected AbstractMenu(String code, String id, String pid, String name, String url, String title, String target, String icon, String iconopen, String opened, List<Menu> children, Integer sortFlag) {
        this.code = code;
        this.id = id;
        this.pid = pid;
        this.name = name;
        this.url = url;
        this.title = title;
        this.target = target;
        this.icon = icon;
        this.iconopen = iconopen;
        this.opened = opened;
        this.children = children;
        this.sortFlag = sortFlag;
    }

    // Property accessors

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPid() {
        return this.pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTarget() {
        return this.target;
    }

    public void setTarget(String target) {
        this.target = target;
    }

    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getIconopen() {
        return this.iconopen;
    }

    public void setIconopen(String iconopen) {
        this.iconopen = iconopen;
    }

    public String getOpened() {
        return this.opened;
    }

    public void setOpened(String opened) {
        this.opened = opened;
    }

    public Integer getSortFlag() {
        return sortFlag;
    }

    public void setSortFlag(Integer sortFlag) {
        this.sortFlag = sortFlag;
    }

    public List<Menu> getChildren() {
        return children;
    }

    public void setChildren(List<Menu> children) {
        this.children = children;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    /**
     * @see java.lang.Object#equals(Object)
     */
    public boolean equals(Object object) {
        if (!(object instanceof AbstractMenu)) {
            return false;
        }
        AbstractMenu rhs = (AbstractMenu) object;
        return new EqualsBuilder().append(this.opened, rhs.opened).append(
                this.title, rhs.title).append(this.sortFlag, rhs.sortFlag)
                .append(this.icon, rhs.icon).append(this.target, rhs.target)
                .append(this.url, rhs.url).append(this.name, rhs.name).append(
                        this.pid, rhs.pid).append(this.id, rhs.id).append(
                        this.iconopen, rhs.iconopen).isEquals();
    }

    /**
     * @see java.lang.Object#hashCode()
     */
    public int hashCode() {
        return new HashCodeBuilder(482471879, -2125738153).append(this.opened)
                .append(this.title).append(this.sortFlag).append(this.icon)
                .append(this.target).append(this.url).append(this.name).append(
                        this.pid).append(this.id).append(this.iconopen)
                .toHashCode();
    }

    /**
     * @see java.lang.Object#toString()
     */
    public String toString() {
        return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
                .append("sortFlag", this.sortFlag).append("name", this.name)
                .append("iconopen", this.iconopen).append("id", this.id)
                .append("title", this.title).append("url", this.url).append(
                        "target", this.target).append("opened", this.opened)
                .append("pid", this.pid).append("icon", this.icon).toString();
    }


}