package com.kingstargroup.conference.hibernate.form;

import java.sql.Blob;


/**
 * AbstractTCifPhoto generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTCifPhoto  implements java.io.Serializable {


    // Fields    

     private String stuempNo;
     private String cutType;
     private String stuempName;
     private String deptName;
     private String SCode;
     private Integer photoNo;
     private String filename;
     private Blob photo;
     private Integer isCreatecard;
     private String photoDate;
     private String photoTime;
     private Integer isInschool;
     private String libCardid;
     private String curGrade;
     private Integer status;
     private Integer area;
     private String sex;
     private Integer nation;
     private String manId;
     private String tel;
     private String address;
     private String canTime;
     private String reserve1;
     private String reserve2;
     private Integer reserve3;
     private Integer reserve4;
     private String typeName;
     private String deptCode;
     private String SName;
     private String grade;
     private String inDate;
     private String outDate;
     private String id;
     private String areaName;
     private String buildingNo;
     private String floorNo;
     private String roomNo;
     private String medFeetype;
     private String feeType;
     private String updDate;
     private String updTime;
     private String synTime;
     private String classNo;
     private String updStatus;
     private Integer ifcard;
     private String makecarddate;
     private String batchNo;
     private Integer frozenStatus;
     private Blob minphoto;

    // Constructors

    /** default constructor */
    public AbstractTCifPhoto() {
    }

	/** minimal constructor */
    public AbstractTCifPhoto(String stuempNo) {
        this.stuempNo = stuempNo;
    }
    
    /** full constructor */
    public AbstractTCifPhoto(String stuempNo, String cutType, String stuempName, String deptName, String SCode, Integer photoNo, String filename, Blob photo, Integer isCreatecard, String photoDate, String photoTime, Integer isInschool, String libCardid, String curGrade, Integer status, Integer area, String sex, Integer nation, String manId, String tel, String address, String canTime, String reserve1, String reserve2, Integer reserve3, Integer reserve4, String typeName, String deptCode, String SName, String grade, String inDate, String outDate, String id, String areaName, String buildingNo, String floorNo, String roomNo, String medFeetype, String feeType, String updDate, String updTime, String synTime, String classNo, String updStatus, Integer ifcard, String makecarddate, String batchNo, Integer frozenStatus) {
        this.stuempNo = stuempNo;
        this.cutType = cutType;
        this.stuempName = stuempName;
        this.deptName = deptName;
        this.SCode = SCode;
        this.photoNo = photoNo;
        this.filename = filename;
        this.photo = photo;
        this.isCreatecard = isCreatecard;
        this.photoDate = photoDate;
        this.photoTime = photoTime;
        this.isInschool = isInschool;
        this.libCardid = libCardid;
        this.curGrade = curGrade;
        this.status = status;
        this.area = area;
        this.sex = sex;
        this.nation = nation;
        this.manId = manId;
        this.tel = tel;
        this.address = address;
        this.canTime = canTime;
        this.reserve1 = reserve1;
        this.reserve2 = reserve2;
        this.reserve3 = reserve3;
        this.reserve4 = reserve4;
        this.typeName = typeName;
        this.deptCode = deptCode;
        this.SName = SName;
        this.grade = grade;
        this.inDate = inDate;
        this.outDate = outDate;
        this.id = id;
        this.areaName = areaName;
        this.buildingNo = buildingNo;
        this.floorNo = floorNo;
        this.roomNo = roomNo;
        this.medFeetype = medFeetype;
        this.feeType = feeType;
        this.updDate = updDate;
        this.updTime = updTime;
        this.synTime = synTime;
        this.classNo = classNo;
        this.updStatus = updStatus;
        this.ifcard = ifcard;
        this.makecarddate = makecarddate;
        this.batchNo = batchNo;
        this.frozenStatus = frozenStatus;
    }

   
    // Property accessors

    public String getStuempNo() {
        return this.stuempNo;
    }
    
    public void setStuempNo(String stuempNo) {
        this.stuempNo = stuempNo;
    }

    public String getCutType() {
        return this.cutType;
    }
    
    public void setCutType(String cutType) {
        this.cutType = cutType;
    }

    public String getStuempName() {
        return this.stuempName;
    }
    
    public void setStuempName(String stuempName) {
        this.stuempName = stuempName;
    }

    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    public String getSCode() {
        return this.SCode;
    }
    
    public void setSCode(String SCode) {
        this.SCode = SCode;
    }

    public Integer getPhotoNo() {
        return this.photoNo;
    }
    
    public void setPhotoNo(Integer photoNo) {
        this.photoNo = photoNo;
    }

    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    public Blob getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(Blob photo) {
        this.photo = photo;
    }

    public Integer getIsCreatecard() {
        return this.isCreatecard;
    }
    
    public void setIsCreatecard(Integer isCreatecard) {
        this.isCreatecard = isCreatecard;
    }

    public String getPhotoDate() {
        return this.photoDate;
    }
    
    public void setPhotoDate(String photoDate) {
        this.photoDate = photoDate;
    }

    public String getPhotoTime() {
        return this.photoTime;
    }
    
    public void setPhotoTime(String photoTime) {
        this.photoTime = photoTime;
    }

    public Integer getIsInschool() {
        return this.isInschool;
    }
    
    public void setIsInschool(Integer isInschool) {
        this.isInschool = isInschool;
    }

    public String getLibCardid() {
        return this.libCardid;
    }
    
    public void setLibCardid(String libCardid) {
        this.libCardid = libCardid;
    }

    public String getCurGrade() {
        return this.curGrade;
    }
    
    public void setCurGrade(String curGrade) {
        this.curGrade = curGrade;
    }

    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getArea() {
        return this.area;
    }
    
    public void setArea(Integer area) {
        this.area = area;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public Integer getNation() {
        return this.nation;
    }
    
    public void setNation(Integer nation) {
        this.nation = nation;
    }

    public String getManId() {
        return this.manId;
    }
    
    public void setManId(String manId) {
        this.manId = manId;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getCanTime() {
        return this.canTime;
    }
    
    public void setCanTime(String canTime) {
        this.canTime = canTime;
    }

    public String getReserve1() {
        return this.reserve1;
    }
    
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1;
    }

    public String getReserve2() {
        return this.reserve2;
    }
    
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2;
    }

    public Integer getReserve3() {
        return this.reserve3;
    }
    
    public void setReserve3(Integer reserve3) {
        this.reserve3 = reserve3;
    }

    public Integer getReserve4() {
        return this.reserve4;
    }
    
    public void setReserve4(Integer reserve4) {
        this.reserve4 = reserve4;
    }

    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public String getDeptCode() {
        return this.deptCode;
    }
    
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode;
    }

    public String getSName() {
        return this.SName;
    }
    
    public void setSName(String SName) {
        this.SName = SName;
    }

    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }

    public String getInDate() {
        return this.inDate;
    }
    
    public void setInDate(String inDate) {
        this.inDate = inDate;
    }

    public String getOutDate() {
        return this.outDate;
    }
    
    public void setOutDate(String outDate) {
        this.outDate = outDate;
    }

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getAreaName() {
        return this.areaName;
    }
    
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public String getBuildingNo() {
        return this.buildingNo;
    }
    
    public void setBuildingNo(String buildingNo) {
        this.buildingNo = buildingNo;
    }

    public String getFloorNo() {
        return this.floorNo;
    }
    
    public void setFloorNo(String floorNo) {
        this.floorNo = floorNo;
    }

    public String getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }

    public String getMedFeetype() {
        return this.medFeetype;
    }
    
    public void setMedFeetype(String medFeetype) {
        this.medFeetype = medFeetype;
    }

    public String getFeeType() {
        return this.feeType;
    }
    
    public void setFeeType(String feeType) {
        this.feeType = feeType;
    }

    public String getUpdDate() {
        return this.updDate;
    }
    
    public void setUpdDate(String updDate) {
        this.updDate = updDate;
    }

    public String getUpdTime() {
        return this.updTime;
    }
    
    public void setUpdTime(String updTime) {
        this.updTime = updTime;
    }

    public String getSynTime() {
        return this.synTime;
    }
    
    public void setSynTime(String synTime) {
        this.synTime = synTime;
    }

    public String getClassNo() {
        return this.classNo;
    }
    
    public void setClassNo(String classNo) {
        this.classNo = classNo;
    }

    public String getUpdStatus() {
        return this.updStatus;
    }
    
    public void setUpdStatus(String updStatus) {
        this.updStatus = updStatus;
    }

    public Integer getIfcard() {
        return this.ifcard;
    }
    
    public void setIfcard(Integer ifcard) {
        this.ifcard = ifcard;
    }

    public String getMakecarddate() {
        return this.makecarddate;
    }
    
    public void setMakecarddate(String makecarddate) {
        this.makecarddate = makecarddate;
    }

    public String getBatchNo() {
        return this.batchNo;
    }
    
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    public Integer getFrozenStatus() {
        return this.frozenStatus;
    }
    
    public void setFrozenStatus(Integer frozenStatus) {
        this.frozenStatus = frozenStatus;
    }

	public Blob getMinphoto() {
		return minphoto;
	}

	public void setMinphoto(Blob minphoto) {
		this.minphoto = minphoto;
	}
   








}