package com.kingstargroup.conference.hibernate.form;



/**
 * AbstractTRecordhis generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTRecordhis  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer confid;
     private String physicalNo;
     private String checktime;
     
     private String attendSign;
     private String dealornot;


    // Constructors

    public String getDealornot() {
		return dealornot;
	}


	public void setDealornot(String dealornot) {
		this.dealornot = dealornot;
	}


	/** default constructor */
    public AbstractTRecordhis() {
    }

    
    /** full constructor */
    public AbstractTRecordhis(Integer confid, String physicalNo, String checktime,String attendSign,String dealornot) {
        this.confid = confid;
        this.physicalNo = physicalNo;
        this.checktime = checktime;
        this.attendSign = attendSign;
        this.dealornot = dealornot;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getConfid() {
        return this.confid;
    }
    
    public void setConfid(Integer confid) {
        this.confid = confid;
    }

    public String getPhysicalNo() {
        return this.physicalNo;
    }
    
    public void setPhysicalNo(String physicalNo) {
        this.physicalNo = physicalNo;
    }

    public String getChecktime() {
        return this.checktime;
    }
    
    public void setChecktime(String checktime) {
        this.checktime = checktime;
    }


	public String getAttendSign() {
		return attendSign;
	}


	public void setAttendSign(String attendSign) {
		this.attendSign = attendSign;
	}
   








}