package org.king.quarters.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * TabSsManager generated by MyEclipse - Hibernate Tools
 */
public class TabSsManager extends AbstractTabSsManager implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TabSsManager() {
    }

    
    /** full constructor */
    public TabSsManager(TabSsDept tabSsDept,String stuNo, String sex, String contact, String remark, String password) {
        super(tabSsDept, stuNo, sex, contact, remark, password);        
    }
   
}
