/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Dec 23 15:27:40 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.kingstargroup.form;

import java.io.Serializable;

/**
 * A class that represents a row in the MAP_PARAM_TABLE table. 
 * You can customize the behavior of this class by editing the class, {@link MapParamTable()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractMapParamTable 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer id;

    /** The value of the simple parameter property. */
    private java.lang.String parameter;

    /** The value of the simple value property. */
    private java.lang.Double value;

    /** The value of the simple name property. */
    private java.lang.String name;

    /** The value of the simple unit property. */
    private java.lang.String unit;

    /** The value of the simple flag property. */
    private java.lang.Short flag;

    /**
     * Simple constructor of AbstractMapParamTable instances.
     */
    public AbstractMapParamTable()
    {
    }

    /**
     * Constructor of AbstractMapParamTable instances given a simple primary key.
     * @param id
     */
    public AbstractMapParamTable(java.lang.Integer id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Integer id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the PARAMETER column.
     * @return java.lang.String
     */
    public java.lang.String getParameter()
    {
        return this.parameter;
    }

    /**
     * Set the value of the PARAMETER column.
     * @param parameter
     */
    public void setParameter(java.lang.String parameter)
    {
        this.parameter = parameter;
    }

    /**
     * Return the value of the VALUE column.
     * @return java.lang.Double
     */
    public java.lang.Double getValue()
    {
        return this.value;
    }

    /**
     * Set the value of the VALUE column.
     * @param value
     */
    public void setValue(java.lang.Double value)
    {
        this.value = value;
    }

    /**
     * Return the value of the NAME column.
     * @return java.lang.String
     */
    public java.lang.String getName()
    {
        return this.name;
    }

    /**
     * Set the value of the NAME column.
     * @param name
     */
    public void setName(java.lang.String name)
    {
        this.name = name;
    }

    /**
     * Return the value of the UNIT column.
     * @return java.lang.String
     */
    public java.lang.String getUnit()
    {
        return this.unit;
    }

    /**
     * Set the value of the UNIT column.
     * @param unit
     */
    public void setUnit(java.lang.String unit)
    {
        this.unit = unit;
    }

    /**
     * Return the value of the FLAG column.
     * @return java.lang.Short
     */
    public java.lang.Short getFlag()
    {
        return this.flag;
    }

    /**
     * Set the value of the FLAG column.
     * @param flag
     */
    public void setFlag(java.lang.Short flag)
    {
        this.flag = flag;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof MapParamTable))
            return false;
        MapParamTable that = (MapParamTable) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
