insert into YKT_CUR.T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG)
values (847137, '扣款下发', null, null);

insert into YKT_CUR.T_PIF_DICTIONARY (DICT_NO, DICT_VALUE, DICT_NAME, DICT_CAPTION)
values (47, '0225', '三九机型代码', '补助机');
insert into YKT_CUR.T_PIF_SYSKEY (KEY_CODE, KEY_NAME, KEY_VALUE, MAX_VALUE, KEY_TYPE)
values ('TIF_SUBSIDY_NO', '补助批次号', 1, 65535, '0');

INSERT INTO YKT_CUR.T_PIF_CUR_SYSPARA (ID, VALUE, PARA_NAME, USETIME, OPTIME, UNIT, COMMENTS, IS_DISPLAY)
values (16, '400.00', '单笔补助金额上限', '20001212121212', '20001212121212', '', null, '1');


DELETE FROM YKT_CUR.T_TIF_CFGSPLIT WHERE TXTYPE IN (62,63);

INSERT INTO YKT_CUR.T_TIF_CFGSPLIT (TXTYPE, TXNAME, DBFLAG, CRFLAG, DBSUBNO, CRSUBNO, DBACTNO, CRACTNO, FUNDTYPE, SUMMARY) 
VALUES (62, '下发扣款', 2, 2, '122', '506', '1221', '5061', NULL, NULL); 
--INSERT INTO YKT_CUR.T_TIF_CFGSPLIT (TXTYPE, TXNAME, DBFLAG, CRFLAG, DBSUBNO, CRSUBNO, DBACTNO, CRACTNO, FUNDTYPE, SUMMARY) 
--VALUES (63, '领取扣款', 1, 2, '201', '122', NULL, '1221', NULL, NULL); 



UPDATE YKT_CUR.T_TIF_SUBJECT
SET    SUBNAME = '应付水费',
       FATHER  = 218,
       "LEVEL" = 2,
       ENDFLAG = 1,
       SPARE1  = 290
WHERE  SUBNO   = 208
;
  
insert into YKT_CUR.T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG)
values (847231, '佣金划拨', null, null);
insert into YKT_CUR.T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG)
values (847232, '佣金折扣', null, null);

insert into YKT_CUR.T_TIF_SUBJECT (SUBNO, SUBNAME, SUBTYPE, DIRECT, KIND, FATHER, "LEVEL", ENDFLAG, SPARE1, SPARE2, SPARE3)
values ('505', '商户佣金', 5, 2, 0, '530', 2, 1, '550', null, null);

insert into YKT_CUR.T_AIF_ACCOUNT (ACCOUNT_ID, ACT_TYPE, CUSTOMER_ID, CUT_NAME, CUT_TYPE, STUEMP_NO, CARD_ID, PURSE_ID, CARD_TYPE, SUBNO, PASSWORD, CURRENT_STATE, ISAUTOTRA, LAST_BALA, LAST_FREEBALA, LAST_FROZEBALA, CUR_BALA, CUR_FREEBALA, CUR_FROZEBALA, OUT_BALA, IN_BALA, OUT_COUNT, IN_COUNT, CARD_BALANCE, NOBALA_NUM, CONSUME_COUNT, OPEN_DATE, OPEN_TIME, CLOSE_DATE, CLOSE_TIME, RESERVE_1, RESERVE_2, RESERVE_3, COMMENTS, DEPOSIT_BALA)
values ('5051            ', 7, 0, '商户佣金', 0, null, 0, 0, 0, '505', null, 1, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, null, null, null, null, null, null, null, null);

insert into YKT_CUR.T_AIF_ACCOUNT (ACCOUNT_ID, ACT_TYPE, CUSTOMER_ID, CUT_NAME, CUT_TYPE, STUEMP_NO, CARD_ID, PURSE_ID, CARD_TYPE, SUBNO, PASSWORD, CURRENT_STATE, ISAUTOTRA, LAST_BALA, LAST_FREEBALA, LAST_FROZEBALA, CUR_BALA, CUR_FREEBALA, CUR_FROZEBALA, OUT_BALA, IN_BALA, OUT_COUNT, IN_COUNT, CARD_BALANCE, NOBALA_NUM, CONSUME_COUNT, OPEN_DATE, OPEN_TIME, CLOSE_DATE, CLOSE_TIME, RESERVE_1, RESERVE_2, RESERVE_3, COMMENTS, DEPOSIT_BALA)
values ('5061            ', 7, 0, '补助扣款', 0, null, 0, 0, 0, '506', null, 1, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, null, null, null, null, null, null, null, null);

insert into YKT_CUR.T_TIF_SUBJECT (SUBNO, SUBNAME, SUBTYPE, DIRECT, KIND, FATHER, "LEVEL", ENDFLAG, SPARE1, SPARE2, SPARE3)
values ('506', '补助扣款', 5, 2, 0, '530', 2, 1, '560', null, null);

insert into YKT_CUR.T_PIF_DICTIONARY (DICT_NO, DICT_VALUE, DICT_NAME, DICT_CAPTION)
values (19, '4', '帐户状态', '保留账户');

CREATE INDEX YKT_CUR.IDX_BATCH_NO ON YKT_CUR.T_TIF_SUBSIDYTMP
(BATCH_NO, OPER_CODE,CARD_NO)
LOGGING
NOPARALLEL;

CREATE INDEX YKT_CUR.IDX_SUBSIDY_CARD ON YKT_CUR.T_TIF_SUBSIDY
(CARD_NO, SUBSIDY_NO)
LOGGING
NOPARALLEL;


ALTER TABLE YKT_CUR.T_TIF_SUBSIDY
 DROP PRIMARY KEY CASCADE;
DROP TABLE YKT_CUR.T_TIF_SUBSIDY CASCADE CONSTRAINTS;

CREATE TABLE YKT_CUR.T_TIF_SUBSIDY
(
  SUBSIDY_NO   NUMBER                           NOT NULL,
  CUST_NO      NUMBER                           NOT NULL,
  BATCH_NO     VARCHAR2(14 BYTE),
  SEQNO        NUMBER,
  OPER_CODE    VARCHAR2(10 BYTE),
  CARD_NO      NUMBER,
  SUMMARY      VARCHAR2(60 BYTE),
  EXPIRE_DATE  VARCHAR2(8 BYTE),
  BILL_TYPE    NUMBER,
  BILL_NO      VARCHAR2(20 BYTE),
  AMOUNT       NUMBER,
  SUBSIDYTYPE  CHAR(1 BYTE),
  TX_DATE      CHAR(8 BYTE),
  TX_TIME      CHAR(6 BYTE),
  GET_DATE     CHAR(8 BYTE),
  GET_TIME     CHAR(6 BYTE),
  STATUS       CHAR(1 BYTE),
  BROKER_ID    VARCHAR2(18 BYTE),
  BROKER_NAME  VARCHAR2(60 BYTE),
  PRIMARY KEY (BATCH_NO,CUST_NO,SUBSIDY_NO)
)
TABLESPACE TS_YKT_CUR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX YKT_CUR.IDX_SUBSIDY_CARD ON YKT_CUR.T_TIF_SUBSIDY
(CARD_NO, SUBSIDY_NO)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      50
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE YKT_CUR.T_TIF_SUBSIDYTMP
 DROP PRIMARY KEY CASCADE;
DROP TABLE YKT_CUR.T_TIF_SUBSIDYTMP CASCADE CONSTRAINTS;

CREATE TABLE YKT_CUR.T_TIF_SUBSIDYTMP
(
  SUBSIDY_NO   NUMBER,
  CUST_NO      NUMBER                           NOT NULL,
  BATCH_NO     VARCHAR2(14 BYTE),
  SEQNO        NUMBER,
  OPER_CODE    VARCHAR2(10 BYTE),
  CARD_NO      NUMBER,
  SUMMARY      VARCHAR2(60 BYTE),
  EXPIRE_DATE  VARCHAR2(8 BYTE),
  BILL_TYPE    NUMBER,
  BILL_NO      VARCHAR2(20 BYTE),
  AMOUNT       NUMBER,
  SUBSIDYTYPE  CHAR(1 BYTE),
  TX_DATE      CHAR(8 BYTE),
  TX_TIME      CHAR(6 BYTE),
  GET_DATE     CHAR(8 BYTE),
  GET_TIME     CHAR(6 BYTE),
  STATUS       CHAR(1 BYTE),
  BROKER_ID    VARCHAR2(18 BYTE),
  BROKER_NAME  VARCHAR2(60 BYTE),
  PRIMARY KEY (BATCH_NO,CUST_NO)
)
TABLESPACE TS_YKT_CUR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

-------------------------------------------------------
INSERT INTO YKT_CUR.T_PIF_CUR_SYSPARA (ID, VALUE, PARA_NAME, USETIME, OPTIME, UNIT, COMMENTS, IS_DISPLAY)
values (17, '50.00', '退卡允许金额上限', '20001212121212', '20001212121212', '', null, '1');

insert into YKT_CUR.T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG)
values (847233, '网银转账', null, null);
insert into YKT_CUR.T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG)
values (847140, '账户扣款', null, null);



insert into YKT_CUR.T_TIF_SUBJECT (SUBNO, SUBNAME, SUBTYPE, DIRECT, KIND, FATHER, "LEVEL", ENDFLAG, SPARE1, SPARE2, SPARE3)
values ('507', '主营业务成本', 5, 2, 0, '530', 2, 1, '565', null, null);

insert into YKT_CUR.T_AIF_ACCOUNT (ACCOUNT_ID, ACT_TYPE, CUSTOMER_ID, CUT_NAME, CUT_TYPE, STUEMP_NO, CARD_ID, PURSE_ID, CARD_TYPE, SUBNO, PASSWORD, CURRENT_STATE, ISAUTOTRA, LAST_BALA, LAST_FREEBALA, LAST_FROZEBALA, CUR_BALA, CUR_FREEBALA, CUR_FROZEBALA, OUT_BALA, IN_BALA, OUT_COUNT, IN_COUNT, CARD_BALANCE, NOBALA_NUM, CONSUME_COUNT, OPEN_DATE, OPEN_TIME, CLOSE_DATE, CLOSE_TIME, RESERVE_1, RESERVE_2, RESERVE_3, COMMENTS, DEPOSIT_BALA)
values ('5071            ', 7, 0, '主营业务成本', 0, null, 0, 0, 0, '507', null, 1, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, null, null, null, null, null, null, null, null);

insert into YKT_CUR.T_TIF_CFGSPLIT (TXTYPE, TXNAME, DBFLAG, CRFLAG, DBSUBNO, CRSUBNO, DBACTNO, CRACTNO, FUNDTYPE, SUMMARY)
values (64, '营业收入', 1, 2, NULL, '507', null, '5071', null, null);
insert into YKT_CUR.T_TIF_CFGSPLIT (TXTYPE, TXNAME, DBFLAG, CRFLAG, DBSUBNO, CRSUBNO, DBACTNO, CRACTNO, FUNDTYPE, SUMMARY)
values (65, '营业支出', 2, 1, '507', null, '5071', null, null, null);
insert into YKT_CUR.T_TIF_CFGSPLIT (TXTYPE, TXNAME, DBFLAG, CRFLAG, DBSUBNO, CRSUBNO, DBACTNO, CRACTNO, FUNDTYPE, SUMMARY)
values (66, '网银转账', 2, 1, '102', '201', '1021', null, 8, null);
insert into YKT_CUR.T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847233, '66', null, null,'$0');

INSERT INTO YKT_CUR.T_PIF_CUR_SYSPARA (ID, VALUE, PARA_NAME, USETIME, OPTIME, UNIT, COMMENTS, IS_DISPLAY)
values (4001, '中国工商银行上海市分行', '商户结算委托单位名称', '20001212121212', '20070721000000', '', '', '1');
INSERT INTO YKT_CUR.T_PIF_CUR_SYSPARA (ID, VALUE, PARA_NAME, USETIME, OPTIME, UNIT, COMMENTS, IS_DISPLAY)
values (4011, '07501', '商户结算单位委托码', '20001212121212', '20070721000000', '', '', '1');
INSERT INTO YKT_CUR.T_PIF_CUR_SYSPARA (ID, VALUE, PARA_NAME, USETIME, OPTIME, UNIT, COMMENTS, IS_DISPLAY)
values (4021, '07', '商户结算业务编号', '20001212121212', '20070721000000', '', '', '1');
INSERT INTO YKT_CUR.T_PIF_CUR_SYSPARA (ID, VALUE, PARA_NAME, USETIME, OPTIME, UNIT, COMMENTS, IS_DISPLAY)
values (4031, '1001232011200509809', '商户结算单位帐号', '20001212121212', '20070721000000', '', '', '1');

INSERT INTO YKT_CUR.T_PIF_CUR_SYSPARA (ID, VALUE, PARA_NAME, USETIME, OPTIME, UNIT, COMMENTS, IS_DISPLAY)
values (4002, '中国工商银行上海市分行', '手续费清算委托单位名称', '20001212121212', '20070721000000', '', '', '1');
INSERT INTO YKT_CUR.T_PIF_CUR_SYSPARA (ID, VALUE, PARA_NAME, USETIME, OPTIME, UNIT, COMMENTS, IS_DISPLAY)
values (4012, '07501', '手续费清算单位委托码', '20001212121212', '20070721000000', '', '', '1');
INSERT INTO YKT_CUR.T_PIF_CUR_SYSPARA (ID, VALUE, PARA_NAME, USETIME, OPTIME, UNIT, COMMENTS, IS_DISPLAY)
values (4022, '07', '手续费清算业务编号', '20001212121212', '20070721000000', '', '', '1');
INSERT INTO YKT_CUR.T_PIF_CUR_SYSPARA (ID, VALUE, PARA_NAME, USETIME, OPTIME, UNIT, COMMENTS, IS_DISPLAY)
values (4032, '1001232011200509809', '委托单位帐号', '20001212121212', '20070721000000', '', '', '1');

INSERT INTO YKT_CUR.T_PIF_CUR_SYSPARA (ID, VALUE, PARA_NAME, USETIME, OPTIME, UNIT, COMMENTS, IS_DISPLAY)
values (4009, '中国工商银行上海市分行', '充值清算委托单位名称', '20001212121212', '20070721000000', '', '', '1');
INSERT INTO YKT_CUR.T_PIF_CUR_SYSPARA (ID, VALUE, PARA_NAME, USETIME, OPTIME, UNIT, COMMENTS, IS_DISPLAY)
values (4019, '07501', '充值清算单位委托码', '20001212121212', '20070721000000', '', '', '1');
INSERT INTO YKT_CUR.T_PIF_CUR_SYSPARA (ID, VALUE, PARA_NAME, USETIME, OPTIME, UNIT, COMMENTS, IS_DISPLAY)
values (4029, '07', '充值清算业务编号', '20001212121212', '20070721000000', '', '', '1');
INSERT INTO YKT_CUR.T_PIF_CUR_SYSPARA (ID, VALUE, PARA_NAME, USETIME, OPTIME, UNIT, COMMENTS, IS_DISPLAY)
values (4039, '1001232011200509809', '充值清算委托单位帐号', '20001212121212', '20070721000000', '', '', '1');

INSERT INTO YKT_CUR.T_TIF_CFGSPLIT (TXTYPE, TXNAME, DBFLAG, CRFLAG, DBSUBNO, CRSUBNO, DBACTNO, CRACTNO, FUNDTYPE, SUMMARY) 
VALUES (59, '佣金划拨', 1, 2, '202', '505', NULL, '5051', NULL, NULL); 
INSERT INTO YKT_CUR.T_TIF_CFGSPLIT (TXTYPE, TXNAME, DBFLAG, CRFLAG, DBSUBNO, CRSUBNO, DBACTNO, CRACTNO, FUNDTYPE, SUMMARY)
VALUES (60, '佣金折扣', 2, 1, '505', '202', '5051', NULL, NULL, NULL);


