#include	"\src\atlanta\define\product.h"
#include	"\src\atlanta\define\cdc_def.h"
/************************************************************************
*               BY:  M.Kotani
*             DATE:  1996/10/14
*        FILE NAME:  cdc_tbl.h
*       Task ID No:  Not Valid
*      DESCRIPTION:  ∫∞√ﬁØ∏ ⁄ºﬁΩ¿±ƒﬁ⁄Ω√∞ÃﬁŸéQè∆ For MN86063
*        REFERENCE:
************************************************************************/
#if (PRO_CPU == SH7043)
extern UDWORD CodecRegisterAddressTable[CODEC_MAX][9];
#endif
