/*************************************************************************
*	System			: POPLAR/ANZU-L
*	File Name		: cg_rom.h
*	Author			: ãkê≥é˜
*	Date			: 1997/02/07
*	RealTimeOS		: RISCÉÇÉjÉ^
*	Description		: ÇbÇfÅ@ÇqÇnÇlÉGÉäÉA (300000H)
*	Maintenance		: 
*
*	Copyright (C) 1997 Murata Machinery,Ltd. All rights reserved.
*************************************************************************/
#include "\src\atlanta\define\product.h"

extern CONST UBYTE CG_ROM0[0x10000];
extern CONST UBYTE CG_ROM1[0x10000];
