/*	By Y.Suzuki 1996/10/24	*/
/*	Original File jun\usr2:\src\kobe\anzu\def_v\cmn_tbl.h	*/
/* By S.K Spe.21,1995 */
#include "\src\atlanta\define\country.h"

/************************************************************************
 * 国別パラメータ														*
 ************************************************************************/
extern CONST UBYTE CountryTable[COUNTRY_MAX][COUNTRY_DATA_MAX];

/************************************************************************
 * ワンタッチキーにおける配列オフセット値に対するコード					*
 ************************************************************************/
extern CONST UBYTE OnetouchTable[];

/*--------------------------------------*/
/* オプションモデムボード用国別テーブル */
/*--------------------------------------*/
extern CONST UBYTE CountryOptionTable[COUNTRY_MAX][COUNTRY_OPTION_DATA_MAX];

