/*************************************************************************
*	System			: POPLAR/ANZU-L
*	File Name		: fcm_tbl.h
*	Author			: ãkê≥é˜
*	Date			: 1997/06/23
*	RealTimeOS		: RISCÉÇÉjÉ^
*	Description		: 
*	Maintenance		: 
*
*	Copyright (C) 1997 Murata Machinery,Ltd. All rights reserved.
*************************************************************************/
#include "\src\atlanta\define\product.h"
#include "\src\atlanta\define\sysmax.h"

extern CONST UWORD	FaxComErrorMonitorTable[SYS_FAXCOM_ERROR_MONITOR_MAX];
