/************************************************************************
*	System		: POPLAR_B
*	File Name	: FONT_TBL.H
*	Author		: 渡辺一章
*	Date		: 1997/04/09
*	RealTimeOS	: ＲＩＳＣ（ＳＨ７０４３）モニター
*	Description	: フォントテーブル
*	Maintenance	:
*
*	Copyright (C) 1996 Murata Machinery,Ltd. All rights reserved.
*************************************************************************/
#include	"\src\atlanta\define\product.h"
#include	"\src\atlanta\define\font_def.h"

/************************************************************************
*               BY:  K.Watanabe
*             DATE:  97/04/09
*             TYPE:  CONST struct
*      VAR TO HOLD:  
*      DESCRIPTION:  漢字フォントテーブル（ＪＩＳ第２水準）
************************************************************************/
extern CONST struct KanjiFontTableData_t Kanji2[];
