/************************************************************************
*               BY:  O.Kimoto
*             DATE:  1997/01/17
*        FILE NAME:  mlt_tbl.c
*       Task ID No:  Not Valid
*      DESCRIPTION:  ２回線用テーブル定義
*        REFERENCE:
************************************************************************/
#include "\src\atlanta\define\product.h"

#if (PRO_MULTI_LINE == ENABLE)
/************************************************************************
*               BY:  O.Kimoto
*             DATE:  1997/01/17
*             TYPE:  struct
*      VAR TO HOLD:  
*      DESCRIPTION:  回線選択優先順位テーブル
************************************************************************/
extern CONST UBYTE MLT_SelectLineTable[2][9];

#endif
