/*---------------------------------------------------------------------------*/
/*  プロジェクト : Jun/ATLANTA                                               */
/*  ファイル名   : OPT_TBL.C                                                 */
/*  モジュール   :                                                           */
/*               :                                                           */
/*  作成者       : 村田                                                      */
/*  日  付       : 1997/09/10                                                */
/*  概  要       : オプションボード定義ファイル                              */
/*               :                                                           */
/*  修正履歴     :                                                           */
/*---------------------------------------------------------------------------*/
#ifndef opt_tbl_h
	#define	opt_tbl_h
/*------------------------*/
/* インクルードファイル達 */
/*------------------------*/

/*
 * 縮小率テーブル
*/
extern CONST	UWORD	OPT_TxReductionA4_DocTbl[15][10];
extern CONST	UWORD	OPT_TxReductionB4_DocTbl[15][10];
extern CONST	UWORD	OPT_TxReductionA3_DocTbl[15][10];






#endif	/* End of File */
