package org.king.check.domain;

import java.util.Date;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


/**
 * AbstractWorkinfo generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractWorkinfo extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String workinfoid;
     private long serialid;
     private Integer cardnumber;
     private Integer clerkid;
     private String deptid;
     private Date recordtime;
     private String workconfid;
     private String isseat;
     private String description;
     private String workinfotype;
     private String checkdate;
     private String checktime;


    // Constructors

    /** default constructor */
    public AbstractWorkinfo() {
    }

	/** minimal constructor */
    public AbstractWorkinfo(long serialid, Integer cardnumber, Integer clerkid, String deptid, Date recordtime) {
        this.serialid = serialid;
        this.cardnumber = cardnumber;
        this.clerkid = clerkid;
        this.deptid = deptid;
        this.recordtime = recordtime;
    }
    
    /** full constructor */
    public AbstractWorkinfo(long serialid, Integer cardnumber, Integer clerkid, String deptid, Date recordtime, String workconfid, String isseat, String description,  String workinfotype,String checkdate,String checktime) {
        this.serialid = serialid;
        this.cardnumber = cardnumber;
        this.clerkid = clerkid;
        this.deptid = deptid;
        this.recordtime = recordtime;
        this.workconfid = workconfid;
        this.isseat = isseat;
        this.description = description;
        this.workinfotype = workinfotype;
        this.checkdate=checkdate;
        this.checktime=checktime;
    }

   
    // Property accessors

    public String getWorkinfoid() {
        return this.workinfoid;
    }
    
    public void setWorkinfoid(String workinfoid) {
        this.workinfoid = workinfoid;
    }

    public long getSerialid() {
        return this.serialid;
    }
    
    public void setSerialid(long serialid) {
        this.serialid = serialid;
    }

    public Integer getCardnumber() {
		return cardnumber;
	}

	public void setCardnumber(Integer cardnumber) {
		this.cardnumber = cardnumber;
	}

	public Integer getClerkid() {
		return clerkid;
	}

	public void setClerkid(Integer clerkid) {
		this.clerkid = clerkid;
	}

	public String getDeptid() {
        return this.deptid;
    }
    
    public void setDeptid(String deptid) {
        this.deptid = deptid;
    }

    public Date getRecordtime() {
        return this.recordtime;
    }
    
    public void setRecordtime(Date recordtime) {
        this.recordtime = recordtime;
    }

    public String getWorkconfid() {
        return this.workconfid;
    }
    
    public void setWorkconfid(String workconfid) {
        this.workconfid = workconfid;
    }

    public String getIsseat() {
        return this.isseat;
    }
    
    public void setIsseat(String isseat) {
        this.isseat = isseat;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }


    public String getWorkinfotype() {
        return this.workinfotype;
    }
    
    public void setWorkinfotype(String workinfotype) {
        this.workinfotype = workinfotype;
    }

	public String getCheckdate() {
		return checkdate;
	}

	public void setCheckdate(String checkdate) {
		this.checkdate = checkdate;
	}

	public String getChecktime() {
		return checktime;
	}

	public void setChecktime(String checktime) {
		this.checktime = checktime;
	}

	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof AbstractWorkinfo)) {
			return false;
		}
		AbstractWorkinfo rhs = (AbstractWorkinfo) object;
		return new EqualsBuilder().append(this.workconfid, rhs.workconfid)
				.append(this.serialid, rhs.serialid).append(this.cardnumber,
						rhs.cardnumber).append(this.workinfotype,
						rhs.workinfotype).append(this.recordtime,
						rhs.recordtime).append(this.workinfoid,
						rhs.workinfoid).append(this.description,
						rhs.description).append(this.deptid, rhs.deptid)
				.append(this.isseat, rhs.isseat).append(this.clerkid,
						rhs.clerkid).isEquals();
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(-523818475, -840563367).append(
				this.workconfid).append(this.serialid).append(this.cardnumber)
				.append(this.workinfotype).append(this.recordtime).append(
						this.workinfoid).append(this.description).append(
						this.deptid).append(this.isseat).append(this.clerkid)
				.toHashCode();
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
				.append("deptid", this.deptid).append("workinfoid",
						this.workinfoid).append("serialid", this.serialid)
				.append(
						"recordtime", this.recordtime).append("cardnumber",
						this.cardnumber).append("workinfotype",
						this.workinfotype).append("description",
						this.description).append("isseat", this.isseat).append(
						"workconfid", this.workconfid).append("clerkid",
						this.clerkid).toString();
	}
   
    








}