package org.king.check.domain;



/**
 * AbstractWorkinfodetailmap generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractWorkinfodetailmap extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String mapid;
     private Workinfo workinfo;
     private Workinfodetail workinfodetail;


    // Constructors

    /** default constructor */
    public AbstractWorkinfodetailmap() {
    }

    
    /** full constructor */
    public AbstractWorkinfodetailmap(Workinfo workinfo, Workinfodetail workinfodetail) {
        this.workinfo = workinfo;
        this.workinfodetail = workinfodetail;
    }

   
    // Property accessors

    public String getMapid() {
        return this.mapid;
    }
    
    public void setMapid(String mapid) {
        this.mapid = mapid;
    }

    public Workinfo getWorkinfo() {
        return this.workinfo;
    }
    
    public void setWorkinfo(Workinfo workinfo) {
        this.workinfo = workinfo;
    }

    public Workinfodetail getWorkinfodetail() {
        return this.workinfodetail;
    }
    
    public void setWorkinfodetail(Workinfodetail workinfodetail) {
        this.workinfodetail = workinfodetail;
    }
   








}