package org.king.check.domain;



/**
 * AbstractWorktimepara generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractWorktimepara extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String paraid;
     private String ondutytime;
     private String offdutytime;


    // Constructors

    /** default constructor */
    public AbstractWorktimepara() {
    }

    
    /** full constructor */
    public AbstractWorktimepara(String ondutytime, String offdutytime) {
        this.ondutytime = ondutytime;
        this.offdutytime = offdutytime;
    }

   
    // Property accessors

    public String getParaid() {
        return this.paraid;
    }
    
    public void setParaid(String paraid) {
        this.paraid = paraid;
    }

    public String getOndutytime() {
        return this.ondutytime;
    }
    
    public void setOndutytime(String ondutytime) {
        this.ondutytime = ondutytime;
    }

    public String getOffdutytime() {
        return this.offdutytime;
    }
    
    public void setOffdutytime(String offdutytime) {
        this.offdutytime = offdutytime;
    }
   








}