package org.king.check.domain;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * Extraworkinfo generated by MyEclipse - Hibernate Tools
 */
public class Extraworkinfo extends AbstractExtraworkinfo implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Extraworkinfo() {
    }

    
    /** full constructor */
    public Extraworkinfo(Date startdate, Date enddate,Date recodedate,String operatorid) {
        super(startdate, enddate,recodedate,operatorid);        
    }


	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}


	public boolean equals(Object arg0) {
		// TODO Auto-generated method stub
		return false;
	}


	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}
   
}
