package org.king.check.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * Vacation generated by MyEclipse - Hibernate Tools
 */
public class Vacation extends AbstractVacation implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Vacation() {
    }

    
    /** full constructor */
    public Vacation(String departid, String startdate, String enddate, String vactionalname,String isglobe) {
        super(departid, startdate, enddate, vactionalname,isglobe);        
    }


	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}


	public boolean equals(Object arg0) {
		// TODO Auto-generated method stub
		return false;
	}


	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}
   
}
