package org.king.check.domain;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * Workinfo generated by MyEclipse - Hibernate Tools
 */
public class Workinfo extends AbstractWorkinfo implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Workinfo() {
    }

	

    
    /** full constructor */
    public Workinfo(long serialid, Integer cardnumber, Integer clerkid, String deptid, Date recordtime, String workconfid, String isseat, String description, String leaveinfodesc, Integer exceptionmins, String workinfotype,String checkdate,String checktime) {
		super(serialid, cardnumber, clerkid, deptid, recordtime, workconfid, isseat,
				description,  workinfotype,checkdate,checktime);
	}


   
}
