package com.sungard.smartcard.bccsvr.modules.operator.dao;

import com.sungard.smartcard.bccsvr.modules.operator.domain.Operator;
import com.sungard.smartcard.bccsvr.modules.operator.domain.OperatorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    int countByExample(OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    int deleteByExample(OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    int deleteByPrimaryKey(String opercode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    int insert(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    int insertSelective(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    List<Operator> selectByExample(OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    Operator selectByPrimaryKey(String opercode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    int updateByExampleSelective(@Param("record") Operator record, @Param("example") OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    int updateByExample(@Param("record") Operator record, @Param("example") OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    int updateByPrimaryKeySelective(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPERATOR
     *
     * @mbggenerated Fri Dec 30 09:54:41 CST 2011
     */
    int updateByPrimaryKey(Operator record);
}