package org.king.check.domain;

import java.util.Set;

// Generated by MyEclipse - Hibernate Tools



/**
 * Department generated by MyEclipse - Hibernate Tools
 */
public class Department extends AbstractDepartment implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Department() {
    }
    
    /** full constructor */

    public Department(String id, String name, String createYear, String areaCode, String faculty) {
        super(id, name, createYear, areaCode, faculty);
    }
}
