#!/bin/sh

geterrcode >err.sql

if [ $DBTYPE = "DB2" ]; then
db2 <<!
connect to $YKT_DBNAME user $YKT_USER using $YKT_PWD
delete from ykt_cur.t_pif_errcode
commit
quit
!
	db2 -f err.sql -q on
db2 connect reset
else
	sqlplus $YKT_USER/$YKT_PWD@$YKT_DBNAME <<!
@@err.sql
quit
!
fi
