ALTER TABLE YKT_CUR.T_TIF_REGISTER_PAY
 DROP PRIMARY KEY CASCADE;
DROP TABLE YKT_CUR.T_TIF_REGISTER_PAY CASCADE CONSTRAINTS;

CREATE TABLE YKT_CUR.T_TIF_REGISTER_PAY
(
  STUEMP_NO      VARCHAR2(20 BYTE),
  CUT_NAME       VARCHAR2(60 BYTE)              NOT NULL,
  REGISTER_FLAG  NUMBER                         NOT NULL,
  REGISTER_INFO  VARCHAR2(60 BYTE),
  OPERATE_DATE   VARCHAR2(10 BYTE),
  OPERATE_TIME   VARCHAR2(8 BYTE)
)
TABLESPACE TS_YKT_CUR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX YKT_CUR.T_TIF_REGISTER_PAY_PK ON YKT_CUR.T_TIF_REGISTER_PAY
(STUEMP_NO)
LOGGING
TABLESPACE TS_YKT_CUR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE YKT_CUR.T_TIF_REGISTER_PAY ADD (
  CONSTRAINT T_TIF_REGISTER_PAY_PK
 PRIMARY KEY
 (STUEMP_NO)
    USING INDEX 
    TABLESPACE TS_YKT_CUR
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

