package org.king.checkinmanage.domain;

import java.sql.Timestamp;
import java.util.Date;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


/**
 * AbstractStuhealthinfo generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractStuhealthinfo extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String id;
     private String studentNo;
     private String enrollNo;
     private String enrollYear;
     private String ifUnhealthy;
     private String ifDeleted;
     private String creatorId;
     private Timestamp createTime;
     private String updatorId;
     private Timestamp updateTime;


    // Constructors

    /** default constructor */
    public AbstractStuhealthinfo() {
    }

    
    /** full constructor */
    public AbstractStuhealthinfo(String studentNo, String enrollNo, String enrollYear, String ifUnhealthy, String ifDeleted, String creatorId, Timestamp createTime, String updatorId, Timestamp updateTime) {
        this.studentNo = studentNo;
        this.enrollNo = enrollNo;
        this.enrollYear = enrollYear;
        this.ifUnhealthy = ifUnhealthy;
        this.ifDeleted = ifDeleted;
        this.creatorId = creatorId;
        this.createTime = createTime;
        this.updatorId = updatorId;
        this.updateTime = updateTime;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getStudentNo() {
        return this.studentNo;
    }
    
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }

    public String getEnrollNo() {
        return this.enrollNo;
    }
    
    public void setEnrollNo(String enrollNo) {
        this.enrollNo = enrollNo;
    }

    public String getEnrollYear() {
        return this.enrollYear;
    }
    
    public void setEnrollYear(String enrollYear) {
        this.enrollYear = enrollYear;
    }

    public String getIfUnhealthy() {
        return this.ifUnhealthy;
    }
    
    public void setIfUnhealthy(String ifUnhealthy) {
        this.ifUnhealthy = ifUnhealthy;
    }

    public String getIfDeleted() {
        return this.ifDeleted;
    }
    
    public void setIfDeleted(String ifDeleted) {
        this.ifDeleted = ifDeleted;
    }

    public String getCreatorId() {
        return this.creatorId;
    }
    
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public String getUpdatorId() {
        return this.updatorId;
    }
    
    public void setUpdatorId(String updatorId) {
        this.updatorId = updatorId;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }


	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof AbstractStuhealthinfo)) {
			return false;
		}
		AbstractStuhealthinfo rhs = (AbstractStuhealthinfo) object;
		return new EqualsBuilder().append(this.updateTime, rhs.updateTime)
				.append(this.creatorId, rhs.creatorId).append(this.enrollNo,
						rhs.enrollNo).append(this.studentNo, rhs.studentNo)
				.append(this.createTime, rhs.createTime).append(
						this.ifUnhealthy, rhs.ifUnhealthy).append(
						this.updatorId, rhs.updatorId).append(this.enrollYear,
						rhs.enrollYear).append(this.id, rhs.id).append(
						this.ifDeleted, rhs.ifDeleted).isEquals();
	}


	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(-1236431281, -1927533707).append(
				this.updateTime).append(this.creatorId).append(this.enrollNo)
				.append(this.studentNo).append(this.createTime).append(
						this.ifUnhealthy).append(this.updatorId).append(
						this.enrollYear).append(this.id).append(this.ifDeleted)
				.toHashCode();
	}


	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
				.append("updateTime", this.updateTime).append("enrollYear",
						this.enrollYear).append("id", this.id).append(
						"updatorId", this.updatorId).append("createTime",
						this.createTime).append("studentNo", this.studentNo)
				.append("creatorId", this.creatorId).append("ifDeleted",
						this.ifDeleted).append("enrollNo", this.enrollNo)
				.append("ifUnhealthy", this.ifUnhealthy).toString();
	}
   








}