package org.king.checkinmanage.domain;

import java.util.Date;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


/**
 * AbstractStuCardfeeInfo generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractStuCardfeeInfo extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String id;
     private String studentNo;
     private String enrollYear;
     private String ecardPayed;
     private String bathcardNo;
     private String ecardPhoto;
     private String bathcardPayed;
     private String updatorId;
     private Date updateTime;


    // Constructors

    /** default constructor */
    public AbstractStuCardfeeInfo() {
    }

	/** minimal constructor */
    public AbstractStuCardfeeInfo(String studentNo, String enrollYear, String ecardPayed, String bathcardPayed) {
        this.studentNo = studentNo;
        this.enrollYear = enrollYear;
        this.ecardPayed = ecardPayed;
        this.bathcardPayed = bathcardPayed;
    }
    
    /** full constructor */
    public AbstractStuCardfeeInfo(String studentNo, String enrollYear, String ecardPayed, String bathcardNo, String ecardPhoto, String bathcardPayed, String updatorId, Date updateTime) {
        this.studentNo = studentNo;
        this.enrollYear = enrollYear;
        this.ecardPayed = ecardPayed;
        this.bathcardNo = bathcardNo;
        this.ecardPhoto = ecardPhoto;
        this.bathcardPayed = bathcardPayed;
        this.updatorId = updatorId;
        this.updateTime = updateTime;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getStudentNo() {
        return this.studentNo;
    }
    
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }

    public String getEnrollYear() {
        return this.enrollYear;
    }
    
    public void setEnrollYear(String enrollYear) {
        this.enrollYear = enrollYear;
    }

    public String getEcardPayed() {
        return this.ecardPayed;
    }
    
    public void setEcardPayed(String ecardPayed) {
        this.ecardPayed = ecardPayed;
    }

    public String getBathcardNo() {
        return this.bathcardNo;
    }
    
    public void setBathcardNo(String bathcardNo) {
        this.bathcardNo = bathcardNo;
    }

    public String getEcardPhoto() {
        return this.ecardPhoto;
    }
    
    public void setEcardPhoto(String ecardPhoto) {
        this.ecardPhoto = ecardPhoto;
    }

    public String getBathcardPayed() {
        return this.bathcardPayed;
    }
    
    public void setBathcardPayed(String bathcardPayed) {
        this.bathcardPayed = bathcardPayed;
    }

    public String getUpdatorId() {
        return this.updatorId;
    }
    
    public void setUpdatorId(String updatorId) {
        this.updatorId = updatorId;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof AbstractStuCardfeeInfo)) {
			return false;
		}
		AbstractStuCardfeeInfo rhs = (AbstractStuCardfeeInfo) object;
		return new EqualsBuilder().append(this.updateTime, rhs.updateTime)
				.append(this.bathcardNo, rhs.bathcardNo).append(this.studentNo,
						rhs.studentNo).append(this.updatorId, rhs.updatorId)
				.append(this.enrollYear, rhs.enrollYear).append(
						this.bathcardPayed, rhs.bathcardPayed).append(
						this.ecardPayed, rhs.ecardPayed)
				.append(this.id, rhs.id)
				.append(this.ecardPhoto, rhs.ecardPhoto).isEquals();
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(969433355, -1545257485).append(
				this.updateTime).append(this.bathcardNo).append(this.studentNo)
				.append(this.updatorId).append(this.enrollYear).append(
						this.bathcardPayed).append(this.ecardPayed).append(
						this.id).append(this.ecardPhoto).toHashCode();
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
				.append("updateTime", this.updateTime).append("bathcardNo",
						this.bathcardNo).append("studentNo", this.studentNo)
				.append("updatorId", this.updatorId).append("enrollYear",
						this.enrollYear).append("bathcardPayed",
						this.bathcardPayed).append("ecardPayed",
						this.ecardPayed).append("id", this.id).append(
						"ecardPhoto", this.ecardPhoto).toString();
	}
   








}