prompt PL/SQL Developer import file
prompt Created on 2008年10月14日 by Administrator
set feedback off
set define off
prompt Disabling triggers for T_PIF_TRADECODE...
alter table T_PIF_TRADECODE disable all triggers;
prompt Deleting T_PIF_TRADECODE...
delete from T_PIF_TRADECODE;
commit;
prompt Loading T_PIF_TRADECODE...
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847330, '网络收费', null, null, 2, 1, 0, null);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847231, '佣金划拨', null, null, 2, 1, 0, 2);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847232, '佣金折扣', null, null, 2, 1, 0, 2);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (843350, '充值商户开户', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (843351, '充值商户存款', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (843352, '充值商户销户', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (849003, '充值商户充值', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847132, '补贴下发', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847140, '扣款下发', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (240001, '圈存转帐', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (849009, '水控钱包补写', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (240157, '补帐流水', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847101, '发行正式卡', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847105, '收回卡', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847106, '校园卡充值', '1', null, 2, 1, 0, 9);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (843335, '商户开户', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (843336, '商户销户', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847107, '校园卡取款', '1', null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847119, '卡写失败更新卡状态', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847116, '发行过渡临时卡', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847117, '冻结卡', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847118, '解冻卡', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847125, '发行不记名临时卡', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847123, '换卡', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847124, '发行记名临时卡', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (8471040, '补办正式卡', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (930001, '卡挂失', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (930002, '卡解挂', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (930003, '更改卡密码', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (930031, '消费', '1', null, 2, 1, 0, 1);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (930033, '领取补助', '1', null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (930034, 'POS充值', '1', null, 2, 1, 0, 9);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (930036, '充值管理流水', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (241011, '圈存冲正', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847121, '更新卡信息', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847126, '发行贵宾卡(现金)', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847183, '交易冲正', null, null, 2, 1, 0, 1);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847127, '手工借贷', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (240104, '领取补贴', '1', null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847202, '水控充值', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847201, '水控转账', null, '1', 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847206, '电控转账', null, '1', 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847226, '发行授权卡', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847227, '回收授权卡', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847228, '更新授权卡', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847229, '挂失授权卡', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847230, '解挂授权卡', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847220, '充值解款', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847221, '充值解款冲正', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847222, '商户消费解款', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847223, '商户消费解款冲正', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847300, '小钱包充值', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847301, '水控转账', null, '1', 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847306, '采集金额', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (930030, '前置水控转帐', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847134, '电控转账', null, null, 2, 1, 0, 0);
insert into T_PIF_TRADECODE (TRADECODE, TRADEMSG, SPLITCFG, FLAG, RUSH_FLAG, RESTRICT_OPER, RUSH_MAX_DAY, ACCOUNT_FLAG)
values (847233, '考试报名', null, null, 2, 1, 0, 0);
commit;
prompt 57 records loaded
prompt Enabling triggers for T_PIF_TRADECODE...
alter table T_PIF_TRADECODE enable all triggers;
set feedback on
set define on
prompt Done.
