prompt PL/SQL Developer import file
prompt Created on 2008Äê10ÔÂ14ÈÕ by Administrator
set feedback off
set define off
prompt Disabling triggers for T_TIF_CFGTXFEE...
alter table T_TIF_CFGTXFEE disable all triggers;
prompt Deleting T_TIF_CFGTXFEE...
delete from T_TIF_CFGTXFEE;
commit;
prompt Loading T_TIF_CFGTXFEE...
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847330, '72', '0', '1', '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847105, '18,19,20,5,16,6,35,7,36,64,65', null, null, '$0*(1-@5),$0*(1-@5),$2*(1-@6),$0*@5*@1,$2*@6*@1,$0*@5*@2,$2*@6*@2,$0*@5*@3,$2*@6*@3,$4,$5');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847231, '59', null, null, '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847232, '60', null, null, '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 930034, '1,64', null, null, '$0,$2');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 930031, '15,65,64,10', null, null, '$0,$3,$2,$1');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 843351, '67,68', null, null, '$0,$1');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 843352, '69,70', null, null, '$0,$1');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 849003, '71', null, null, '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847116, '13,1', null, null, '20,$0-20');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847107, '5,6,7', '0,0,0', null, '$0*@1,$0*@2,$0*@3');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (17, 847124, '11,1,29,2,30,3', null, null, '20*@1,($0-20)*@1,20*@2,($0-20)*@2,20*@3,($0-20)*@3');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (19, 847126, '11,1,29,2,30,3', null, '-1,0,-1,0,-1,0', '0*@1,($0-0)*@1,0*@2,($0-0)*@2,0*@3,($0-0)*@3');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (12, 847101, '1,2,3', null, '0,0,0', '$0*@1,$0*@2,$0*@3');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 930036, '9', null, '0', '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (11, 847101, '1,2,3', null, '0,0,0', '$0*@1,$0*@2,$0*@3');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847183, '15', '0', '1', '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 8471040, '11,1', null, null, '20,$0-20');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (12, 240001, '22,21', null, '0,0', '$0*0,$0-$0*0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 240001, '21', null, '0', '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (1, 847127, '48', '0', '1', '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 240104, '23', null, '0', '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (12, 240104, '22,23', null, '0,0', '$0*0,$0-$0*0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847201, '54', '0', '1', '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847206, '55', '0', '1', '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 240157, '21', null, '0', '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (12, 240157, '22,21', null, '0,0', '$0*0,$0-$0*0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847106, '1,2,3', null, '0,0,0', '$0*@1,$0*@2,$0*@3');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (13, 847101, '1,2,3', null, '0,0,0', '$0*@1,$0*@2,$0*@3');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (14, 847101, '1,2,3', null, '0,0,0', '$0*@1,$0*@2,$0*@3');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (15, 847101, '1,2,3', null, '0,0,0', '$0*@1,$0*@2,$0*@3');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (16, 847101, '1,2,3', null, '0,0,0', '$0*@1,$0*@2,$0*@3');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (17, 847101, '1,2,3', null, '0,0,0', '$0*@1,$0*@2,$0*@3');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (18, 847183, '15,10', '0,0', '1,1', '$0,($0*0.099)*@4');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847220, '58', null, null, '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847221, '58', null, null, '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (1, 847222, '57', '0', '-1', '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (1, 847223, '57', '0', '-1', '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (17, 240001, '1,10', null, null, '$0*0,$0*0-@3');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847301, '54', '0', '-1', '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847306, '56', '-1', '1', '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 930030, '54', '0', '-1', '$0');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (18, 847125, '1,11', null, null, '$0-20,20');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (18, 847124, '1,11', null, null, '($0-20)*@1,20*@1');
insert into T_TIF_CFGTXFEE (FEE_TYPE, TX_CODE, FEE_LIST, IDXDBACTNO_LIST, IDXCRACTNO_LIST, FORMULA_LIST)
values (0, 847132, '24,49,50', null, null, '$0*@1,$0*@2,$0*@3');
commit;
prompt 45 records loaded
prompt Enabling triggers for T_TIF_CFGTXFEE...
alter table T_TIF_CFGTXFEE enable all triggers;
set feedback on
set define on
prompt Done.
