select cust_id,
a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ab,ac,ad,ae,
(a+b+c+d+e+f+g+h+i+j+k+l+m+n+o+p+q+r+s+t+u+v+w+x+y+z+aa+ab+ac+ad+ae)hj from (
select distinct CUST_ID,
max(case when substr(att_date,7,2)='01' then 1 else 0 end)a,
max(case when substr(att_date,7,2)='02' then 1 else 0 end)b,
max(case when substr(att_date,7,2)='03' then 1 else 0 end)c,
max(case when substr(att_date,7,2)='04' then 1 else 0 end)d,
max(case when substr(att_date,7,2)='05' then 1 else 0 end)e,
max(case when substr(att_date,7,2)='06' then 1 else 0 end)f,
max(case when substr(att_date,7,2)='07' then 1 else 0 end)g,
max(case when substr(att_date,7,2)='08' then 1 else 0 end)h,
max(case when substr(att_date,7,2)='09' then 1 else 0 end)i,
max(case when substr(att_date,7,2)='10' then 1 else 0 end)j,
max(case when substr(att_date,7,2)='11' then 1 else 0 end)k,
max(case when substr(att_date,7,2)='12' then 1 else 0 end)l,
max(case when substr(att_date,7,2)='13' then 1 else 0 end)m,
max(case when substr(att_date,7,2)='14' then 1 else 0 end)n,
max(case when substr(att_date,7,2)='15' then 1 else 0 end)o,
max(case when substr(att_date,7,2)='16' then 1 else 0 end)p,
max(case when substr(att_date,7,2)='17' then 1 else 0 end)q,
max(case when substr(att_date,7,2)='18' then 1 else 0 end)r,
max(case when substr(att_date,7,2)='19' then 1 else 0 end)s,
max(case when substr(att_date,7,2)='20' then 1 else 0 end)t,
max(case when substr(att_date,7,2)='21' then 1 else 0 end)u,
max(case when substr(att_date,7,2)='22' then 1 else 0 end)v,
max(case when substr(att_date,7,2)='23' then 1 else 0 end)w,
max(case when substr(att_date,7,2)='24' then 1 else 0 end)x,
max(case when substr(att_date,7,2)='25' then 1 else 0 end)y,
max(case when substr(att_date,7,2)='26' then 1 else 0 end)z,
max(case when substr(att_date,7,2)='27' then 1 else 0 end)aa,
max(case when substr(att_date,7,2)='28' then 1 else 0 end)ab,
max(case when substr(att_date,7,2)='29' then 1 else 0 end)ac,
max(case when substr(att_date,7,2)='30' then 1 else 0 end)ad,
max(case when substr(att_date,7,2)='31' then 1 else 0 end)ae
  from YKT_CK.T_ATTSERIAL where att_date>'20070801' and att_date<'20070830'
  and cust_id in (select cust_id from ykt_ck.t_clerkinfo)
group by cust_id)t