/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Nov 04 14:44:39 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.kingstargroup.form;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the MAP_DEVICE_TABLE
 * table.  This object should only be instantiated for use with instances 
 * of the MapDeviceTable class.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized 
 * by MyEclipse Hibernate tool integration.
 */
public class MapDeviceTableKey
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private volatile int hashValue = 0;

    /** The value of the ANALYSIS_TIME component of this composite id. */
    private java.lang.String analysisTime;

    /** The value of the DEVICE_ID component of this composite id. */
    private java.lang.Integer deviceId;

    /**
     * Simple constructor of MapDeviceTableKey instances.
     */
    public MapDeviceTableKey()
    {
    }

    /**
     * Returns the value of the analysisTime property.
     * @return java.lang.String
     */
    public java.lang.String getAnalysisTime()
    {
        return analysisTime;
    }

    /**
     * Sets the value of the analysisTime property.
     * @param analysisTime
     */
    public void setAnalysisTime(java.lang.String analysisTime)
    {
        hashValue = 0;
        this.analysisTime = analysisTime;
    }

    /**
     * Returns the value of the deviceId property.
     * @return java.lang.Integer
     */
    public java.lang.Integer getDeviceId()
    {
        return deviceId;
    }

    /**
     * Sets the value of the deviceId property.
     * @param deviceId
     */
    public void setDeviceId(java.lang.Integer deviceId)
    {
        hashValue = 0;
        this.deviceId = deviceId;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the id components.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof MapDeviceTableKey))
            return false;
        MapDeviceTableKey that = (MapDeviceTableKey) rhs;
        if (this.getAnalysisTime() == null || that.getAnalysisTime() == null)
        {
            return false;
        }
        if (! this.getAnalysisTime().equals(that.getAnalysisTime()))
        {
            return false;
        }
        if (this.getDeviceId() == null || that.getDeviceId() == null)
        {
            return false;
        }
        if (! this.getDeviceId().equals(that.getDeviceId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int analysisTimeValue = this.getAnalysisTime() == null ? 0 : this.getAnalysisTime().hashCode();
            result = result * 37 + analysisTimeValue;
            int deviceIdValue = this.getDeviceId() == null ? 0 : this.getDeviceId().hashCode();
            result = result * 37 + deviceIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
