/************************************************************************
*	System		: POPLAR/ANZU_L
*	File Name	: CMN_TBL.C
*	Author		: 渡辺一章
*	Date		: 1996/10/24
*	RealTimeOS	: ＲＩＳＣ（ＳＨ７０４３）モニター
*	Description	: ワンタッチキーの配列オフセット値に対するコード
*	Maintenance	:
*
*	Copyright (C) 1996 Murata Machinery,Ltd. All rights reserved.
*************************************************************************/
#include "\src\atlanta\define\product.h"
#include "\src\atlanta\define\keycode.h"

#if (PRO_KEYPANEL == PANEL_ANZU_L)
 #if (0) /* パネルめくりなしの時 ANZU F-100 */
  CONST UBYTE OnetouchTable[] = {
	ONETOUCH_A_KEY,		ONETOUCH_B_KEY,		ONETOUCH_C_KEY,		ONETOUCH_D_KEY,		ONETOUCH_E_KEY,
	ONETOUCH_F_KEY,		ONETOUCH_G_KEY,		ONETOUCH_H_KEY,		ONETOUCH_I_KEY,		ONETOUCH_J_KEY,
	ONETOUCH_K_KEY,		ONETOUCH_L_KEY,		ONETOUCH_M_KEY,		ONETOUCH_N_KEY,		ONETOUCH_O_KEY,
	ONETOUCH_P_KEY,		ONETOUCH_Q_KEY,		ONETOUCH_R_KEY,		ONETOUCH_S_KEY,		ONETOUCH_T_KEY,
	ONETOUCH_U_KEY,		ONETOUCH_V_KEY,		ONETOUCH_W_KEY,		ONETOUCH_X_KEY,		ONETOUCH_Y_KEY,
	ONETOUCH_Z_KEY,		ONETOUCH_U1_KEY,	ONETOUCH_U2_KEY,	ONETOUCH_U3_KEY,	ONETOUCH_U4_KEY,
  };
 #endif
 /* パネルめくりありの時 */
CONST UBYTE OnetouchTable[] = {
 	ONETOUCH_A_KEY,		ONETOUCH_B_KEY,		ONETOUCH_C_KEY,		ONETOUCH_D_KEY,		ONETOUCH_E_KEY,
 	ONETOUCH_F_KEY,		ONETOUCH_G_KEY,		ONETOUCH_H_KEY,		ONETOUCH_I_KEY,		ONETOUCH_J_KEY,
 	ONETOUCH_K_KEY,		ONETOUCH_L_KEY,		ONETOUCH_M_KEY,		ONETOUCH_N_KEY,		ONETOUCH_O_KEY,
 	ONETOUCH_P_KEY,		ONETOUCH_Q_KEY,		ONETOUCH_R_KEY,		ONETOUCH_S_KEY,		ONETOUCH_T_KEY,
 	ONETOUCH_U_KEY,		ONETOUCH_V_KEY,		ONETOUCH_W_KEY,		ONETOUCH_X_KEY,		ONETOUCH_Y_KEY,
 	ONETOUCH_Z_KEY,		ONETOUCH_a_KEY,		ONETOUCH_b_KEY,		ONETOUCH_c_KEY,		ONETOUCH_d_KEY,
 	ONETOUCH_e_KEY,		ONETOUCH_f_KEY,		ONETOUCH_g_KEY,		ONETOUCH_h_KEY,		ONETOUCH_i_KEY,
 	ONETOUCH_j_KEY,		ONETOUCH_k_KEY,		ONETOUCH_l_KEY,		ONETOUCH_m_KEY,		ONETOUCH_n_KEY,
 	ONETOUCH_o_KEY,		ONETOUCH_p_KEY,		ONETOUCH_q_KEY,		ONETOUCH_r_KEY,		ONETOUCH_s_KEY,
 	ONETOUCH_t_KEY,		ONETOUCH_u_KEY,		ONETOUCH_v_KEY,		ONETOUCH_w_KEY,		ONETOUCH_x_KEY,
 	ONETOUCH_y_KEY,		ONETOUCH_z_KEY,		ONETOUCH_U1_KEY,	ONETOUCH_U2_KEY,	ONETOUCH_U3_KEY,
 	ONETOUCH_U4_KEY,	ONETOUCH_U5_KEY,	ONETOUCH_U6_KEY,	ONETOUCH_U7_KEY,	ONETOUCH_U8_KEY
};
#endif

#if (PRO_KEYPANEL == PANEL_POPLAR_B) || (PRO_KEYPANEL == PANEL_POPLAR_L)
/* POPLAR_Hは、ICHOUにあわせます。 By O.Kimoto 1997/07/16 */
CONST UBYTE OnetouchTable[] = {
	ONETOUCH_01_KEY,	ONETOUCH_02_KEY,	ONETOUCH_03_KEY,	ONETOUCH_04_KEY,	ONETOUCH_05_KEY,
	ONETOUCH_06_KEY,	ONETOUCH_07_KEY,	ONETOUCH_08_KEY,	ONETOUCH_09_KEY,	ONETOUCH_10_KEY,
	ONETOUCH_11_KEY,	ONETOUCH_12_KEY,	ONETOUCH_13_KEY,	ONETOUCH_14_KEY,	ONETOUCH_15_KEY,
	ONETOUCH_16_KEY,	ONETOUCH_17_KEY,	ONETOUCH_18_KEY,	ONETOUCH_19_KEY,	ONETOUCH_20_KEY,
	ONETOUCH_21_KEY,	ONETOUCH_22_KEY,	ONETOUCH_23_KEY,	ONETOUCH_24_KEY,	ONETOUCH_25_KEY,
	ONETOUCH_26_KEY,	ONETOUCH_27_KEY,	ONETOUCH_28_KEY,	ONETOUCH_29_KEY,	ONETOUCH_30_KEY,
	ONETOUCH_31_KEY,	ONETOUCH_32_KEY,	ONETOUCH_33_KEY,	ONETOUCH_34_KEY,	ONETOUCH_35_KEY,
	ONETOUCH_36_KEY,	ONETOUCH_37_KEY,	ONETOUCH_38_KEY,	ONETOUCH_39_KEY,	ONETOUCH_40_KEY,
	ONETOUCH_41_KEY,	ONETOUCH_42_KEY,	ONETOUCH_43_KEY,	ONETOUCH_44_KEY,	ONETOUCH_45_KEY,
	ONETOUCH_46_KEY,	ONETOUCH_47_KEY,	ONETOUCH_48_KEY,	ONETOUCH_49_KEY,	ONETOUCH_50_KEY,
	ONETOUCH_51_KEY,	ONETOUCH_52_KEY,	ONETOUCH_53_KEY,	ONETOUCH_54_KEY,	ONETOUCH_55_KEY,
	ONETOUCH_56_KEY,	ONETOUCH_57_KEY,	ONETOUCH_58_KEY,	ONETOUCH_59_KEY,	ONETOUCH_60_KEY,
	ONETOUCH_61_KEY,	ONETOUCH_62_KEY,	ONETOUCH_63_KEY,	ONETOUCH_64_KEY,	ONETOUCH_65_KEY,
	ONETOUCH_66_KEY,	ONETOUCH_67_KEY,	ONETOUCH_68_KEY,	ONETOUCH_69_KEY,	ONETOUCH_70_KEY,
	ONETOUCH_71_KEY,	ONETOUCH_72_KEY
};
#endif
#if (PRO_KEYPANEL == PANEL_POPLAR_H)	/*  By O.Kimoto 1997/07/16 */
	/* 表面のみ定義
	** 裏面の判定は大域変数のシートの状態を見て判定する
	*/
CONST UBYTE OnetouchTable[] = {
	ONETOUCH_01_KEY,	ONETOUCH_02_KEY,	ONETOUCH_03_KEY,	ONETOUCH_04_KEY,	ONETOUCH_05_KEY,
	ONETOUCH_06_KEY,	ONETOUCH_07_KEY,	ONETOUCH_08_KEY,	ONETOUCH_09_KEY,	ONETOUCH_10_KEY,
	ONETOUCH_11_KEY,	ONETOUCH_12_KEY,	ONETOUCH_13_KEY,	ONETOUCH_14_KEY,	ONETOUCH_15_KEY,
	ONETOUCH_16_KEY,	ONETOUCH_17_KEY,	ONETOUCH_18_KEY,	ONETOUCH_19_KEY,	ONETOUCH_20_KEY,
	ONETOUCH_21_KEY,	ONETOUCH_22_KEY,	ONETOUCH_23_KEY,	ONETOUCH_24_KEY,	ONETOUCH_25_KEY,
	ONETOUCH_26_KEY,	ONETOUCH_27_KEY,	ONETOUCH_28_KEY,	ONETOUCH_29_KEY,	ONETOUCH_30_KEY,
	ONETOUCH_31_KEY,	ONETOUCH_32_KEY,	ONETOUCH_33_KEY,	ONETOUCH_34_KEY,	ONETOUCH_35_KEY,
	ONETOUCH_36_KEY,	ONETOUCH_37_KEY,	ONETOUCH_38_KEY,	ONETOUCH_39_KEY,	ONETOUCH_40_KEY
};
#endif

#if (PRO_KEYPANEL == PANEL_SAKAKI)	/* 1998/06/06 H.Yoshikawa */
CONST UBYTE OnetouchTable[] = {
	ONETOUCH_01_KEY,	ONETOUCH_02_KEY,	ONETOUCH_03_KEY,	ONETOUCH_04_KEY,	ONETOUCH_05_KEY,
	ONETOUCH_06_KEY,	ONETOUCH_07_KEY,	ONETOUCH_08_KEY,	ONETOUCH_09_KEY,	ONETOUCH_10_KEY,
	ONETOUCH_11_KEY,	ONETOUCH_12_KEY,	ONETOUCH_13_KEY,	ONETOUCH_14_KEY,	ONETOUCH_15_KEY,
	ONETOUCH_16_KEY,	ONETOUCH_17_KEY,	ONETOUCH_18_KEY,	ONETOUCH_19_KEY,	ONETOUCH_20_KEY,
	ONETOUCH_21_KEY,	ONETOUCH_22_KEY,	ONETOUCH_23_KEY,	ONETOUCH_24_KEY,	ONETOUCH_25_KEY,
	ONETOUCH_26_KEY,	ONETOUCH_27_KEY,	ONETOUCH_28_KEY,	ONETOUCH_29_KEY,	ONETOUCH_30_KEY
};	
#endif

#if (PRO_KEYPANEL == PANEL_HINOKI)	/* Add By H.Fujimura 1998/10/22 */
CONST UBYTE OnetouchTable[] = {
	ONETOUCH_01_KEY,	ONETOUCH_02_KEY,	ONETOUCH_03_KEY,	ONETOUCH_04_KEY,	ONETOUCH_05_KEY,
	ONETOUCH_06_KEY,	ONETOUCH_07_KEY,	ONETOUCH_08_KEY,	ONETOUCH_09_KEY,	ONETOUCH_10_KEY,
	ONETOUCH_11_KEY,	ONETOUCH_12_KEY,	ONETOUCH_13_KEY,	ONETOUCH_14_KEY,	ONETOUCH_15_KEY,
	ONETOUCH_16_KEY,	ONETOUCH_17_KEY,	ONETOUCH_18_KEY,	ONETOUCH_19_KEY,	ONETOUCH_20_KEY,
	ONETOUCH_21_KEY,	ONETOUCH_22_KEY,	ONETOUCH_23_KEY,	ONETOUCH_24_KEY
};
#endif

/* 移植 by SMuratec K.W.Q 2003/07/23 */
#if (PRO_KEYPANEL == PANEL_SATSUKI2)  || (PRO_KEYPANEL == PANEL_STOCKHM2)	/* Add by Y.Kano 2003/07/11 */
CONST UBYTE OnetouchTable[] = {
	ONETOUCH_01_KEY,	ONETOUCH_02_KEY,	ONETOUCH_03_KEY,	ONETOUCH_04_KEY,	ONETOUCH_05_KEY,
	ONETOUCH_06_KEY,	ONETOUCH_07_KEY,	ONETOUCH_08_KEY,	ONETOUCH_09_KEY,	ONETOUCH_10_KEY,
	ONETOUCH_11_KEY,	ONETOUCH_12_KEY,	ONETOUCH_13_KEY,	ONETOUCH_14_KEY,	ONETOUCH_15_KEY,
	ONETOUCH_16_KEY,	ONETOUCH_17_KEY,	ONETOUCH_18_KEY,	ONETOUCH_19_KEY,	ONETOUCH_20_KEY
};
#endif

