h:\src\atlanta\sh7043\mon\mon_time.c(1) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(2) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(2) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(2) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(3) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(3) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(3) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(4) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(4) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(4) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(5) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(5) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(5) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(6) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(6) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(6) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(7) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(7) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(7) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(8) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(9) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(9) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(10) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(10) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(12) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(13) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(13) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(14) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(15) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(16) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(17) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(18) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(19) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(20) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(21) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(21) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(22) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(23) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(24) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(25) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(26) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(27) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(27) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(28) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(29) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(29) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(30) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(31) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(32) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(33) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(33) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(34) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(34) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(35) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(35) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(36) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(36) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(37) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(37) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(38) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(39) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(40) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(41) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(41) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(42) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(42) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(43) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(43) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(44) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(45) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(46) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(47) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(47) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(48) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(48) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(49) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(50) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(51) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(52) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(52) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(53) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(53) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(54) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(54) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(55) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(55) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(56) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(57) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(58) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(59) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(59) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(60) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(60) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(61) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(61) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(62) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(62) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(63) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(64) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(65) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(66) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(66) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(67) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(67) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(68) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(68) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(69) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(69) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(70) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(71) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(72) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(73) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(73) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(74) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(74) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(75) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(75) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(76) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(77) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(78) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(79) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(79) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(81) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(81) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(81) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(82) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(82) : 801 (W) MULTIPLE SYMBOLS
h:\src\atlanta\sh7043\mon\mon_time.c(83) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(84) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(85) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(85) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(86) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(86) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(87) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(87) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(88) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(88) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(89) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(89) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(90) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(91) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(92) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(93) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(93) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(94) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(94) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(95) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(95) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(96) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(97) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(98) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(99) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(99) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(100) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(100) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(101) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(102) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(103) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(104) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(104) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(105) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(105) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(106) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(106) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(107) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(107) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(108) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(109) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(110) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(111) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(111) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(112) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(112) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(113) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(113) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(114) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(114) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(115) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(116) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(117) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(118) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(118) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(119) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(119) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(120) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(120) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(121) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(121) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(122) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(123) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(124) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(125) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(125) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(126) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(126) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(127) : 838 (W) ILLEGAL CHARACTER CODE
h:\src\atlanta\sh7043\mon\mon_time.c(127) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(128) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(129) : 300 (E) ILLEGAL MNEMONIC
h:\src\atlanta\sh7043\mon\mon_time.c(130) : 202 (E) ILLEGAL SYMBOL OR SECTION NAME
h:\src\atlanta\sh7043\mon\mon_time.c(130) : 103 (E) .END NOT FOUND
