/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Oct 19 14:09:12 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.kingstargroup.advquery.doortxdtl;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the T_DOOR_TXDTL
 * table.  This object should only be instantiated for use with instances 
 * of the TDoorTxdtl class.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized 
 * by MyEclipse Hibernate tool integration.
 */
public class TDoorTxdtlKey
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private volatile int hashValue = 0;

    /** The value of the DEVICE_ID component of this composite id. */
    private java.lang.String deviceId;

    /** The value of the SERIAL_NO component of this composite id. */
    private java.lang.Integer serialNo;

    /** The value of the TX_DATE component of this composite id. */
    private java.lang.String txDate;

    /**
     * Simple constructor of TDoorTxdtlKey instances.
     */
    public TDoorTxdtlKey()
    {
    }

    /**
     * Returns the value of the deviceId property.
     * @return java.lang.String
     */
    public java.lang.String getDeviceId()
    {
        return deviceId;
    }

    /**
     * Sets the value of the deviceId property.
     * @param deviceId
     */
    public void setDeviceId(java.lang.String deviceId)
    {
        hashValue = 0;
        this.deviceId = deviceId;
    }

    /**
     * Returns the value of the serialNo property.
     * @return java.lang.Integer
     */
    public java.lang.Integer getSerialNo()
    {
        return serialNo;
    }

    /**
     * Sets the value of the serialNo property.
     * @param serialNo
     */
    public void setSerialNo(java.lang.Integer serialNo)
    {
        hashValue = 0;
        this.serialNo = serialNo;
    }

    /**
     * Returns the value of the txDate property.
     * @return java.lang.String
     */
    public java.lang.String getTxDate()
    {
        return txDate;
    }

    /**
     * Sets the value of the txDate property.
     * @param txDate
     */
    public void setTxDate(java.lang.String txDate)
    {
        hashValue = 0;
        this.txDate = txDate;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the id components.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof TDoorTxdtlKey))
            return false;
        TDoorTxdtlKey that = (TDoorTxdtlKey) rhs;
        if (this.getDeviceId() == null || that.getDeviceId() == null)
        {
            return false;
        }
        if (! this.getDeviceId().equals(that.getDeviceId()))
        {
            return false;
        }
        if (this.getSerialNo() == null || that.getSerialNo() == null)
        {
            return false;
        }
        if (! this.getSerialNo().equals(that.getSerialNo()))
        {
            return false;
        }
        if (this.getTxDate() == null || that.getTxDate() == null)
        {
            return false;
        }
        if (! this.getTxDate().equals(that.getTxDate()))
        {
            return false;
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int deviceIdValue = this.getDeviceId() == null ? 0 : this.getDeviceId().hashCode();
            result = result * 37 + deviceIdValue;
            int serialNoValue = this.getSerialNo() == null ? 0 : this.getSerialNo().hashCode();
            result = result * 37 + serialNoValue;
            int txDateValue = this.getTxDate() == null ? 0 : this.getTxDate().hashCode();
            result = result * 37 + txDateValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
