package org.king.classmanage.domain;

import java.util.Date;


/**
 * AbstractMenuTime generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractMenuTime extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String id;
     private String menuId;
     private Date beginDate;
     private Date beginTime;
     private Date endDate;
     private Date endTime;
     private String memo;
     private String updator;
     private Date updateTime;
     private String schoolId;


    // Constructors

    /** default constructor */
    public AbstractMenuTime() {
    }

    
    /** full constructor */
    public AbstractMenuTime(String menuId, Date beginDate, Date beginTime, Date endDate, Date endTime, String memo, String updator, Date updateTime, String schoolId) {
        this.menuId = menuId;
        this.beginDate = beginDate;
        this.beginTime = beginTime;
        this.endDate = endDate;
        this.endTime = endTime;
        this.memo = memo;
        this.updator = updator;
        this.updateTime = updateTime;
        this.schoolId = schoolId;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    public Date getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }

    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getSchoolId() {
        return this.schoolId;
    }
    
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId;
    }
   








}