package org.king.classmanage.domain;



/**
 * AbstractGzStuTemp generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractGzStuTemp extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String id;
     private String enterenceNo;
     private String stuName;
     private String gender;
     private String birthday;
     private String polityBg;
     private String nationality;
     private String fromProvince;
     private String enrollYear;
     private String department;
     private String majorin;
     private String nation;
     private String district;
     private String familyAddress;
     private String idCard;
     private String postCode;
     private String telephone;
     private String examType;
     private String enrollType;
     private double totalScore;
     private String studentType;
     private String cultureMode;
     private String studentNo;
     private String classId;
     private String ifappdorm;
     private String ifprovidedorm;

    // Constructors

    /** default constructor */
    public AbstractGzStuTemp() {
    }

    
    /** full constructor */
    public AbstractGzStuTemp(String enterenceNo, String stuName, String gender, String birthday, String polityBg, String nationality, String fromProvince, String enrollYear, String department, String majorin, String nation, String district, String familyAddress, String idCard, String postCode, String telephone, String examType, String enrollType, double totalScore, String studentType, String cultureMode, String studentNo,String classId,String ifappdorm,String ifprovidedorm) {
        this.enterenceNo = enterenceNo;
        this.stuName = stuName;
        this.gender = gender;
        this.birthday = birthday;
        this.polityBg = polityBg;
        this.nationality = nationality;
        this.fromProvince = fromProvince;
        this.enrollYear = enrollYear;
        this.department = department;
        this.majorin = majorin;
        this.nation = nation;
        this.district = district;
        this.familyAddress = familyAddress;
        this.idCard = idCard;
        this.postCode = postCode;
        this.telephone = telephone;
        this.examType = examType;
        this.enrollType = enrollType;
        this.totalScore = totalScore;
        this.studentType = studentType;
        this.cultureMode = cultureMode;
        this.studentNo = studentNo;
        this.classId=classId;
        this.ifappdorm=ifappdorm;
        this.ifprovidedorm=ifprovidedorm;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getEnterenceNo() {
        return this.enterenceNo;
    }
    
    public void setEnterenceNo(String enterenceNo) {
        this.enterenceNo = enterenceNo;
    }

    public String getStuName() {
        return this.stuName;
    }
    
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getPolityBg() {
        return this.polityBg;
    }
    
    public void setPolityBg(String polityBg) {
        this.polityBg = polityBg;
    }

    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public String getFromProvince() {
        return this.fromProvince;
    }
    
    public void setFromProvince(String fromProvince) {
        this.fromProvince = fromProvince;
    }

    public String getEnrollYear() {
        return this.enrollYear;
    }
    
    public void setEnrollYear(String enrollYear) {
        this.enrollYear = enrollYear;
    }

    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }

    public String getMajorin() {
        return this.majorin;
    }
    
    public void setMajorin(String majorin) {
        this.majorin = majorin;
    }

    public String getNation() {
        return this.nation;
    }
    
    public void setNation(String nation) {
        this.nation = nation;
    }

    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    public String getFamilyAddress() {
        return this.familyAddress;
    }
    
    public void setFamilyAddress(String familyAddress) {
        this.familyAddress = familyAddress;
    }

    public String getIdCard() {
        return this.idCard;
    }
    
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    public String getPostCode() {
        return this.postCode;
    }
    
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getExamType() {
        return this.examType;
    }
    
    public void setExamType(String examType) {
        this.examType = examType;
    }

    public String getEnrollType() {
        return this.enrollType;
    }
    
    public void setEnrollType(String enrollType) {
        this.enrollType = enrollType;
    }

    public double getTotalScore() {
        return this.totalScore;
    }
    
    public void setTotalScore(double totalScore) {
        this.totalScore = totalScore;
    }

    public String getStudentType() {
        return this.studentType;
    }
    
    public void setStudentType(String studentType) {
        this.studentType = studentType;
    }

    public String getCultureMode() {
        return this.cultureMode;
    }
    
    public void setCultureMode(String cultureMode) {
        this.cultureMode = cultureMode;
    }

    public String getStudentNo() {
        return this.studentNo;
    }
    
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }
   
    public String getClassId() {
        return this.classId;
    }
    
    public void setClassId(String classId) {
        this.classId = classId;
    }


	public String getIfappdorm() {
		return ifappdorm;
	}


	public void setIfappdorm(String ifappdorm) {
		this.ifappdorm = ifappdorm;
	}


	public String getIfprovidedorm() {
		return ifprovidedorm;
	}


	public void setIfprovidedorm(String ifprovidedorm) {
		this.ifprovidedorm = ifprovidedorm;
	}







}