package org.king.classmanage.domain;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;



/**
 * AbstractDistributionTemp generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractDistributionTemp extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String studentId;
     private String collegeId;


    // Constructors

    /** default constructor */
    public AbstractDistributionTemp() {
    }

    
    /** full constructor */
    public AbstractDistributionTemp(String collegeId) {
        this.collegeId = collegeId;
    }

   
    // Property accessors

    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    public String getCollegeId() {
        return this.collegeId;
    }
    
    public void setCollegeId(String collegeId) {
        this.collegeId = collegeId;
    }


	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof AbstractDistributionTemp)) {
			return false;
		}
		AbstractDistributionTemp rhs = (AbstractDistributionTemp) object;
		return new EqualsBuilder().append(this.studentId, rhs.studentId)
				.append(this.collegeId, rhs.collegeId).isEquals();
	}


	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(-1362790829, 1978297479).append(
				this.studentId).append(this.collegeId).toHashCode();
	}


	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
				.append("studentId", this.studentId).append("collegeId",
						this.collegeId).toString();
	}
   








}