package org.king.classmanage.domain;

/**
 * AbstractNHeaderSessionModelId generated by MyEclipse Persistence Tools
 */

public abstract class AbstractNHeaderSessionModelId implements
		java.io.Serializable {

	// Fields

	private String accountId;

	private String pageId;

	private String culumnId;

	// Constructors

	/** default constructor */
	public AbstractNHeaderSessionModelId() {
	}

	/** full constructor */
	public AbstractNHeaderSessionModelId(String accountId, String pageId,
			String culumnId) {
		this.accountId = accountId;
		this.pageId = pageId;
		this.culumnId = culumnId;
	}

	// Property accessors

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getPageId() {
		return this.pageId;
	}

	public void setPageId(String pageId) {
		this.pageId = pageId;
	}

	public String getCulumnId() {
		return this.culumnId;
	}

	public void setCulumnId(String culumnId) {
		this.culumnId = culumnId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbstractNHeaderSessionModelId))
			return false;
		AbstractNHeaderSessionModelId castOther = (AbstractNHeaderSessionModelId) other;

		return ((this.getAccountId() == castOther.getAccountId()) || (this
				.getAccountId() != null
				&& castOther.getAccountId() != null && this.getAccountId()
				.equals(castOther.getAccountId())))
				&& ((this.getPageId() == castOther.getPageId()) || (this
						.getPageId() != null
						&& castOther.getPageId() != null && this.getPageId()
						.equals(castOther.getPageId())))
				&& ((this.getCulumnId() == castOther.getCulumnId()) || (this
						.getCulumnId() != null
						&& castOther.getCulumnId() != null && this
						.getCulumnId().equals(castOther.getCulumnId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAccountId() == null ? 0 : this.getAccountId().hashCode());
		result = 37 * result
				+ (getPageId() == null ? 0 : this.getPageId().hashCode());
		result = 37 * result
				+ (getCulumnId() == null ? 0 : this.getCulumnId().hashCode());
		return result;
	}

}