package org.king.classmanage.domain;

/**
 * AbstractNTableHeadModelId generated by MyEclipse Persistence Tools
 */

public abstract class AbstractNTableHeadModelId implements java.io.Serializable {

	// Fields

	private String pageId;

	private String columnId;

	// Constructors

	/** default constructor */
	public AbstractNTableHeadModelId() {
	}

	/** full constructor */
	public AbstractNTableHeadModelId(String pageId, String columnId) {
		this.pageId = pageId;
		this.columnId = columnId;
	}

	// Property accessors

	public String getPageId() {
		return this.pageId;
	}

	public void setPageId(String pageId) {
		this.pageId = pageId;
	}

	public String getColumnId() {
		return this.columnId;
	}

	public void setColumnId(String columnId) {
		this.columnId = columnId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbstractNTableHeadModelId))
			return false;
		AbstractNTableHeadModelId castOther = (AbstractNTableHeadModelId) other;

		return ((this.getPageId() == castOther.getPageId()) || (this
				.getPageId() != null
				&& castOther.getPageId() != null && this.getPageId().equals(
				castOther.getPageId())))
				&& ((this.getColumnId() == castOther.getColumnId()) || (this
						.getColumnId() != null
						&& castOther.getColumnId() != null && this
						.getColumnId().equals(castOther.getColumnId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPageId() == null ? 0 : this.getPageId().hashCode());
		result = 37 * result
				+ (getColumnId() == null ? 0 : this.getColumnId().hashCode());
		return result;
	}

}