package org.king.classmanage.domain;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;



/**
 * AbstractCollegemanager generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractCollegemanager extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private CollegemanagerId id;


    // Constructors

    /** default constructor */
    public AbstractCollegemanager() {
    }

    

   
    // Property accessors

    public CollegemanagerId getId() {
        return this.id;
    }
    
    public void setId(CollegemanagerId id) {
        this.id = id;
    }




	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof AbstractCollegemanager)) {
			return false;
		}
		AbstractCollegemanager rhs = (AbstractCollegemanager) object;
		return new EqualsBuilder().append(this.id, rhs.id).isEquals();
	}




	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(-2090673231, 321892399).append(this.id)
				.toHashCode();
	}




	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
				.append("id", this.id).toString();
	}
   








}