package org.king.classmanage.domain;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;



/**
 * AbstractClassAlertHis generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractClassAlertHis extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String alertId;
     private String studentId;
     private String classIdO;
     private String classIdN;
     private String operatorId;
     private String operatorTime;


    // Constructors

    /** default constructor */
    public AbstractClassAlertHis() {
    }

    
    /** full constructor */
    public AbstractClassAlertHis(String studentId, String classIdO, String classIdN, String operatorId, String operatorTime) {
        this.studentId = studentId;
        this.classIdO = classIdO;
        this.classIdN = classIdN;
        this.operatorId = operatorId;
        this.operatorTime = operatorTime;
    }

   
    // Property accessors

    public String getAlertId() {
        return this.alertId;
    }
    
    public void setAlertId(String alertId) {
        this.alertId = alertId;
    }

    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    public String getClassIdO() {
        return this.classIdO;
    }
    
    public void setClassIdO(String classIdO) {
        this.classIdO = classIdO;
    }

    public String getClassIdN() {
        return this.classIdN;
    }
    
    public void setClassIdN(String classIdN) {
        this.classIdN = classIdN;
    }

    public String getOperatorId() {
        return this.operatorId;
    }
    
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    public String getOperatorTime() {
        return this.operatorTime;
    }
    
    public void setOperatorTime(String operatorTime) {
        this.operatorTime = operatorTime;
    }


	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof AbstractClassAlertHis)) {
			return false;
		}
		AbstractClassAlertHis rhs = (AbstractClassAlertHis) object;
		return new EqualsBuilder().append(this.studentId, rhs.studentId)
				.append(this.classIdO, rhs.classIdO).append(this.alertId,
						rhs.alertId).append(this.operatorId, rhs.operatorId)
				.append(this.classIdN, rhs.classIdN).append(this.operatorTime,
						rhs.operatorTime).isEquals();
	}


	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(787981679, 1591176567)
				.append(this.studentId).append(this.classIdO).append(
						this.alertId).append(this.operatorId).append(
						this.classIdN).append(this.operatorTime).toHashCode();
	}


	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
				.append("studentId", this.studentId).append("classIdO",
						this.classIdO).append("alertId", this.alertId).append(
						"operatorId", this.operatorId).append("classIdN",
						this.classIdN)
				.append("operatorTime", this.operatorTime).toString();
	}
   








}