package org.king.classmanage.domain;

import java.util.Date;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


/**
 * AbstractStuAdddelhis generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractStuAdddelhis extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String id;
     private String studentNo;
     private String addOrDel;
     private String operatorId;
     private Date operateTime;


    // Constructors

    /** default constructor */
    public AbstractStuAdddelhis() {
    }

    
    /** full constructor */
    public AbstractStuAdddelhis(String studentNo, String addOrDel, String operatorId, Date operateTime) {
        this.studentNo = studentNo;
        this.addOrDel = addOrDel;
        this.operatorId = operatorId;
        this.operateTime = operateTime;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getStudentNo() {
        return this.studentNo;
    }
    
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }

    public String getAddOrDel() {
        return this.addOrDel;
    }
    
    public void setAddOrDel(String addOrDel) {
        this.addOrDel = addOrDel;
    }

    public String getOperatorId() {
        return this.operatorId;
    }
    
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    public Date getOperateTime() {
        return this.operateTime;
    }
    
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }


	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof AbstractStuAdddelhis)) {
			return false;
		}
		AbstractStuAdddelhis rhs = (AbstractStuAdddelhis) object;
		return new EqualsBuilder().append(this.operateTime, rhs.operateTime)
				.append(this.studentNo, rhs.studentNo).append(this.addOrDel,
						rhs.addOrDel).append(this.operatorId, rhs.operatorId)
				.append(this.id, rhs.id).isEquals();
	}


	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(997213561, -905233407).append(
				this.operateTime).append(this.studentNo).append(this.addOrDel)
				.append(this.operatorId).append(this.id).toHashCode();
	}


	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
				.append("operateTime", this.operateTime).append("studentNo",
						this.studentNo).append("addOrDel", this.addOrDel)
				.append("operatorId", this.operatorId).append("id", this.id)
				.toString();
	}
   








}