package org.king.classmanage.domain;

import java.util.HashSet;
import java.util.Set;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * AbstractClassmodel generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractClassmodel extends
		org.king.framework.domain.BaseObject implements java.io.Serializable {

	// Fields

	private String classId;

	private Collegemodel yxCollege;

	private String classNo;

	private String className;

	private String introduction;
	
	private String curYear;

	private Set yxStudents = new HashSet(0);

	// Constructors

	/** default constructor */
	public AbstractClassmodel() {
	}

	/** minimal constructor */
	public AbstractClassmodel(Collegemodel yxCollege, String classNo) {
		this.yxCollege = yxCollege;
		this.classNo = classNo;
	}

	/** full constructor */
	public AbstractClassmodel(Collegemodel yxCollege, String classNo,
			String className, String introduction,String curYear,Set yxStudents) {
		this.yxCollege = yxCollege;
		this.classNo = classNo;
		this.className = className;
		this.introduction = introduction;
		this.curYear=curYear;
		this.yxStudents = yxStudents;
	}

	// Property accessors

	public String getClassId() {
		return this.classId;
	}

	public void setClassId(String classId) {
		this.classId = classId;
	}

	public Collegemodel getYxCollege() {
		return this.yxCollege;
	}

	public void setYxCollege(Collegemodel yxCollege) {
		this.yxCollege = yxCollege;
	}

	public String getClassNo() {
		return this.classNo;
	}

	public void setClassNo(String classNo) {
		this.classNo = classNo;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}
	
	public String getCurYear() {
		return this.curYear;
	}

	public void setCurYear(String curYear) {
		this.curYear = curYear;
	}

	public Set getYxStudents() {
		return this.yxStudents;
	}

	public void setYxStudents(Set yxStudents) {
		this.yxStudents = yxStudents;
	}

	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof AbstractClassmodel)) {
			return false;
		}
		AbstractClassmodel rhs = (AbstractClassmodel) object;
		return new EqualsBuilder().append(this.yxStudents, rhs.yxStudents)
				.append(this.classId, rhs.classId).append(this.classNo,
						rhs.classNo).append(this.className, rhs.className)
				.append(this.yxCollege, rhs.yxCollege).append(
						this.introduction, rhs.introduction).isEquals();
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(1252609783, -528954137).append(
				this.yxStudents).append(this.classId).append(this.classNo)
				.append(this.className).append(this.yxCollege).append(
						this.introduction).toHashCode();
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this).append("yxStudents", this.yxStudents)
				.append("classNo", this.classNo)
				.append("classId", this.classId).append("introduction",
						this.introduction).append("yxCollege", this.yxCollege)
				.append("className", this.className).toString();
	}

}