package org.king.classmanage.domain;



/**
 * ClassInfoViewId generated by MyEclipse - Hibernate Tools
 */

public class ClassInfoViewId  implements java.io.Serializable {


    // Fields    

     private String classId;
     private String classNo;
     private String className;
     private String introduction;
     private String collegeId;
     private String collegeName;
     private String managerId;
     private String managerName;
     private String roleId;


    // Constructors

    /** default constructor */
    public ClassInfoViewId() {
    }

	/** minimal constructor */
    public ClassInfoViewId(String classId, String classNo, String collegeId) {
        this.classId = classId;
        this.classNo = classNo;
        this.collegeId = collegeId;
    }
    

   
    // Property accessors

    public String getClassId() {
        return this.classId;
    }
    
    public void setClassId(String classId) {
        this.classId = classId;
    }

    public String getClassNo() {
        return this.classNo;
    }
    
    public void setClassNo(String classNo) {
        this.classNo = classNo;
    }

    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }

    public String getIntroduction() {
        return this.introduction;
    }
    
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    public String getCollegeId() {
        return this.collegeId;
    }
    
    public void setCollegeId(String collegeId) {
        this.collegeId = collegeId;
    }

    public String getCollegeName() {
        return this.collegeName;
    }
    
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName;
    }

    public String getManagerId() {
        return this.managerId;
    }
    
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    public String getManagerName() {
        return this.managerName;
    }
    
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClassInfoViewId) ) return false;
		 ClassInfoViewId castOther = ( ClassInfoViewId ) other; 
         
		 return ( (this.getClassId()==castOther.getClassId()) || ( this.getClassId()!=null && castOther.getClassId()!=null && this.getClassId().equals(castOther.getClassId()) ) )
 && ( (this.getClassNo()==castOther.getClassNo()) || ( this.getClassNo()!=null && castOther.getClassNo()!=null && this.getClassNo().equals(castOther.getClassNo()) ) )
 && ( (this.getClassName()==castOther.getClassName()) || ( this.getClassName()!=null && castOther.getClassName()!=null && this.getClassName().equals(castOther.getClassName()) ) )
 && ( (this.getIntroduction()==castOther.getIntroduction()) || ( this.getIntroduction()!=null && castOther.getIntroduction()!=null && this.getIntroduction().equals(castOther.getIntroduction()) ) )
 && ( (this.getCollegeId()==castOther.getCollegeId()) || ( this.getCollegeId()!=null && castOther.getCollegeId()!=null && this.getCollegeId().equals(castOther.getCollegeId()) ) )
 && ( (this.getCollegeName()==castOther.getCollegeName()) || ( this.getCollegeName()!=null && castOther.getCollegeName()!=null && this.getCollegeName().equals(castOther.getCollegeName()) ) )
 && ( (this.getManagerId()==castOther.getManagerId()) || ( this.getManagerId()!=null && castOther.getManagerId()!=null && this.getManagerId().equals(castOther.getManagerId()) ) )
 && ( (this.getManagerName()==castOther.getManagerName()) || ( this.getManagerName()!=null && castOther.getManagerName()!=null && this.getManagerName().equals(castOther.getManagerName()) ) )
 && ( (this.getRoleId()==castOther.getRoleId()) || ( this.getRoleId()!=null && castOther.getRoleId()!=null && this.getRoleId().equals(castOther.getRoleId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getClassId() == null ? 0 : this.getClassId().hashCode() );
         result = 37 * result + ( getClassNo() == null ? 0 : this.getClassNo().hashCode() );
         result = 37 * result + ( getClassName() == null ? 0 : this.getClassName().hashCode() );
         result = 37 * result + ( getIntroduction() == null ? 0 : this.getIntroduction().hashCode() );
         result = 37 * result + ( getCollegeId() == null ? 0 : this.getCollegeId().hashCode() );
         result = 37 * result + ( getCollegeName() == null ? 0 : this.getCollegeName().hashCode() );
         result = 37 * result + ( getManagerId() == null ? 0 : this.getManagerId().hashCode() );
         result = 37 * result + ( getManagerName() == null ? 0 : this.getManagerName().hashCode() );
         result = 37 * result + ( getRoleId() == null ? 0 : this.getRoleId().hashCode() );
         return result;
   }   





}