package org.king.classmanage.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * Collegemanager generated by MyEclipse - Hibernate Tools
 */
public class Collegemanager extends AbstractCollegemanager implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Collegemanager() {
    }

    
   
}
