package org.king.classmanage.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * Department generated by MyEclipse - Hibernate Tools
 */
public class Department extends AbstractDepartment implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Department() {
    }

    
    /** full constructor */
    public Department(String isAcademy, String deptName, String EName, String parentdeptCode, Integer deptLevel, String isAvailability, String comments, String dwglm, String bdisplay, String gDisplay,Double bSort,Double gSort,String reserve3) {
        super(isAcademy, deptName, EName, parentdeptCode, deptLevel, isAvailability, comments, dwglm, bdisplay, gDisplay,bSort,gSort,reserve3);        
    }
   
}
