package org.king.classmanage.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * Dictionary generated by MyEclipse - Hibernate Tools
 */
public class Dictionary extends AbstractDictionary implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Dictionary() {
    }

    
    /** full constructor */
    public Dictionary(String dictName, String dictCaption, String dictParent, Double dictSort, String dictParent1, Integer dictAvail) {
        super(dictName, dictCaption, dictParent, dictSort, dictParent1, dictAvail);        
    }
   
}
