package org.king.classmanage.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * DistributionTemp generated by MyEclipse - Hibernate Tools
 */
public class DistributionTemp extends AbstractDistributionTemp implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public DistributionTemp() {
    }

    
    /** full constructor */
    public DistributionTemp(String collegeId) {
        super(collegeId);        
    }
   
}
