package org.king.classmanage.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * Managermanagerrole generated by MyEclipse - Hibernate Tools
 */
public class Managermanagerrole extends AbstractManagermanagerrole implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Managermanagerrole() {
    }

    
   
}
