package org.king.classmanage.domain;

// Generated by MyEclipse Persistence Tools

/**
 * NHeaderSessionModelId generated by MyEclipse Persistence Tools
 */
public class NHeaderSessionModelId extends AbstractNHeaderSessionModelId
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public NHeaderSessionModelId() {
	}

	/** full constructor */
	public NHeaderSessionModelId(String accountId, String pageId,
			String culumnId) {
		super(accountId, pageId, culumnId);
	}

}
