package org.king.classmanage.domain;

// Generated by MyEclipse Persistence Tools

/**
 * NTableHeadModel generated by MyEclipse Persistence Tools
 */
public class NTableHeadModel extends AbstractNTableHeadModel implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public NTableHeadModel() {
	}

	/** minimal constructor */
	public NTableHeadModel(NTableHeadModelId id) {
		super(id);
	}

	/** full constructor */
	public NTableHeadModel(NTableHeadModelId id, String columnName, Integer sort) {
		super(id, columnName, sort);
	}

}
