package org.king.classmanage.domain;
// Generated by MyEclipse - Hibernate Tools



/**
 * StuInfoView generated by MyEclipse - Hibernate Tools
 */
public class StuInfoView extends AbstractStuInfoView implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public StuInfoView() {
    }

    
   
}
