/*==============================================================*/
/* Table: T_GDCTPARA                                            */
/*==============================================================*/
CREATE TABLE YKT_CUR.T_GDCTPARA  (
   PARANAME             VARCHAR(60)                     NOT NULL,
   PARAVAL              VARCHAR(60),
   REMARK               VARCHAR(240),
   PARAFLAG             NUMBER(1),
   CONSTRAINT PK_T_GDCTPARA PRIMARY KEY (PARANAME)
)
PCTFREE 10
INITRANS 1
STORAGE
(
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE TS_YKT_CUR
LOGGING
MONITORING
 NOPARALLEL;

COMMENT ON TABLE YKT_CUR.T_GDCTPARA IS
'T_GDCTPARA-电信参数表';

COMMENT ON COLUMN YKT_CUR.T_GDCTPARA.PARANAME IS
'参数名称';

COMMENT ON COLUMN YKT_CUR.T_GDCTPARA.PARAVAL IS
'参数值';

COMMENT ON COLUMN YKT_CUR.T_GDCTPARA.REMARK IS
'备注';

COMMENT ON COLUMN YKT_CUR.T_GDCTPARA.PARAFLAG IS
'参数标志';

/

INSERT INTO T_GDCTPARA(PARANAME,PARAVAL,REMARK)
VALUES('svrip','10.49.118.250','讯源服务器IP');

INSERT INTO T_GDCTPARA(PARANAME,PARAVAL,REMARK)
VALUES('svrport','8000','讯源服务器PORT');

INSERT INTO T_GDCTPARA(PARANAME,PARAVAL,REMARK)
VALUES('phonenum','13309761112','讯源服务代理商手机号');

INSERT INTO T_GDCTPARA(PARANAME,PARAVAL,REMARK)
VALUES('svrpswd','202cb962ac59075b964b07152d234b70','讯源服务密码');

INSERT INTO T_GDCTPARA(PARANAME,PARAVAL,REMARK)
VALUES('companycode','00000000','企业代码');

INSERT INTO T_GDCTPARA(PARANAME,PARAVAL,REMARK)
VALUES('timeout','2000','与讯源通讯超时时间(毫秒)');

INSERT INTO T_GDCTPARA(PARANAME,PARAVAL,REMARK)
VALUES('transsvrip','10.49.188.13','讯源中转前置机IP');
INSERT INTO T_GDCTPARA(PARANAME,PARAVAL,REMARK)
VALUES('transsvrport','7000','讯源中转前置机PORT');

INSERT INTO T_GDCTPARA(PARANAME,PARAVAL,REMARK)
VALUES('chkfileprefix','GXC_13309761112','对账文件名前缀(不包括结尾的_号)');

COMMIT;


DROP VIEW V_THIRDPARA;
CREATE VIEW V_THIRDPARA(THIRDNAME,PARANAME,PARAVAL,REMARK,PARAFLAG)
AS
SELECT 'GDCT',PARANAME,PARAVAL,REMARK,PARAFLAG FROM T_GDCTPARA;
/

ALTER TABLE YKT_CUR.T_REFNO
 ADD (DRTPHANDLE  VARCHAR2(128));
 
INSERT INTO T_SYSPARA(PARAID,PARAVAL,PARANAME,PARAUNIT,DISPLAYFLAG,REMARK)
VALUES (6,'sungard kingstar gateway common version','通用前置机版本标志','','1','');
COMMIT;


CREATE TABLE YKT_CUR.T_CFGCHKDATE 
(
ACCCHKTYPE INTEGER NOT NULL,
CHKDATE VARCHAR(8) NOT NULL,
ACCDATE	VARCHAR(8) NOT NULL,
CHKFLAG NUMBER(1) DEFAULT 0 NOT NULL,
CHKTYPE	NUMBER(1) DEFAULT 2 NOT NULL,
OPERCODE	VARCHAR(8),
YKTCNT	INTEGER,
YKTBALA	NUMBER(15,2),
THIRDCNT	INTEGER,
THIRDBALA	NUMBER(15,2),
REMARK	VARCHAR(240),
LASTCHKTIME VARCHAR2(30),
PRIMARY KEY (ACCCHKTYPE,CHKDATE)
);
/

ALTER TABLE YKT_CUR.T_CFGACCCHK
 ADD (CHKTIME  VARCHAR2(4));
/
ALTER TABLE YKT_CUR.T_CFGACCCHK
 ADD (CHKTYPE  NUMBER(1));
/


INSERT INTO YKT_CUR.T_CFGACCCHK (ACCCHKTYPE, ACCCHKTYPENAME, ACCCHKFILEPATH, ACCCHKEXCNAME, BCCDRTPNO, BCCFUNCNO,
BCCTIMEOUT, DELFLAG, CHKTIME,  CHKTYPE)
VALUES ( 601,'广州大学城空中充值','/tmp' ,'ca_gzdxc_gdct' ,0, 0,5 ,'0' ,'0900',2 );

COMMIT;

CREATE TABLE YKT_CUR.T_GDCTCHKDTL(
REFNO	VARCHAR(32) NOT NULL,
TRANSDATE	VARCHAR(8) NOT NULL,
TRANSTIME	varchar(6) NOT NULL,
MOBILE	VARCHAR(20),
AMOUNT	NUMBER(15,2),
AMOUNT2	NUMBER(15,2),
CHKRESULT	NUMBER(1),
chkdate	varchar(8),
chktime	varchar(6),
PRIMARY KEY(REFNO)
);
/
CREATE INDEX YKT_CUR.CTCD_IDX ON YKT_CUR.T_GDCTCHKDTL (TRANSDATE);
/
--INSERT INTO YKT_CUR.T_CFGPAYMENT (PAYCODE, SUMMARY, ENABLED, ONLINEPAY, PAYCHKFLAG, PAYEEACCTYPE, SHOPID, BCCFUNCNO, BCCDRTPNO, 
--   IP, PORT, TIMEOUT, LASTSAVED) 
--VALUES ( 3062,'广州空中充值' ,1 ,1,1,0,?,?,?,?,3,'20100105'); 
