/*==============================================================*/
/* Table: T_RPTOPERLEDGER                                       */
/*==============================================================*/
CREATE TABLE YKT_CUR.T_RPTOPERLEDGER  (
   ACCDATE              VARCHAR(8)                      NOT NULL,
   OPERCODE             VARCHAR(8)                      NOT NULL,
   SUBJNO               VARCHAR(6),
   ACCNO                VARCHAR(10)                     NOT NULL,
   TRANSTYPE            INTEGER,
   SUMMARY              VARCHAR(60)                     NOT NULL,
   TRANSCNT             INTEGER,
   DRAMT                NUMBER(15,2),
   CRAMT                NUMBER(15,2),
   CONSTRAINT PK_T_RPTOPERLEDGER PRIMARY KEY (ACCDATE, OPERCODE, ACCNO, SUMMARY)
)
TABLESPACE TS_YKT_CUR;

COMMENT ON TABLE YKT_CUR.T_RPTOPERLEDGER IS
'T_RPTOPERLEDGER-操作员分类账表';

COMMENT ON COLUMN YKT_CUR.T_RPTOPERLEDGER.ACCDATE IS
'业务日期';

COMMENT ON COLUMN YKT_CUR.T_RPTOPERLEDGER.OPERCODE IS
'操作员号';

COMMENT ON COLUMN YKT_CUR.T_RPTOPERLEDGER.SUBJNO IS
'科目号';

COMMENT ON COLUMN YKT_CUR.T_RPTOPERLEDGER.ACCNO IS
'账号';

COMMENT ON COLUMN YKT_CUR.T_RPTOPERLEDGER.TRANSTYPE IS
'交易类型';

COMMENT ON COLUMN YKT_CUR.T_RPTOPERLEDGER.SUMMARY IS
'摘要';

COMMENT ON COLUMN YKT_CUR.T_RPTOPERLEDGER.TRANSCNT IS
'交易次数';

COMMENT ON COLUMN YKT_CUR.T_RPTOPERLEDGER.DRAMT IS
'借方发生额';

COMMENT ON COLUMN YKT_CUR.T_RPTOPERLEDGER.CRAMT IS
'贷方发生额';

insert into ykt_cur.T_CFGSPLIT (TRANSTYPE, FUNDTYPE, OFFLINEFLAG, USECARDFLAG, CALCCARDBAL, DRACCFLAG, DRSUBJNO, DRACCNO, CRACCFLAG, CRSUBJNO, CRACCNO, SUMMARY)
values (234, 3, 0, 1, 1, 'C', '2001', null, 'N', '112102','112102', '销户经费本退款');
commit;