package org.king.rcvmanage.domain;

import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


/**
 * AbstractStuarriveinfo generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractStuarriveinfo extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String id;
     private String enrollNo;
     private Date arriveDate;
     private Time arriveTime;
     private String arrivePlace;
     private String trainNo;
     private String trainRoomNo;
     private Integer companyNum;
     private String ifNeedHelp;
     private String ifNeedBus;
     private String memo;
     private String ifDeleted;
     private String creatorId;
     private Timestamp createTime;
     private String updatorId;
     private Timestamp updateTime;
     private String tempconcact;


    // Constructors

    /** default constructor */
    public AbstractStuarriveinfo() {
    }

	/** minimal constructor */
    public AbstractStuarriveinfo(String enrollNo, Date arriveDate, Time arriveTime, String arrivePlace, String trainNo, String trainRoomNo, Integer companyNum, String ifNeedHelp, String ifNeedBus, String ifDeleted, String creatorId, Timestamp createTime, String updatorId, Timestamp updateTime) {
        this.enrollNo = enrollNo;
        this.arriveDate = arriveDate;
        this.arriveTime = arriveTime;
        this.arrivePlace = arrivePlace;
        this.trainNo = trainNo;
        this.trainRoomNo = trainRoomNo;
        this.companyNum = companyNum;
        this.ifNeedHelp = ifNeedHelp;
        this.ifNeedBus = ifNeedBus;
        this.ifDeleted = ifDeleted;
        this.creatorId = creatorId;
        this.createTime = createTime;
        this.updatorId = updatorId;
        this.updateTime = updateTime;        
    }
    
    /** full constructor */
    public AbstractStuarriveinfo(String enrollNo, Date arriveDate, Time arriveTime, String arrivePlace, String trainNo, String trainRoomNo, Integer companyNum, String ifNeedHelp, String ifNeedBus, String memo, String ifDeleted, String creatorId, Timestamp createTime, String updatorId, Timestamp updateTime,String tempconcact) {
        this.enrollNo = enrollNo;
        this.arriveDate = arriveDate;
        this.arriveTime = arriveTime;
        this.arrivePlace = arrivePlace;
        this.trainNo = trainNo;
        this.trainRoomNo = trainRoomNo;
        this.companyNum = companyNum;
        this.ifNeedHelp = ifNeedHelp;
        this.ifNeedBus = ifNeedBus;
        this.memo = memo;
        this.ifDeleted = ifDeleted;
        this.creatorId = creatorId;
        this.createTime = createTime;
        this.updatorId = updatorId;
        this.updateTime = updateTime;
        this.tempconcact=tempconcact;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getEnrollNo() {
        return this.enrollNo;
    }
    
    public void setEnrollNo(String enrollNo) {
        this.enrollNo = enrollNo;
    }

    public Date getArriveDate() {
        return this.arriveDate;
    }
    
    public void setArriveDate(Date arriveDate) {
        this.arriveDate = arriveDate;
    }

    public Time getArriveTime() {
        return this.arriveTime;
    }
    
    public void setArriveTime(Time arriveTime) {
        this.arriveTime = arriveTime;
    }

    public String getArrivePlace() {
        return this.arrivePlace;
    }
    
    public void setArrivePlace(String arrivePlace) {
        this.arrivePlace = arrivePlace;
    }

    public String getTrainNo() {
        return this.trainNo;
    }
    
    public void setTrainNo(String trainNo) {
        this.trainNo = trainNo;
    }

    public String getTrainRoomNo() {
        return this.trainRoomNo;
    }
    
    public void setTrainRoomNo(String trainRoomNo) {
        this.trainRoomNo = trainRoomNo;
    }

    public Integer getCompanyNum() {
        return this.companyNum;
    }
    
    public void setCompanyNum(Integer companyNum) {
        this.companyNum = companyNum;
    }

    public String getIfNeedHelp() {
        return this.ifNeedHelp;
    }
    
    public void setIfNeedHelp(String ifNeedHelp) {
        this.ifNeedHelp = ifNeedHelp;
    }

    public String getIfNeedBus() {
        return this.ifNeedBus;
    }
    
    public void setIfNeedBus(String ifNeedBus) {
        this.ifNeedBus = ifNeedBus;
    }

    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }

    public String getIfDeleted() {
        return this.ifDeleted;
    }
    
    public void setIfDeleted(String ifDeleted) {
        this.ifDeleted = ifDeleted;
    }

    public String getCreatorId() {
        return this.creatorId;
    }
    
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public String getUpdatorId() {
        return this.updatorId;
    }
    
    public void setUpdatorId(String updatorId) {
        this.updatorId = updatorId;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
    
    public String getTempconcact() {
        return this.tempconcact;
    }
    
    public void setTempconcact(String tempconcact) {
        this.tempconcact = tempconcact;
    }

	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof AbstractStuarriveinfo)) {
			return false;
		}
		AbstractStuarriveinfo rhs = (AbstractStuarriveinfo) object;
		return new EqualsBuilder().append(this.ifNeedHelp, rhs.ifNeedHelp)
				.append(this.updateTime, rhs.updateTime).append(this.memo,
						rhs.memo).append(this.arriveTime, rhs.arriveTime)
				.append(this.arriveDate, rhs.arriveDate).append(
						this.companyNum, rhs.companyNum)
				.append(this.id, rhs.id).append(this.trainNo, rhs.trainNo)
				.append(this.trainRoomNo, rhs.trainRoomNo).append(
						this.creatorId, rhs.creatorId).append(this.enrollNo,
						rhs.enrollNo).append(this.ifNeedBus, rhs.ifNeedBus)
				.append(this.createTime, rhs.createTime).append(
						this.arrivePlace, rhs.arrivePlace).append(
						this.updatorId, rhs.updatorId).append(this.ifDeleted,
						rhs.ifDeleted).isEquals();
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(1351942889, -300301189).append(
				this.ifNeedHelp).append(this.updateTime).append(this.memo)
				.append(this.arriveTime).append(this.arriveDate).append(
						this.companyNum).append(this.id).append(this.trainNo)
				.append(this.trainRoomNo).append(this.creatorId).append(
						this.enrollNo).append(this.ifNeedBus).append(
						this.createTime).append(this.arrivePlace).append(
						this.updatorId).append(this.ifDeleted).toHashCode();
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
				.append("arriveDate", this.arriveDate).append("id", this.id)
				.append("updatorId", this.updatorId).append("createTime",
						this.createTime).append("companyNum", this.companyNum)
				.append("trainRoomNo", this.trainRoomNo).append("creatorId",
						this.creatorId).append("memo", this.memo).append(
						"arriveTime", this.arriveTime).append("updateTime",
						this.updateTime).append("ifNeedBus", this.ifNeedBus)
				.append("arrivePlace", this.arrivePlace).append("ifNeedHelp",
						this.ifNeedHelp).append("trainNo", this.trainNo)
				.append("ifDeleted", this.ifDeleted).append("enrollNo",
						this.enrollNo).toString();
	}
   








}