/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Sep 28 16:27:07 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.kingstargroup.ecard.hibernate.picdelay;

import java.io.Serializable;

/**
 * A class that represents a row in the ECARD_PIC_DELAY table. 
 * You can customize the behavior of this class by editing the class, {@link EcardPicDelay()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractEcardPicDelay 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String curStuempNo;

    /** The value of the simple oldStuempNo property. */
    private java.lang.String oldStuempNo;

    /** The value of the simple status property. */
    private java.lang.String status;

    /**
     * Simple constructor of AbstractEcardPicDelay instances.
     */
    public AbstractEcardPicDelay()
    {
    }

    /**
     * Constructor of AbstractEcardPicDelay instances given a simple primary key.
     * @param curStuempNo
     */
    public AbstractEcardPicDelay(java.lang.String curStuempNo)
    {
        this.setCurStuempNo(curStuempNo);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getCurStuempNo()
    {
        return curStuempNo;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param curStuempNo
     */
    public void setCurStuempNo(java.lang.String curStuempNo)
    {
        this.hashValue = 0;
        this.curStuempNo = curStuempNo;
    }

    /**
     * Return the value of the OLD_STUEMP_NO column.
     * @return java.lang.String
     */
    public java.lang.String getOldStuempNo()
    {
        return this.oldStuempNo;
    }

    /**
     * Set the value of the OLD_STUEMP_NO column.
     * @param oldStuempNo
     */
    public void setOldStuempNo(java.lang.String oldStuempNo)
    {
        this.oldStuempNo = oldStuempNo;
    }

    /**
     * Return the value of the STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the STATUS column.
     * @param status
     */
    public void setStatus(java.lang.String status)
    {
        this.status = status;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof EcardPicDelay))
            return false;
        EcardPicDelay that = (EcardPicDelay) rhs;
        if (this.getCurStuempNo() == null || that.getCurStuempNo() == null)
            return false;
        return (this.getCurStuempNo().equals(that.getCurStuempNo()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int curStuempNoValue = this.getCurStuempNo() == null ? 0 : this.getCurStuempNo().hashCode();
            result = result * 37 + curStuempNoValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
