package org.king.check.domain;

import java.util.Set;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;



/**
 * AbstractDepartment generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractDepartment  implements java.io.Serializable {


    // Fields    

     private String id;
     private String name;
     
     
     private Department parent;
     
     private Set children;


    // Constructors

   

	/** default constructor */
    public AbstractDepartment() {
    }

    
    /** full constructor */
    public AbstractDepartment(String id, String name, Department parent, Set children) {
		this.id = id;
		this.name = name;
		this.parent = parent;
		this.children = children;
	}

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


	public Set getChildren() {
		return children;
	}


	public void setChildren(Set children) {
		this.children = children;
	}


	public Department getParent() {
		return parent;
	}


	public void setParent(Department parent) {
		this.parent = parent;
	}




   








}