/*---------------------------------------------------------------------------*/
/*  プロジェクト : POPLAR/ANZU_L                                             */
/*  ファイル名   : sys_data.h                                                */
/*  作成者       : 橘正樹                                                    */
/*  日  付       : 1997/05/17                                                */
/*  概  要       : フラッシュ書き換えシステム                                */
/*  修正履歴     :                                                           */
/*---------------------------------------------------------------------------*/

extern UWORD	SYS_GeneralTimer;

extern UWORD	SYS_Modem1PortStatus;
extern UWORD	SYS_Modem2PortStatus;
extern UWORD	SYS_ETC_PortStatus;
extern UWORD	SYS_ETC2_PortStatus;
extern UWORD	SYS_LCDC_PortStatus;
extern UWORD	SYS_LCD_DataPortStatus;
extern UWORD	SYS_LED1_PortStatus;
extern UWORD	SYS_LED2_PortStatus;
extern UWORD	SYS_COM_PortStatus;
extern UWORD	SYS_RTC_PortStatus;
extern UWORD	SYS_PADRH_PortStatus;
extern UWORD	SYS_PADRL_PortStatus;
extern UWORD	SYS_PDDRH_PortStatus;

extern UBYTE	SCN_MTPC0_Status;
extern UBYTE	SCN_MTPC1_Status;
extern UBYTE	SCN_MTP0_Status;
extern UBYTE	SCN_MTP1_Status;
extern UBYTE	SCN_SENSTP_Status;
extern UBYTE	SCN_SSTSTP_Status;
extern UBYTE	SCN_SCNINT_Status;
extern UBYTE	SCN_DS2INTR_Status;
extern UBYTE	SCN_BUZZ_1K_Status;
extern UBYTE	SCN_MTCNT_Status;
extern UBYTE	SCN_SCCNT_Status;
extern UBYTE	SCN_INTLNCN_Status;

