/************************************************************************
*	System			: HINOKI
*	File Name		: SCI_DAT.C
*	Author			: •½”ö ‰p“T
*	Date			: 1999/01/13
*	RealTimeOS		: ‚q‚h‚r‚bi‚r‚g‚V‚O‚S‚Rjƒ‚ƒjƒ^[
*	Description		: ‚r‚b‚h—p•Ï”
*	Original File	: 
*	Maintenance		:
*
*	Copyright (C) 1996 Murata Machinery,Ltd. All rights reserved.
*************************************************************************/
#include "\src\atlanta\define\product.h"

extern UBYTE SciError;		/* added by H.Hirao 1999/01/13 */
extern UBYTE SciTxStatus;	/* added by H.Hirao 1999/01/13 */
