package org.king.check.domain;
// Generated by MyEclipse - Hibernate Tools

import org.apache.commons.lang.builder.CompareToBuilder;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;



/**
 * Tworktimeinfo generated by MyEclipse - Hibernate Tools
 */
public class Tworktimeinfo extends AbstractTworktimeinfo implements Comparable, java.io.Serializable {

    // Constructors

    /** default constructor */
    public Tworktimeinfo() {
    }

    
    /** full constructor */
    public Tworktimeinfo(String worktimeName, String ontime1, String offtime1, String ontime2, String offtime2, String ontime3, String offtime3, String ontime4, String offtime4,String deptId) {
        super(worktimeName, ontime1, offtime1, ontime2, offtime2, ontime3, offtime3, ontime4, offtime4,deptId);        
    }


	/**
	 * @see java.lang.Comparable#compareTo(Object)
	 */
	public int compareTo(Object object) {
		Tworktimeinfo myClass = (Tworktimeinfo) object;
		return new CompareToBuilder().toComparison();
	}


	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if (!(object instanceof Tworktimeinfo)) {
			return false;
		}
		Tworktimeinfo rhs = (Tworktimeinfo) object;
		return new EqualsBuilder().isEquals();
	}


	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder(-1863781397, 1822068339).toHashCode();
	}


	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return new ToStringBuilder(this).append("offtime2", this.getOfftime2())
				.append("offtime4", this.getOfftime4()).append("ontime1",
						this.getOntime1()).append("ontime4", this.getOntime4())
				.append("offtime1", this.getOfftime1()).append("worktimeName",
						this.getWorktimeName()).append("ontime2",
						this.getOntime2()).append("ontime3", this.getOntime3())
				.append("offtime3", this.getOfftime3()).append("worktimeId",
						this.getWorktimeId()).toString();
	}
   
}
