package com.kingstargroup.conference.hibernate.form;



/**
 * AbstractTTifSubsidy generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTTifSubsidy  implements java.io.Serializable {


    // Fields    

     private TTifSubsidyId id;
     private String batchNo;
     private Integer seqno;
     private String operCode;
     private Integer cardNo;
     private String summary;
     private String expireDate;
     private Integer billType;
     private String billNo;
     private double amount;
     private String subsidytype;
     private String txDate;
     private String txTime;
     private String getDate;
     private String getTime;
     private String status;
     private String brokerId;
     private String brokerName;


    // Constructors

    /** default constructor */
    public AbstractTTifSubsidy() {
    }

	/** minimal constructor */
    public AbstractTTifSubsidy(TTifSubsidyId id) {
        this.id = id;
    }
    
    /** full constructor */
    public AbstractTTifSubsidy(TTifSubsidyId id, String batchNo, Integer seqno, String operCode, Integer cardNo, String summary, String expireDate, Integer billType, String billNo, double amount, String subsidytype, String txDate, String txTime, String getDate, String getTime, String status, String brokerId, String brokerName) {
        this.id = id;
        this.batchNo = batchNo;
        this.seqno = seqno;
        this.operCode = operCode;
        this.cardNo = cardNo;
        this.summary = summary;
        this.expireDate = expireDate;
        this.billType = billType;
        this.billNo = billNo;
        this.amount = amount;
        this.subsidytype = subsidytype;
        this.txDate = txDate;
        this.txTime = txTime;
        this.getDate = getDate;
        this.getTime = getTime;
        this.status = status;
        this.brokerId = brokerId;
        this.brokerName = brokerName;
    }

   
    // Property accessors

    public TTifSubsidyId getId() {
        return this.id;
    }
    
    public void setId(TTifSubsidyId id) {
        this.id = id;
    }

    public String getBatchNo() {
        return this.batchNo;
    }
    
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    public Integer getSeqno() {
        return this.seqno;
    }
    
    public void setSeqno(Integer seqno) {
        this.seqno = seqno;
    }

    public String getOperCode() {
        return this.operCode;
    }
    
    public void setOperCode(String operCode) {
        this.operCode = operCode;
    }

    public Integer getCardNo() {
        return this.cardNo;
    }
    
    public void setCardNo(Integer cardNo) {
        this.cardNo = cardNo;
    }

    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(String expireDate) {
        this.expireDate = expireDate;
    }

    public Integer getBillType() {
        return this.billType;
    }
    
    public void setBillType(Integer billType) {
        this.billType = billType;
    }

    public String getBillNo() {
        return this.billNo;
    }
    
    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }

    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }

    public String getSubsidytype() {
        return this.subsidytype;
    }
    
    public void setSubsidytype(String subsidytype) {
        this.subsidytype = subsidytype;
    }

    public String getTxDate() {
        return this.txDate;
    }
    
    public void setTxDate(String txDate) {
        this.txDate = txDate;
    }

    public String getTxTime() {
        return this.txTime;
    }
    
    public void setTxTime(String txTime) {
        this.txTime = txTime;
    }

    public String getGetDate() {
        return this.getDate;
    }
    
    public void setGetDate(String getDate) {
        this.getDate = getDate;
    }

    public String getGetTime() {
        return this.getTime;
    }
    
    public void setGetTime(String getTime) {
        this.getTime = getTime;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getBrokerId() {
        return this.brokerId;
    }
    
    public void setBrokerId(String brokerId) {
        this.brokerId = brokerId;
    }

    public String getBrokerName() {
        return this.brokerName;
    }
    
    public void setBrokerName(String brokerName) {
        this.brokerName = brokerName;
    }
   








}