/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Oct 19 16:43:23 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.kingstargroup.advquery.photo;

import java.io.Serializable;

/**
 * A class that represents a row in the T_CIF_PHOTO table. 
 * You can customize the behavior of this class by editing the class, {@link TCifPhoto()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractTCifPhoto 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The simple primary key value. */
    private TCifPhotoKey id;

    /** The value of the simple stuempName property. */
    private java.lang.String stuempName;

    /** The value of the simple deptName property. */
    private java.lang.String deptName;

    /** The value of the simple sCode property. */
    private java.lang.String scode;

    /** The value of the simple isCreatecard property. */
    private java.lang.Integer isCreatecard;

    /** The value of the simple isInschool property. */
    private java.lang.Integer isInschool;

    /** The value of the simple area property. */
    private java.lang.Integer area;

    /** The value of the simple libCardid property. */
    private java.lang.String libCardid;

    /** The value of the simple sex property. */
    private java.lang.String sex;

    /** The value of the simple nation property. */
    private java.lang.Integer nation;

    /** The value of the simple manId property. */
    private java.lang.String manId;

    /** The value of the simple tel property. */
    private java.lang.String tel;

    /** The value of the simple address property. */
    private java.lang.String address;

    /** The value of the simple photoDate property. */
    private java.lang.String photoDate;

    /** The value of the simple photoTime property. */
    private java.lang.String photoTime;

    /** The value of the simple photoNo property. */
    private java.lang.Integer photoNo;

    /** The value of the simple filename property. */
    private java.lang.String filename;

    /** The value of the simple photo property. */
    private java.lang.String photo;

    /** The value of the simple reserve1 property. */
    private java.lang.String reserve1;

    /** The value of the simple reserve2 property. */
    private java.lang.String reserve2;

    /** The value of the simple reserve3 property. */
    private java.lang.Integer reserve3;

    /** The value of the simple reserve4 property. */
    private java.lang.Integer reserve4;

    /** The value of the simple curGrade property. */
    private java.lang.String curGrade;

    /** The value of the simple status property. */
    private java.lang.Integer status;

    /** The value of the simple canTime property. */
    private java.lang.String canTime;

    /**
     * Simple constructor of AbstractTCifPhoto instances.
     */
    public AbstractTCifPhoto()
    {
    }

    /**
     * Constructor of AbstractTCifPhoto instances given a composite primary key.
     * @param id
     */
    public AbstractTCifPhoto(TCifPhotoKey id)
    {
        this.setId(id);
    }

    /**
     * Return the composite id instance that identifies this object.
     * @return TCifPhotoKey
     */
    public TCifPhotoKey getId()
    {
        return this.id;
    }

    /**
     * Set the composite id instance that identifies this object.
     * @param id
     */
    public void setId(TCifPhotoKey id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the STUEMP_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getStuempName()
    {
        return this.stuempName;
    }

    /**
     * Set the value of the STUEMP_NAME column.
     * @param stuempName
     */
    public void setStuempName(java.lang.String stuempName)
    {
        this.stuempName = stuempName;
    }

    /**
     * Return the value of the DEPT_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getDeptName()
    {
        return this.deptName;
    }

    /**
     * Set the value of the DEPT_NAME column.
     * @param deptName
     */
    public void setDeptName(java.lang.String deptName)
    {
        this.deptName = deptName;
    }

    /**
     * Return the value of the S_CODE column.
     * @return java.lang.String
     */
    public java.lang.String getScode()
    {
        return this.scode;
    }

    /**
     * Set the value of the S_CODE column.
     * @param sCode
     */
    public void setScode(java.lang.String sCode)
    {
        this.scode = sCode;
    }

    /**
     * Return the value of the IS_CREATECARD column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getIsCreatecard()
    {
        return this.isCreatecard;
    }

    /**
     * Set the value of the IS_CREATECARD column.
     * @param isCreatecard
     */
    public void setIsCreatecard(java.lang.Integer isCreatecard)
    {
        this.isCreatecard = isCreatecard;
    }

    /**
     * Return the value of the IS_INSCHOOL column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getIsInschool()
    {
        return this.isInschool;
    }

    /**
     * Set the value of the IS_INSCHOOL column.
     * @param isInschool
     */
    public void setIsInschool(java.lang.Integer isInschool)
    {
        this.isInschool = isInschool;
    }

    /**
     * Return the value of the AREA column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getArea()
    {
        return this.area;
    }

    /**
     * Set the value of the AREA column.
     * @param area
     */
    public void setArea(java.lang.Integer area)
    {
        this.area = area;
    }

    /**
     * Return the value of the LIB_CARDID column.
     * @return java.lang.String
     */
    public java.lang.String getLibCardid()
    {
        return this.libCardid;
    }

    /**
     * Set the value of the LIB_CARDID column.
     * @param libCardid
     */
    public void setLibCardid(java.lang.String libCardid)
    {
        this.libCardid = libCardid;
    }

    /**
     * Return the value of the SEX column.
     * @return java.lang.String
     */
    public java.lang.String getSex()
    {
        return this.sex;
    }

    /**
     * Set the value of the SEX column.
     * @param sex
     */
    public void setSex(java.lang.String sex)
    {
        this.sex = sex;
    }

    /**
     * Return the value of the NATION column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getNation()
    {
        return this.nation;
    }

    /**
     * Set the value of the NATION column.
     * @param nation
     */
    public void setNation(java.lang.Integer nation)
    {
        this.nation = nation;
    }

    /**
     * Return the value of the MAN_ID column.
     * @return java.lang.String
     */
    public java.lang.String getManId()
    {
        return this.manId;
    }

    /**
     * Set the value of the MAN_ID column.
     * @param manId
     */
    public void setManId(java.lang.String manId)
    {
        this.manId = manId;
    }

    /**
     * Return the value of the TEL column.
     * @return java.lang.String
     */
    public java.lang.String getTel()
    {
        return this.tel;
    }

    /**
     * Set the value of the TEL column.
     * @param tel
     */
    public void setTel(java.lang.String tel)
    {
        this.tel = tel;
    }

    /**
     * Return the value of the ADDRESS column.
     * @return java.lang.String
     */
    public java.lang.String getAddress()
    {
        return this.address;
    }

    /**
     * Set the value of the ADDRESS column.
     * @param address
     */
    public void setAddress(java.lang.String address)
    {
        this.address = address;
    }

    /**
     * Return the value of the PHOTO_DATE column.
     * @return java.lang.String
     */
    public java.lang.String getPhotoDate()
    {
        return this.photoDate;
    }

    /**
     * Set the value of the PHOTO_DATE column.
     * @param photoDate
     */
    public void setPhotoDate(java.lang.String photoDate)
    {
        this.photoDate = photoDate;
    }

    /**
     * Return the value of the PHOTO_TIME column.
     * @return java.lang.String
     */
    public java.lang.String getPhotoTime()
    {
        return this.photoTime;
    }

    /**
     * Set the value of the PHOTO_TIME column.
     * @param photoTime
     */
    public void setPhotoTime(java.lang.String photoTime)
    {
        this.photoTime = photoTime;
    }

    /**
     * Return the value of the PHOTO_NO column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getPhotoNo()
    {
        return this.photoNo;
    }

    /**
     * Set the value of the PHOTO_NO column.
     * @param photoNo
     */
    public void setPhotoNo(java.lang.Integer photoNo)
    {
        this.photoNo = photoNo;
    }

    /**
     * Return the value of the FILENAME column.
     * @return java.lang.String
     */
    public java.lang.String getFilename()
    {
        return this.filename;
    }

    /**
     * Set the value of the FILENAME column.
     * @param filename
     */
    public void setFilename(java.lang.String filename)
    {
        this.filename = filename;
    }

    /**
     * Return the value of the PHOTO column.
     * @return java.lang.String
     */
    public java.lang.String getPhoto()
    {
        return this.photo;
    }

    /**
     * Set the value of the PHOTO column.
     * @param photo
     */
    public void setPhoto(java.lang.String photo)
    {
        this.photo = photo;
    }

    /**
     * Return the value of the RESERVE_1 column.
     * @return java.lang.String
     */
    public java.lang.String getReserve1()
    {
        return this.reserve1;
    }

    /**
     * Set the value of the RESERVE_1 column.
     * @param reserve1
     */
    public void setReserve1(java.lang.String reserve1)
    {
        this.reserve1 = reserve1;
    }

    /**
     * Return the value of the RESERVE_2 column.
     * @return java.lang.String
     */
    public java.lang.String getReserve2()
    {
        return this.reserve2;
    }

    /**
     * Set the value of the RESERVE_2 column.
     * @param reserve2
     */
    public void setReserve2(java.lang.String reserve2)
    {
        this.reserve2 = reserve2;
    }

    /**
     * Return the value of the RESERVE_3 column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getReserve3()
    {
        return this.reserve3;
    }

    /**
     * Set the value of the RESERVE_3 column.
     * @param reserve3
     */
    public void setReserve3(java.lang.Integer reserve3)
    {
        this.reserve3 = reserve3;
    }

    /**
     * Return the value of the RESERVE_4 column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getReserve4()
    {
        return this.reserve4;
    }

    /**
     * Set the value of the RESERVE_4 column.
     * @param reserve4
     */
    public void setReserve4(java.lang.Integer reserve4)
    {
        this.reserve4 = reserve4;
    }

    /**
     * Return the value of the CUR_GRADE column.
     * @return java.lang.String
     */
    public java.lang.String getCurGrade()
    {
        return this.curGrade;
    }

    /**
     * Set the value of the CUR_GRADE column.
     * @param curGrade
     */
    public void setCurGrade(java.lang.String curGrade)
    {
        this.curGrade = curGrade;
    }

    /**
     * Return the value of the STATUS column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the STATUS column.
     * @param status
     */
    public void setStatus(java.lang.Integer status)
    {
        this.status = status;
    }

    /**
     * Return the value of the CAN_TIME column.
     * @return java.lang.String
     */
    public java.lang.String getCanTime()
    {
        return this.canTime;
    }

    /**
     * Set the value of the CAN_TIME column.
     * @param canTime
     */
    public void setCanTime(java.lang.String canTime)
    {
        this.canTime = canTime;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof TCifPhoto))
            return false;
        TCifPhoto that = (TCifPhoto) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            if (this.getId() == null)
            {
                result = super.hashCode();
            }
            else
            {
                result = this.getId().hashCode();
            }
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
