-- 门禁功能升级的相关数据字典
INSERT INTO YKT_CUR.T_PIF_DICTIONARY ( DICT_NO, DICT_VALUE, DICT_NAME, DICT_CAPTION ) 
VALUES ( 100, '1001', '门禁控制', '常开门' ) ;
INSERT INTO YKT_CUR.T_PIF_DICTIONARY ( DICT_NO, DICT_VALUE, DICT_NAME, DICT_CAPTION ) 
VALUES ( 100, '1002', '门禁控制', '恢复门状态') ;
INSERT INTO YKT_CUR.T_PIF_DICTIONARY ( DICT_NO, DICT_VALUE, DICT_NAME, DICT_CAPTION ) 
VALUES ( 100, '1003', '门禁控制', '开门') ;

INSERT INTO YKT_CUR.T_PIF_DICTIONARY ( DICT_NO, DICT_VALUE, DICT_NAME, DICT_CAPTION ) 
VALUES ( 101, '1', '任务状态', '新任务' ) ;
INSERT INTO YKT_CUR.T_PIF_DICTIONARY ( DICT_NO, DICT_VALUE, DICT_NAME, DICT_CAPTION ) 
VALUES ( 101, '2', '任务状态', '正在执行' ) ;
INSERT INTO YKT_CUR.T_PIF_DICTIONARY ( DICT_NO, DICT_VALUE, DICT_NAME, DICT_CAPTION ) 
VALUES ( 101, '3', '任务状态', '执行失败' ) ;
INSERT INTO YKT_CUR.T_PIF_DICTIONARY ( DICT_NO, DICT_VALUE, DICT_NAME, DICT_CAPTION ) 
VALUES ( 101, '4', '任务状态', '最终失败' ) ;
INSERT INTO YKT_CUR.T_PIF_DICTIONARY ( DICT_NO, DICT_VALUE, DICT_NAME, DICT_CAPTION ) 
VALUES ( 101, '5', '任务状态', '任务过期' ) ;
INSERT INTO YKT_CUR.T_PIF_DICTIONARY ( DICT_NO, DICT_VALUE, DICT_NAME, DICT_CAPTION ) 
VALUES ( 101, '6', '任务状态', '执行成功' ) ;



CREATE TABLE YKT_CUR.T_TIF_PUSH_TASK
(
  TASK_ID        INTEGER                        NOT NULL,
  TASK_SEQ       INTEGER                        DEFAULT 0                     NOT NULL,
  FUNCTION_ID       INTEGER,
  FUNC_GROUP     INTEGER,
  SYS_ID         INTEGER,
  DEVICE_ID      INTEGER,
  ADD_TIME       CHAR(14 BYTE),
  BEGIN_TIME     CHAR(12 BYTE),
  INVALID_TIME   CHAR(14 BYTE),
  EXEC_TIME      VARCHAR2(24 BYTE),
  EXEC_CNT           INTEGER,
  MAX_EXEC       INTEGER,
  NEXT_INTERVAL  INTEGER,
  STATUS         INTEGER,
  FLAG           VARCHAR2(10 BYTE),
  SEND_TYPE      INTEGER,
  ROUTE_ID       INTEGER,
  CONTENT_STR        VARCHAR2(1000 BYTE),
  RET_CODE       VARCHAR2(20 BYTE),
  RET_MSG        VARCHAR2(500 BYTE),
  PRIMARY KEY (TASK_ID)
)
TABLESPACE TS_YKT_CUR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE SEQUENCE S_T_TIF_PUSH_TASK;