package org.king.business.domain;

import java.util.Date;


/**
 * AbstractStudent generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractBmStudent extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String studentNo;
     private String stuName;
     private String gender;
     private String enrollYear;
     private String deptName;
     private String majorName;
     private String curGrade;
     private String curClass;
     private String idType;
     private String idCard;
     private String email;
     private String updator;
     private String updateTime;
     private BmDepartment bmDepartment;
     private BmMajor bmMajor;
     private String deptCode;
     private String majorCode;
      
    // Constructors

    /** default constructor */
    public AbstractBmStudent() {
    }

	/** minimal constructor */
    public AbstractBmStudent(String studentNo) {
        this.studentNo = studentNo;
    }
    
    /** full constructor */
    public AbstractBmStudent(String studentNo, String stuName, String gender, String enrollYear, String deptName, String majorName, String curGrade, String curClass, String idType, String idCard, String email, String updator, String updateTime,BmDepartment bmDepartment,BmMajor bmMajor) {
        this.studentNo = studentNo;
        this.stuName = stuName;
        this.gender = gender;
        this.enrollYear = enrollYear;
        this.deptName = deptName;
        this.majorName = majorName;
        this.curGrade = curGrade;
        this.curClass = curClass;
        this.idType = idType;
        this.idCard = idCard;
        this.email = email;
        this.updator = updator;
        this.updateTime = updateTime;
        this.bmDepartment=bmDepartment;
        this.bmMajor=bmMajor;
    }

   
    // Property accessors

    public String getStudentNo() {
        return this.studentNo;
    }
    
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }

    public String getStuName() {
        return this.stuName;
    }
    
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getEnrollYear() {
        return this.enrollYear;
    }
    
    public void setEnrollYear(String enrollYear) {
        this.enrollYear = enrollYear;
    }

    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    public String getMajorName() {
        return this.majorName;
    }
    
    public void setMajorName(String majorName) {
        this.majorName = majorName;
    }

    public String getCurGrade() {
        return this.curGrade;
    }
    
    public void setCurGrade(String curGrade) {
        this.curGrade = curGrade;
    }

    public String getCurClass() {
        return this.curClass;
    }
    
    public void setCurClass(String curClass) {
        this.curClass = curClass;
    }

    public String getIdType() {
        return this.idType;
    }
    
    public void setIdType(String idType) {
        this.idType = idType;
    }

    public String getIdCard() {
        return this.idCard;
    }
    
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getUpdator() {
        return this.updator;
    }
    
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    public String getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
    
   public void setBmMajor(BmMajor bmMajor) {
	   this.bmMajor=bmMajor;
   }
   
   public void setBmDepartment(BmDepartment bmDepartment) {
	   this.bmDepartment=bmDepartment;
   }
   
   public BmMajor getBmMajor() {
	   return this.bmMajor;
   }
   
   public BmDepartment getBmDepartment() {
	   return this.bmDepartment;
   }







}