package org.king.business.domain;



/**
 * AbstractBmAccessInfo generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractBmAccessInfo extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    // Fields    

     private String id;
     private String userName;
     private String trueName;
     private String accessDate;
     private String accessTime;
     private String ipAddress;


    // Constructors

    /** default constructor */
    public AbstractBmAccessInfo() {
    }

    
    /** full constructor */
    public AbstractBmAccessInfo(String userName, String trueName, String accessDate, String accessTime, String ipAddress) {
        this.userName = userName;
        this.trueName = trueName;
        this.accessDate = accessDate;
        this.accessTime = accessTime;
        this.ipAddress = ipAddress;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getTrueName() {
        return this.trueName;
    }
    
    public void setTrueName(String trueName) {
        this.trueName = trueName;
    }

    public String getAccessDate() {
        return this.accessDate;
    }
    
    public void setAccessDate(String accessDate) {
        this.accessDate = accessDate;
    }

    public String getAccessTime() {
        return this.accessTime;
    }
    
    public void setAccessTime(String accessTime) {
        this.accessTime = accessTime;
    }

    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
   








}