package org.king.business.domain;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * BmTest generated by MyEclipse - Hibernate Tools
 */
public class BmTest extends AbstractBmTest implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public BmTest() {
    }

    
    /** full constructor */
    public BmTest(BmTestCat bmTestCat, String bmBeginDate, String bmBeginTime, String bmEndDate, String bmEndTime, String testDate, String testBeginTime, String testEndTime, String testMemo, String updator, String updateTime) {
        super(bmTestCat, bmBeginDate, bmBeginTime, bmEndDate, bmEndTime, testDate, testBeginTime, testEndTime, testMemo, updator, updateTime);        
    }


	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}


	public boolean equals(Object arg0) {
		// TODO Auto-generated method stub
		return false;
	}


	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}
   
}
