package org.king.business.domain;
// Generated by MyEclipse - Hibernate Tools

import java.sql.Clob;
import java.util.Date;


/**
 * BmTestPublish generated by MyEclipse - Hibernate Tools
 */
public class BmTestPublish extends AbstractBmTestPublish implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public BmTestPublish() {
    }

    
    /** full constructor */
    public BmTestPublish(String title, String body,String ifDisplay,String ifPublic,String creator, String createTime, String updator, String updateTime) {
        super(title, body, ifDisplay,ifPublic,creator, createTime, updator, updateTime);        
    }


	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}


	public boolean equals(Object arg0) {
		// TODO Auto-generated method stub
		return false;
	}


	public int hashCode() {
		// TODO Auto-generated method stub
		return 0;
	}
   
}
